### PR TITLE
Remove the title attribute on the Windows window buttons

### PR DESCRIPTION
**Pull request by j-f1**
See #3338.

### CODE REVIEW

**Comment by j-f1** [comment]
ready for review :)

**Comment by momon** [comment]
This is still an issue for me running the latest version available under windows.

**Comment by j-f1** [comment]
Which version do you have?

**Comment by momon** [comment]
Attaching a screenshot @j-f1 


I purposely moved the about box next to the label (while having the main app minimized) to showcase the present issue.

I also checked for updates from within the app and it says I am running the latest build.

Thanks!

**Comment by momon** [comment]
@j-f1 ignored me.  Wrong place to post.  My bad.

**Pull request merged**
