### PR TITLE
Add Kotlin syntax highlighting

### PR DESCRIPTION
**Pull request by ziggy42**

### CODE REVIEW

**Comment by shiftkey** [comment]
@ziggy42 can you submit a PR to add a sample file to [`desktop/highlighter-tests`](https://github.com/desktop/highlighter-tests), as per [the instructions](https://github.com/desktop/desktop/blob/master/docs/technical/syntax-highlighting.md#i-want-to-add-my-favorite-language)?

**Comment by ziggy42** [comment]
@shiftkey [done](https://github.com/desktop/highlighter-tests/pull/13)

(sorry, I read the instructions after submitting the PR :neutral_face:

**Comment by shiftkey** [comment]
@ziggy42 just needs a merge from `master` to get #3556 integrated

**Comment by ziggy42** [comment]
@shiftkey done!

**Pull request merged**
