### PR TITLE
[rebase] detect and show a dialog containing what needs to be done

### LINKED ISSUE #6548: ask user to resolve rebase conflicts before continuing
Much like the work around handling merge conflicts, this issue is about ensuring the app correctly detects the user is in a rebase (and that conflicts were found) and asks the user to resolve these before continuing.

The mocks for this can be seen in this comment: https://github.com/desktop/desktop/issues/5953#issuecomment-437527414

TODO:

- [x] when an error occurs that indicates a rebase is occurring, show the dialog
- [x] when `git status` detects that a rebase is in progress, verify the dialog is shown
- [x] show the list of files and indicate what needs to be addressed (ala merge conflicts)
- [x] let the user abort the rebase
- [x] when there are no more things to resolve, let the user continue the rebase

### PR DESCRIPTION
**Pull request by shiftkey**
## Overview

Fixes #6548

This PR has evolved to cover detecting a rebase conflict and letting the user continue or abort. It's feature-flagged for development only so the dialog won't be shown until we're ready to ship it.

## Description

The two flows I want to flesh out here are:

 1. detect a rebase with conflicts done externally to Desktop
  - app should show dialog
  - dialog should block while there are conflicts
  - user can abort rebase while underway
  - if no conflicts, let user continue rebase

2. detect when `git pull --rebase` raises an error (see #3422 for tracking issue)
  - error handling is invoked
  - dialog is shown
  - then user is in the flow from scenario 1

I'll follow up on some questions in the PR about the symmetry between Rebase conflicts and Merge conflicts as I'm thinking about them.

TODO:

- [x] when an error occurs that throws a `RebaseConflicts` error from dugite, show the dialog
- [x] when `git status` detects that a rebase is in progress, show a dialog with what needs to be done
- [x] show the list of files and their state
- [x]  the abort button so the user can bail out
- [x]  continue button is enabled when no more conflicts
- [x] need to stage conflicted files before continuing the rebase
- [x] disable `pull --rebase` blocker behind feature flag to enable further testing
- [x] add some tests
- [x] test flows and identify more interesting corner cases
 - [x] add banners for warning and success
- [x] show warning banner when dismissing dialog, warning banner lets you return to dialog
- [x] show success banner after successful rebase
- [x] rebase conflicts dialog shows base branch (if known) and target branch
- [x] extract follow-up tasks as part of these changes
- [x]  rebase on top of #6884 once that is merged

### Duplicated components

 - ~~`app/src/ui/rebase/conflict-files-list.tsx` has been extracted from `app/src/ui/merge-conflicts/merge-conflicts-dialog.tsx` and could be turned into a reusable component - I don't think I've tweaked it too much, gonna wait and see what recent changes @outofambit has been making~~ moved to #6904
 - ~~`app/src/ui/rebase/rebase-conflicts-dialog.tsx` has been heavily influenced by `app/src/ui/merge-conflicts/merge-conflicts-dialog.tsx` but is likely to need a different flow (in particular to show progress while a rebase is occurring in the background) so I'm fine with keeping them separate for now rather than trying to unify them and be too clever~~ this is fine

## Release notes

Notes: detect and guide user through a rebase when encountered in the app

### CODE REVIEW

**Comment by shiftkey** [comment]
For those who are following along with this PR, I've been working on a suite of tests around rebase scenarios in this repository: https://github.com/shiftkey/rebase-test-cases

Why a separate repository?

 - using branches in active repositories is not ideal because of how they evolve over time (new commits added to branches could impact tests, branches could be merged and deleted, etc)
 - active repositories have lots of unimportant history that would be cloned down
 - creating a set of test cases means we can reuse known cases when testing and QA-ing this flow
 - we can add different cases to this repository as we identify things that Desktop needs to support

The repository is setup with a `README` that links off to the specific test cases, which explain in more detail what you're trying to test and how to go about it. I'll keep building on it as I test more rebase cases but please comment here if you have things that you want covered.

I eventually want to move that repository under the `desktop` org so it's not tied to my personal account, but for the moment it's fine there while I get things together. I also intend to enable branch protection on all branches so that you can't force push to change a test case after completing a rebase.

**Comment by shiftkey** [comment]
@billygriffin @ampinsk I've updated the PR to point out some ways in which this branch differs from the designs discussed around resolving conflicts - the designs pre-date our decision to let people dismiss the dialog, and maybe we should incorporate our learnings there. Happy to discuss in detail later in the week if you want to throw ideas around.

**Comment by billygriffin** [comment]
@shiftkey @ampinsk Thanks for the description! I agree that it'll be important for people to get into a "clean" state prior to doing other major actions (switching branches, committing, etc.). My question is whether there's a "manual mode" equivalent of what we did with regular merge conflicts, or if this is a special case where it needs to happen through something more guided. Maybe let's go through a few scenarios on a call to figure that out.

**Comment by shiftkey** [comment]
I've extracted these follow-up tasks that are not blockers on reviewing and merging this PR:

 - #6892 - I'll focus on this as part of testing #6549 and confirming the app correctly supports `pull --rebase`
 - #6891 and #6890 - proposed UI improvements to existing components related to rebase flows

Once #6698  has been merged (and I can rebase this PR one last time) this will be ready for review

**Comment by shiftkey** [comment]
Advice for people testing out this PR - you'll need to trigger conflicts from the command line and then switch to Desktop, as the UI for this #6551 is not in scope until `1.7.0`. I have some pre-canned rebase cases here which will help you to test things out yourself in the meantime: https://github.com/shiftkey/rebase-test-cases (click into each of the links on the root `README`)

**Comment by shiftkey** [comment]
Marking this as `time-sensitive` because it's now a blocker for a number of draft PRs that I'm testing and verifying: #6907 #6913 #6914

**Pull request merged**
