### PR TITLE
Support preview for DDS images

### LINKED ISSUE #5337: Support for .dds image file preview
Hello,
I'd like to suggest the addition of .dds image preview in Github Desktop.

To get a preview here:
image

### PR DESCRIPTION
**Pull request by mkafrin**
Closes #5337

## Description
Uses WebGL2 to render DDS images to a canvas, then extract that canvas image to a dataURL that can be passed into the existing logic to render image previews.

This also necessitates adding the rawContents (buffer) to the Image class so we can use that in the conversion later on. This is technically an optimization since we could decode the base64 contents, but that would introduce an additional (and significant) delay in the conversion that is unnecessary.

The alternative option is to enhance the ImageContainer to be able to render to canvas directly, so it can use canvas for DDS and img for anything else. I played around with this and got pretty far, but kept running into issues so decided to push that off for a potential future enhancement. At the end of the day, this solution produces the same results, just a bit slower due to the toDataURL call to convert the canvas to a dataURL for rendering.

### Screenshots

Preview of DDS in deletion diff:
image

Preview of DDS in addition diff:
image

Preview of DDS in modification diff (in all four modes):
image
image
image
image

## Release notes

Notes: [Added] Add support for DDS image files

### CODE REVIEW

**Review by sergiou87 — CHANGES_REQUESTED** [review]
First of all thanks for your contribution! It looks great overall, but we have some concerns about it:
- We see many dependencies installed to get to render the DDS image in a canvas. Given how (seemingly) "simple" the rendering process is for this, could you try to get rid of all new dependencies (except for `parse-dds`) and just implement the minimum WebGL stuff needed in the `dds-converter.ts` file?
- We have seen in the past a number of security issues related to GPU work, so we were hoping this WebGL render code could be moved to a [utility process](https://www.electronjs.org/docs/latest/api/utility-process) that would run independently from the main and renderer processes.

**Comment by mkafrin** [comment]
Thanks for the review! Both of those suggestions seem like good ideas, I can definitely do them.

**Comment by mkafrin** [comment]
I pushed commits to remove the `gl-shader` and `a-big-triangle` packages, but I've hit a snag with the second request. Correct me if I'm wrong, but from what I'm reading, it seems that the utilityProcess api spawns Node processes. If I'm correct in that assumption, the WebGL rendering can't be offloaded using that, because WebGL is a browser api, and does not exist in Node. Can you think of an alternative path here? And what security concerns do you have regarding it?

**Comment by sergiou87** [comment]
Oops! You're right, I think in this case we'd need a new `BrowserWindow` instance with its own process and WebGL rendering context to perform the operation 🤔 

Sorry about that 😅  and thanks for cleaning up those two dependencies! ❤️ 

> And what security concerns do you have regarding it?

Nothing specific, just being extra cautious 😅

**Comment by mkafrin** [comment]
Hmm, I've been working the new `BrowserWindow` angle, and I think this might be a mistake to pursue. This is a lot of additional complexity and code for not even a specific problem we're trying to solve. There's an additional process (I modeled it similar to the crash process), additional logic in the main process to spawn the new process and handle ipc, additional build step (webpacking the new process code), many new IPCs (one each for ready and quit, one for request to convert DDS, one for response of dataURL), and additional complexity in `ImageContainer`.

Without any specific security concerns we're solving for, is all that worth it? It certainly makes the code harder to process, follow, and work on. And it adds additional opportunities for failures/exceptions. Plus, all that additional complexity has it's own security risks. Not to mention that these are official and long-standing WebGL APIs which are sandboxed and field-tested with thousands (if not a lot more) of websites. Heck, I'd venture to guess that those APIs have way more eyes on them and testing (including pen-testing) then Electron's process separation, IPC, etc.

I've pushed the changes to a separate branch if you'd like to review the commit and tell me if I'm making this way more complicated than needed or missed something obvious https://github.com/mkafrin/github-desktop/commit/d4c5c160d49c4b66685d2b066628df9a74bd9921. However, if that's basically on the mark and what would need to be done to support process separation, I think it's worth reviewing whether it's worth it and if there's a real concern we're solving for.

**Comment by sergiou87** [comment]
Thank you for that! 🙏  I'll discuss your comment with the team and let you know as soon as possible.

**Comment by mkafrin** [comment]
> Thank you for that! 🙏 I'll discuss your comment with the team and let you know as soon as possible.

Any update on this by chance?

**Comment by tidy-dev** [comment]
@mkafrin We appreciate your patience on this, unfortunately, we have not been able to discuss this yet. It may be some time before we can circle back.

**Comment by mkafrin** [comment]
No problem! Just wanted to keep up with it. Thanks for the update!

**Comment by mkafrin** [comment]
Rebased to fix some conflicts and also to remove the type packages in the original commits, rather than having an additional commit on top.

**Comment by mkafrin** [comment]
Any updates by chance? @tidy-dev

**Comment by reanimatedmanx** [comment]
> Any updates by chance? @tidy-dev

Just fork it and pull changes when needed, do you not see how slow they are? Disgusting 

Oct 16 2023
Sept 13 2024

**Comment by sergiou87** [comment]
@mkafrin Sorry it took us this long, it's been a complicated year 😓 We've discussed about this today and agree with your assessment that using a new `BrowserWindow` to render this is overkill, so we're happy to go ahead with your initial approach.

Our only ask at this point is to keep this in beta for some time, so please add a feature flag (see `feature-flag.ts`) and keep all changes gated by it 🙏 

Thank you for your patience!

**Comment by mkafrin** [comment]
Awesome news @sergiou87, thanks for keeping this in mind. Will sync with upstream and add the feature flag stuff.

**Comment by mkafrin** [comment]
@sergiou87 I have synced with upstream and also added the feature flag.

With feature flag false:
image

With feature flag true:
image

**Comment by sergiou87** [comment]
Thank you!! I will try to get this re-reviewed during the week 🤓

**Review by sergiou87 — APPROVED** [review]
Looks good and works as expected! Thank you again for your contribution and patience 🙇‍♂️

**Comment by theolaa** [comment]
Thanks for this guys, gonna be a big help for some of us who work with DDS texture often.

**Comment by akaday** [comment]
"Support preview for DDS images" (#17564), involves adding support for DDS (DirectDraw Surface) image previews using WebGL2. Here’s a summary of the conversation and steps taken:

Summary:
Description: The PR uses WebGL2 to render DDS images to a canvas and then extracts the canvas image to a dataURL for rendering image previews. This required adding the rawContents buffer to the Image class for conversion, optimizing the process.

Initial Concerns: Reviewer @sergiou87 raised concerns about the number of dependencies and security issues related to GPU work. They suggested minimizing dependencies and considering process separation for the WebGL rendering.

Changes and Discussions:

@mkafrin removed unnecessary dependencies but faced challenges with the process separation as WebGL is a browser API.

A detailed discussion ensued about the complexity and practicality of using a new BrowserWindow for the rendering.

Resolution:

After discussion, it was decided to stick with the initial approach but to keep the feature in beta with a feature flag for controlled testing.

@mkafrin added the feature flag and synced with the upstream repository.

**Comment by mkafrin** [comment]
> Looks good and works as expected! Thank you again for your contribution and patience 🙇‍♂️

No problem! Thanks for keeping it in mind and circling back around!

**Pull request merged**
