### PR TITLE
clarify the current SChannel errors and provide workarounds

### LINKED ISSUE #3326: Provide a better error message for schannel errors
We've had a good number of reports of schannel errors. We should parse these errors and present a more helpful dialog.

* https://github.com/desktop/desktop/issues/3300
* https://github.com/desktop/desktop/issues/3316
* https://github.com/desktop/desktop/issues/3260
* https://github.com/desktop/desktop/issues/3156
* https://github.com/desktop/desktop/issues/2920
* https://github.com/desktop/desktop/issues/2884
* https://github.com/desktop/desktop/issues/2471
* https://github.com/desktop/desktop/issues/2452
* https://github.com/desktop/desktop/issues/2414
* https://github.com/desktop/desktop/issues/2187

### PR DESCRIPTION
**Pull request by shiftkey**
Fixes #3326

- [ ] flesh our dialog and flow to show something better than what we currently do
- [ ] write up some notes to explain this situation and provide workarounds
- [ ] talk with the Docs team about incorporating this into `https://help.github.com/desktop/` so it's available everywhere
- [ ] ???

### CODE REVIEW

**Comment by j-f1** [comment]
Will this handle the non-English error message in #3498?

> InitializeSecurityContext failed: Unknown error (0x80092013) - La funci�n de revocaci�n no puede comprobar la revocaci�n debido a que el servidor de revocaci�n est� sin conexi�n.

**Comment by shiftkey** [comment]
@j-f1 then regex is only looking for the start of the error message that Git reports:

```ts
const schannelRe = /schannel: next InitializeSecurityContext failed:/
```

**Comment by shiftkey** [comment]
Parking this for now to address it better upstream https://github.com/git-for-windows/git/issues/1446 - once we agree on that solution and get a fix into Git for Windows, this flow becomes simpler: 

 - detect the error
 - explain the error to the user (no need for docs)
 - ask them if they want to opt-in to disable revocation checks
 - apply global Git config change

**Comment by nocnokneo** [comment]
Since this is still broken out of the box and this issue comes up as a top web search result, here's the quick fix:

```.bat
%LOCALAPPDATA%\GitHubDesktop\app-2.0.4\resources\app\git\cmd\git.exe config --system http.schannelCheckRevoke false
```

(replace `2.0.4` with the version if GitHub Desktop you are using)

**Pull request closed without merging**
