### PR TITLE
Enable diff expansion feature flag

### LINKED ISSUE #7014: Get more context around the code I'm looking at in a diff
At the moment, the context of (lines preceding and following) the diffs is fixed. It would be useful to allow the user to unfold lines around the diff, like in GitHub itself.

For example, this is how a change is currently displayed in GitHub Desktop:
image

This is how it looks like in GitHub on the web (with an unfold button):
image

https://github.com/desktop/desktop/issues/1544 seems related, but I couldn't find this precise issue anywhere.

### PR DESCRIPTION
**Pull request by sergiou87**
Closes #7014 

## Release notes

Notes: [New] Expand diffs to get more context about your changes

### CODE REVIEW

**Review by tidy-dev — APPROVED** [review]
✨

**Review by nottyboi513 — COMMENTED** [review]
why can't change small window of github
**
**

**Comment by nmz787-intel** [comment]
how to use???

**Comment by DonniexSmurko** [comment]
Yea how an what

**Comment by DonniexSmurko** [comment]
What do I do with this I gotta log into my old github

**Pull request merged**
