### PR TITLE
Upgrade to React 16.8.4

### PR DESCRIPTION
**Pull request by say25**
## Overview

**Supports #6685**

## Description

- Upgrade to the latest version of `react`, `react-dom`, `@types/react` & `@types/react-dom`

## Release notes

Notes: No notes

### CODE REVIEW

**Comment by say25** [comment]
@desktop/engineering This is `ready for review` but I can't change this from a draft PR to an open one.

**Comment by shiftkey** [comment]
@say25 I'll enable it now but also figure out how to route that feedback to the team - it seems weird that as the PR author you can't move to "ready for review".

**Comment by say25** [comment]
Seems like the stash workflow on master depends on deprecated functionality as well, build failure will need to be addressed

**Comment by iAmWillShepherd** [comment]
Removed myself from review until this PR is no longer blocked.

**Pull request merged**
