### PR TITLE
update Electron to 5.0.8 to get some bugfixes

### LINKED ISSUE #7978: Desktop preview is empty while in full screen
# Description
Desktop's Mission Control preview is empty when in full screen mode.

## Version
* GitHub Desktop: 2.1.1-beta1
* Operating system: MacOS Mojave

## Steps to Reproduce
1. Full screen Desktop (use the green button)
1. Open mission control

### Expected Behavior
The contents of Desktop is visible in the preview.

### Actual Behavior
A blank white preview appears.

## Additional Information
This is a bug in Electron and was fixed in https://github.com/electron/electron/pull/18661#ref-commit-8a0d03e, but was not back ported to Electron 5.0.x.

Here is a [YouTube video](https://youtu.be/tnAo9_6g6h0) reproducing the behavior on Desktop.

### Logs
Logs are not relevant for this issue.

### PR DESCRIPTION
**Pull request by shiftkey**
## Overview

**Closes #7978**

## Description

 -  [ ] smoke test on macOS
 -  [ ] smoke test on Windows
 -  [ ] smoke test on Linux

## Release notes

Notes: no-notes

### CODE REVIEW

**Comment by shiftkey** [comment]
I'm not sure #7978 has been resolved by this upgrade, as on macOS 10.14.6 I will see the full-screen preview, but then it can revert to a white screen (not sure how to trigger it consistently just yet):





Switching to the full-screen Desktop causes something to update and repaint the preview of the full-screen Desktop app.

@iAmWillShepherd as you've been following this issue upstream, do you think there's anything we need to do inside Desktop to resolve this issue?

**Comment by iAmWillShepherd** [comment]
Looks like this bug still exists in Electron.

Electron_5_0_8

**Comment by iAmWillShepherd** [comment]
Turns out this bug is slightly different from https://github.com/electron/electron/issues/17942 and https://github.com/electron/electron/issues/18410 and exists in Electron 6-0-x as well.

**Comment by shiftkey** [comment]
Closing this out because it's not the complete fix for the bug, and our current version of Electron 5 seems fine otherwise.

**Comment by iAmWillShepherd** [comment]
I've opened https://github.com/electron/electron/issues/19430 for this bug.

**Pull request closed without merging**
