### PR TITLE
Have CLI invoke the app directly

### PR DESCRIPTION
**Pull request by niik**
## Description

In order to reduce our exposed surface area to the web we want to limit the `openLocalRepo` URL-action to only be accessible on the local machine (i.e. via the CLI). Since CLI currently uses the same code path as the web (protocol handlers) to communicate with Desktop that's not possible. So in this PR I'm splitting URLAction into URLAction and CLIAction where CLIAction stems from parsing command line arguments and URLAction comes from protocol handlers. That way we can assign different levels of trust to these operations.

We do this by invoking the main executable directly from the CLI using good old fashion command line arguments instead of using the protocol handler.

I also took the opportunity to simplify the CLI logic a bit and I think it turned out pretty good.

Note that this regresses the CLI support on Linux that was added in https://github.com/desktop/desktop/pull/17018. @shiftkey for this to work on Linux we'd need to be able to resolve the path to the main executable with the only real starting point being the location of the CLI JS file, see https://github.com/desktop/desktop/blob/0410d1f657b8b31df99ff0338d10b69007b54740/app/src/cli/main.ts#L14-L18. If you have a quick solution for this I'd be happy to incorporate it into this PR and if not we can review a follow-up PR later.

## Release notes

Notes:

### CODE REVIEW

**Review by tidy-dev — APPROVED** [review]
✨  Nice cleanup. Makes sense.

**Comment by shiftkey** [comment]
> Note that this regresses the CLI support on Linux that was added in #17018. @shiftkey for this to work on Linux we'd need to be able to resolve the path to the main executable with the only real starting point being the location of the CLI JS file, see

👋🏻 I'm not going to be able to look at this until January, and I have other breakages to look at related to Linux ARM support (not ARM64) so don't wait for me:

```
make: Entering directory '/github/workspace/app/node_modules/keytar/build'
  CXX(target) Release/obj.target/keytar/src/async.o
arm-linux-gnueabihf-g++: error: unrecognized command line option '-std=gnu++20'; did you mean '-std=gnu++03'?
keytar.target.mk:120: recipe for target 'Release/obj.target/keytar/src/async.o' failed
make: Leaving directory '/github/workspace/app/node_modules/keytar/build'
make: *** [Release/obj.target/keytar/src/async.o] Error 1
gyp ERR! build error 
```

**Comment by NickCraver** [comment]
@shiftkey @niik I'm not sure how, but this might have regressed my usual workflow in Windows. I very often change my UI to the current folder of a worktree via `github .` at a PowerShell prompt, but after this change _it doesn't exit_, holding my prompt a tad bit hostage and making things unusable until GitHub closes.

Was this an expected side-effect of the change? I have active dumps from the `--cli-open` process on `3.4.15` x64 Windows 11 (26100.2894), but having no luck with symbols to help confirm.

**Comment by niik** [comment]
> Was this an expected side-effect of the change?

Interesting. I was able to reproduce this and it only happens if GitHub Desktop isn't running when you execute `github .`. If it's running then it seems to work as intended. I'm going to open a new issue for this, I'm hopeful it won't be all that tricky to fix.

**Comment by NickCraver** [comment]
@niik Thanks for fixing this! Very much appreciated daily here <3

**Pull request merged**
