### PR TITLE
Add transitions for notification banner (NDDB)

### PR DESCRIPTION
**Pull request by donokuda**
This pull request adds a dismiss transition for the notification when you've diverged from the default branch.

### CODE REVIEW

**Comment by shiftkey** [comment]
> 🌵🌵🌵**NOTE: This depends on the pull request #4874 to be merged first** 🌵🌵🌵 

@donokuda I'm confused - this is actually targeting #4874,  so it feels like it's something that can be done before we merge #4874. Am I understanding it right?

**Comment by donokuda** [comment]
> @donokuda I'm confused - this is actually targeting #4874, so it feels like it's something that can be done before we merge #4874. Am I understanding it right?

You are right. I have no clue how to write a cactus banner. 😅

**Comment by donokuda** [comment]
> Any pointers on testing the animations?

Yup! Make sure you have a branch that's behind the default branch by any number of commits and switch to the history tab.

**Comment by donokuda** [comment]
> Transitions work great, just gonna call out that the dark theme makes this message stand out - would be nice to get that addressed before shipping NDDB.

"Make it pop" 😄 

Good looking out! I'll take care of that one ASAP.

**Pull request merged**
