### PR TITLE
Style merge button in banner

### PR DESCRIPTION
**Pull request by ampinsk**
This styles the merge button in the notification banner! 

_Targets the `then-i-wanna-merge` branch_

|Light theme|Dark theme|
|---|---|
|screen shot 2018-07-02 at 10 57 41 am|screen shot 2018-07-02 at 10 57 56 am|

### CODE REVIEW

**Comment by ampinsk** [comment]
Hey @niik, @donokuda and weren't sure if `ButtonGroup` was necessary to use here, do you have any thoughts?

**Comment by donokuda** [comment]
@ampinsk Got any thoughts on having the buttons be the same size? I don't have any particularly strong feels either way but thought it looked nice:

**Comment by ampinsk** [comment]
@donokuda I don't feel too strongly either, but my only thought is that it might look more intrusive if the buttons are bigger?

**Comment by donokuda** [comment]
> @donokuda I don't feel too strongly either, but my only thought is that it might look more intrusive if the buttons are bigger?

Yeah, I can see that. I'm fine with leaving it as is. 👍 

I just realized that the font size for the button is bigger than the text in the banner. 😅Can you adding the `.small-button` class to each of the buttons? That should decrease the font-size and keep the buttons compact in the banner.

https://github.com/desktop/desktop/blob/1cd48a0e26fb64fc4c635ffd4f7cbf1478441a2a/app/styles/ui/_button.scss#L81-L85

**Comment by ampinsk** [comment]
@donokuda I agree this looks cleaner ✨ 

screen shot 2018-07-02 at 3 45 33 pm

**Comment by niik** [comment]
> Hey @niik, @donokuda and weren't sure if ButtonGroup was necessary to use here, do you have any thoughts?

I don't think it's necessary. The `ButtonGroup` will switch the order of the actions on Windows and that should be reserved for 'Yes/No'-type actions in dialogs.

Other than that I think this looks great!

**Pull request merged**
