### PR TITLE
Change styles of inline error messages for dialog

### PR DESCRIPTION
**Pull request by http-request**
Change styles for inline error messages for dialog. Issue is  https://github.com/desktop/desktop/issues/2052

### CODE REVIEW

**Comment by iAmWillShepherd** [comment]
@http-request could you post some before and after images for your change?

**Comment by http-request** [comment]
**Before:**

screen shot 2017-12-07 at 15 27 03
screen shot 2017-12-07 at 15 26 51
screen shot 2017-12-07 at 15 26 41

**Comment by http-request** [comment]
**After:**

screen shot 2017-12-07 at 21 39 38
screen shot 2017-12-07 at 21 39 17
screen shot 2017-12-07 at 21 39 05

**Comment by j-f1** [comment]
> the third screenshot

Is there a way to remove the padding on this warning? The dialog already has padding, so it would look nicer IMHO if the padding was 🔥ed.

**Comment by http-request** [comment]
**Updated:**

screen shot 2017-12-08 at 17 20 41

**Comment by joshaber** [comment]
@desktop/design should review this before it lands.

**Comment by niik** [comment]
Hey @http-request, thank you so much for wanting to contribute to GitHub Desktop!

As I said in https://github.com/desktop/desktop/issues/2052#issuecomment-314716974 I don't think the solution to #2052 is to change the style of the `DialogError` component. The problem pointed out in that issue has to do with improper use of it.

 See https://github.com/desktop/desktop/blob/master/docs/technical/dialogs.md#errors

> The DialogError component, if used, must be the first child element of the Dialog itself.

`DialogError` is meant to be used when immediate validation (i.e. on text changed) is not realistic (due to performance), when the validation result can not be guaranteed (i.e. race conditions, file system is a good example) or when it's not suitable from a UX perspective. In other words. These errors should *normally* only appear after you've submitted the form in the dialog. 

In this specific instance of the directory creation failing what we need to do is move the `DialogError` component up to the top of the dialog (and probably tweak the message). We should not change the icon, these are definitely errors, not warnings.

I'm going to close this PR but If you'd like to start a PR to make the changes I outlined above we'd be happy to take a look!

**Comment by http-request** [comment]
:cry: why world is so cruel :cry:

**Pull request closed without merging**
