### PR TITLE
Rename branch.remote to branch.upstreamRemote

### PR DESCRIPTION
**Pull request by tidy-dev**
## Description

Rename `Branch` property `remote` to `upstreamRemote` as is a more accurate description.

### CODE REVIEW

**Review by niik — DISMISSED** [review]
:sparkles:

**Review by sergiou87 — COMMENTED** [review]
Looks good! But if we're later reintroducing `remote` as `remoteName`, shouldn't this one be `upstreamRemoteName`? 😳

**Comment by tidy-dev** [comment]
> Looks good! But if we're later reintroducing `remote` as `remoteName`, shouldn't this one be `upstreamRemoteName`? 😳

Makes sense

**Review by sergiou87 — APPROVED** [review]
Thanks for the change! LGTM now 😄

**Review by niik — APPROVED** [review]

**Pull request merged**
