### PR TITLE
Added support with the PhpStorm editor and updated for WebStorm

### LINKED ISSUE #7195: Add support for detecting Jetbrains tools in Desktop (Phpstorm, webstorm, etc) with Jetbrains Toolbox
Add the option to choose a program installed on my computer other than the ones it automatically detects.
image

### PR DESCRIPTION
**Pull request by dacoto97**
Closes #7195

## Description

- Added support for PhpStorm 2019.2, 2019.2.4 and 2020.1
- Added support for WebStorm 2019.2, 2019.2.4 and 2020.1

### CODE REVIEW

**Comment by dacoto97** [comment]
Hi @billygriffin.
This pull request is ready to merge.

**Comment by AKFU** [comment]
Pass

**Comment by dacoto97** [comment]
Hi @billygriffin, @desktop & @desktop.
This pull request is ready to review and merge.

**Comment by advaith1** [comment]
This isn't working for me: I have WebStorm 2020.1 Beta installed via JetBrains Toolbox and it doesn't show up in the list, also I checked and there are no WebStorm folders in the Uninstall folder in the registry.

To test, I also installed WebStorm 2019.2.4 via Toolbox, and there was no change: still no WebStorm registry folder in Uninstall, and still no WebStorm version is showing in the list in GitHub Desktop.

Toolbox App 1.16.6319, OS kernel winnt 10.0.19587 on x86_64

**Pull request merged**
