### PR TITLE
SVGs now have a visual diffs

### PR DESCRIPTION
**Pull request by mathieudutour**
context: https://github.com/desktop/desktop/pull/2383#issuecomment-328639486 (sorry for the delay)

- Add a new tab to the existing image diffs mode for file that supports it (only svg for now).
- In case it's an added or deleted file, it only shows 2 tabs: "Visual" and "Text"

### CODE REVIEW

**Comment by timofonic** [comment]
@mathieudutour @shiftkey Please yes!!! Will this get merged someday? Please consider it.

PS:  It would be amazing if done for other visual-like files, like KiCad ones <3

**Comment by shiftkey** [comment]
Just a heads up for anyone following this along - this has fallen down my priority queue due to the refactoring of the Diff internals. I also need to throw some screenshots in here to give an idea of what's changed UX-wise /cc @desktop/design

**Comment by pandeer2** [comment]
How to fetch a code?

**Comment by shiftkey** [comment]
I'm still hesitant to take this in as-is, due the changes to diff internals. My current plan is to break this up into two PRs:

 - first, refactoring the diff internals to support visual diffs of text content like SVGs
 - second, add the support for detecting SVGs and rendering them as visual diffs in the app

Once I open the first PR and a reviewer is happy with the changes proposed, I'll close this original PR and port the remaining work to a fresh PR.

I've timeboxed opening the first PR to this week to prevent dragging this out further.

**Comment by shiftkey** [comment]
Closing this out in favour of #4348 and a follow-up PR to add support for SVG visual previews.

**Pull request closed without merging**
