### PR TITLE
Added support for PyCharm as external editor on macOS

### PR DESCRIPTION
**Pull request by jakubroztocil**
## Description

Added support for PyCharm as external editor on macOS (analogous to how other JetBrains IDEs are integrated).

## Release notes

* Added support for PyCharm as external editor on macOS.

### CODE REVIEW

**Comment by Rexogamer** [comment]
I think you forgot a few bits (for example the app identifier) which are important to making this work. Check out the editor integration docs (docs/technical/editor-integration.md).

**Comment by jakubroztocil** [comment]
@Rexogamer thanks, I forgot to commit the rest but it should be fixed now

**Comment by Rexogamer** [comment]
Looking good now 👍

**Comment by say25** [comment]
@jakubroztocil There is a small merge conflict to resolve

**Comment by jakubroztocil** [comment]
@say25 fixed 👍

**Pull request merged**
