### PR TITLE
Added error message when `github open [url]`

### PR DESCRIPTION
**Pull request by msztech**
## Overview

CLI now shows an error message if `github open <arg>` is called on a remote URL rather than a local path. Addressing issue #4658 

## Description

Added a conditional statement in CLI call when running `github open path` to check if it's a remote URL. If it is, display a message. Otherwise, open the path in Desktop.

## Release notes

- Fixes issue with remote url being opened as relative path in desktop CLI.

### CODE REVIEW

**Comment by tierninho** [comment]
@msztech Thanks for the work on this issue. I cannot see the new error messaging though.

Can you confirm the text that needs to go in the field? Is it `https://github.com/USERNAME/REPOSITORY.git` or `git@github.com:USERNAME/REPOSITORY.git`?

**Comment by msztech** [comment]
@tierninho I have only added the error message for the command line. Can you try out the ‘open’ command in CLI on an URL and see if there is an error message? If so, I’ll continue to add the GUI error message tonight. If not, I’ll try to examine the issue.

**Comment by tierninho** [comment]
Awesome, thanks for the clarification @msztech Error message is now showing. ❇️

**Comment by msztech** [comment]
@tierninho Great! I’ll work on the GUI part now and push to this PR.

**Comment by msztech** [comment]
Hi @tierninho, I have two questions 😃:
1. Should I add the same error message for the graphical interface when a remote path is typed in the text box?
2. Should the error message prompt the new command `git clone`, or `github clone` (which opens up the desktop app for clone instead of cloning to the current working directory)?

**Comment by tierninho** [comment]
Thanks for checking in. I am inclined to say yes, but I am going to cc'd some other folks who will be better able to answer these questions. 

cc @shiftkey @billygriffin

**Comment by shiftkey** [comment]
@tierninho @msztech the CLI is a bit annoying to test locally, because it needs to invoke part of the bundled app. On macOS at least if you've installed the CLI shortcut to `/usr/local/bin/github` you can tweak the CLI behaviour with a couple of steps:

1. Build the app in dev mode with what you'd like to change, in my case this was to `~/src/desktop/dist/GitHub Desktop-dev-darwin-x64/GitHub Desktop-dev.app`

2. Find where this `/usr/local/bin/github` is symlinked to:

```
$ ls -l /usr/local/bin/github
lrwxr-xr-x  1 shiftkey  admin  77  8 May 08:36 /usr/local/bin/github -> /Applications/GitHub Desktop Test.app/Contents/Resources/app/static/github.sh
```

3. Edit the `/usr/local/bin/github` script to point to your dev mode app:

```shell
#!/bin/sh

# The least terrible way to resolve a symlink to its real path.
function realpath() {
  /usr/bin/python -c "import os,sys; print(os.path.realpath(sys.argv[1]))" "$0";
}

# comment out this variable
#CONTENTS="$(dirname "$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")")"
# hard-code this path to your new app to test
CONTENTS="/Users/shiftkey/src/desktop/dist/GitHub Desktop-dev-darwin-x64/GitHub Desktop-dev.app/Contents/"
BINARY_NAME="$(ls "$CONTENTS/MacOS/")"
ELECTRON="$CONTENTS/MacOS/$BINARY_NAME"
CLI="$CONTENTS/Resources/app/cli.js"

ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"

exit $?
```

4. Now run `github` to test with the new CLI behaviour. 

With these steps, I was able to see the new message:

**Pull request merged**
