### PR TITLE
Move dialog error out of dialog content

### PR DESCRIPTION
**Pull request by http-request**
Issue: <https://github.com/desktop/desktop/issues/2052>

Please read this comment before review:
https://github.com/desktop/desktop/pull/3532#issuecomment-350283733

**Before:** 
screen shot 2017-12-07 at 15 27 03

**After:**
screen shot 2017-12-11 at 18 46 28

### CODE REVIEW

**Comment by http-request** [comment]
run test

**Comment by j-f1** [comment]
Can you try merging in the latest `master`? PR https://github.com/desktop/desktop/pull/3556 fixed the issue with Circle.

**Comment by http-request** [comment]
I have created this branch from last master, it's already up-to-date.

**Comment by iAmWillShepherd** [comment]
Looks awesome!!! 

cc'ing @desktop/design

**Comment by joshaber** [comment]
I think this is safe since it's what @niik already outlined in https://github.com/desktop/desktop/issues/2052#issuecomment-314716974.

**Comment by joshaber** [comment]
Thanks @http-request! ✨

**Pull request merged**
