### PR TITLE
set environment variables for email and name instead of modifying configs

### PR DESCRIPTION
**Pull request by shiftkey**
This is to ensure AppVeyor is working as expected, without doing any test-specific workarounds.

This also dumps out the `git config` settings before running tests, to help track down any unexpected surprises...

### CODE REVIEW

**Comment by niik** [comment]
> This is to ensure AppVeyor is working as expected, without doing any test-specific workarounds.

I don't understand what this means, is AppVeyor not working as expected now?

Am I'm reading this correctly in that it'll actually try to update the global config when running tests locally if user.name/email isn't set? In that case I'm not wild about it.

If the intention is to ensure that all our git commands in tests have access to a valid tuple of user/email could we scope it such that it's only valid in the test context itself? Either by setting the `GIT_AUTHOR_*` environment variables or, if the problem is that git can't auto-resolve on AppVeyor, just the `EMAIL` env var.

**Comment by shiftkey** [comment]
> I don't understand what this means, is AppVeyor not working as expected now?

Neither AppVeyor nor Travis set these values, however bumping Git to 2.13 meant any call to `commit` would hard-fail on AppVeyor. I haven't dug into why Travis isn't failing in the same way.

> If the intention is to ensure that all our git commands in tests have access to a valid tuple of user/email could we scope it such that it's only valid in the test context itself?

I'll see if the use of environment variables will flow through `electron-mocha` - this isn't something I've tested yet, but it should work...

**Comment by shiftkey** [comment]
> Either by setting the `GIT_AUTHOR_*` environment variables or, if the problem is that git can't auto-resolve on AppVeyor, just the `EMAIL` env var.

`GIT_AUTHOR_*` didn't seem to be detected, but `EMAIL` seems to work just fine here.

**Comment by niik** [comment]
> GIT_AUTHOR_* didn't seem to be detected, but EMAIL seems to work just fine here.

Ah, that's my bad, it should probably be `GIT_COMMITTER_*` for the purposes of this PR.

> I'll see if the use of environment variables will flow through electron-mocha - this isn't something I've tested yet, but it should work...

We could also just modify process.env inside the test context itself if we don't want to taint that package.json any more

**Comment by shiftkey** [comment]
> Ah, that's my bad, it should probably be `GIT_COMMITTER_*` for the purposes of this PR.

All good, I need more ☕️  anyway. I'd rather us use `GIT_COMMITER_*` as this also sets the name.

**Comment by shiftkey** [comment]
Looks like `git commit` doesn't use these `GIT_COMMITTER_*` and `GIT_AUTHOR_*` environment variables - the docs mention `git-commit-tree` looking for these values, which I guess is a different code path to what `git commit` is using.

So I guess we're stuck with `EMAIL` for this case:

> `EMAIL` is the fallback email address in case the `user.email` configuration value isn’t set. If this isn’t set, Git falls back to the system user and host names.

```
$ git --version
git version 2.13.0.windows.1

$ GIT_COMMITTER_NAME="Joe Bloggs" GIT_COMMITTER_EMAIL="foo@bar.com" GIT_TRACE=1 git commit -m "ha ha business"
09:30:45.128788 git.c:369               trace: built-in: git 'commit' '-m' 'ha ha business'

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'shiftkey@BRENDANFORSE14E.(none)')

$ EMAIL="foo@bar.com" git commit -m "ha ha business"
[master 95bb946] ha ha business
 1 file changed, 1 insertion(+), 1 deletion(-)


$ git show HEAD
commit 95bb9461cbd1d8d0a436ca40d9eb0314d216b820 (HEAD -> master)
Author: unknown <foo@bar.com>
Date:   Wed Jun 7 09:33:14 2017 -0300

 ...
```

**Comment by shiftkey** [comment]
💊

**Comment by niik** [comment]
> Looks like git commit doesn't use these GIT_COMMITTER_* and GIT_AUTHOR_* environment variables - the docs mention git-commit-tree looking for these values, which I guess is a different code path to what git commit is using.

That sounds weird, it seems to be working pretty well on my machine

image

```
$ git --version
git version 2.13.0.windows.1
```

**Comment by shiftkey** [comment]
@niik weird. This isn't critical and I'd like to use `GIT_COMMITTER_*` so I'll keep digging.

**Comment by shiftkey** [comment]
Alright, I finally figured out what the root cause here is - you need to define both sets of `GIT_COMMITTER_*` and `GIT_AUTHOR_*` values when you don't have `user.email` or `user.name` configured.



Define only `GIT_AUTHOR_*` (which Git displays by default) and Git still goes off to try and resolve the committer fields and fails:

**Pull request merged**
