### PR TITLE
first pass at packaging for Linux distros

### PR DESCRIPTION
**Pull request by shiftkey**
Replaces #2300 

This is the first pass at adding support for generating RPM, DEB and AppImage builds of Desktop. 

**This doesn't include official support, just the groundwork.**

This uses the same `npm run package` commands that we can use on macOS and Windows.

If someone wants to contribute additional formats, please follow the conventions in `script/package`.

 - [x] fix appveyor issue with linux-only package
 - [x] cleanup `after_success` hooks as we shouldn't package for every build

### CODE REVIEW

**Review by joshaber — APPROVED** [review]
Wow, well alright then ✨

**Comment by probonopd** [comment]
@shiftkey @joshaber now that this has been merged, is there anything preventing this project from providing pre-compiled RPM, DEB and AppImage builds of Desktop on GitHub Releases?

**Comment by shiftkey** [comment]
@probonopd we don't use GitHub Releases for shipping updates, so we'd have to teach our infrastructure how to manage these.

I have some ideas about moving this forward, but I need to chat with @desktop/core first.

**Comment by wyqydsyq** [comment]
@shiftkey If you guys are intending to ship native packages (`.rpm`s and `.deb`s) as opposed to something like a Flatpak or AppImage, I'd strongly recommend using OBS for building and shipping:
https://build.opensuse.org/

Supports building for all major desktop distros (Ubuntu, Debian, Fedora, OpenSUSE), a lot of Linux users are already familiar with installing software from there.

**Pull request merged**
