### PR TITLE
Track metrics for reordering commits

### PR DESCRIPTION
**Pull request by sergiou87**
## Description

This PR starts tracking for metrics around reordering commits, inspired on our cherry-picking metrics. More specifically:
- When the user starts reordering commits.
- When the user starts reordering **multiple** commits.
- Number of times reordering is completed successfully.
- Number of times reordering is completed successfully after encountering conflicts.
- Number of times reordering causes conflicts.
- Number of reorderings undone.

## Release notes

Notes: no-notes

### CODE REVIEW

**Review by tidy-dev — DISMISSED** [review]
✨  Looks good to me! 

I may move the `this.statsStore.recordReorderUndone()` when I build the squashing metrics on top of this into a `this.statsStore.recordOperationUndone()` to house a switch statement that one day will also include cherry-picking... and if there are any others I can do that way to reduce some of the stat tracking noise in the operation logic.

**Comment by sergiou87** [comment]
That sounds great, thanks!! ❤️

**Review by billygriffin — DISMISSED** [review]
LGTM!

**Review by tidy-dev — APPROVED** [review]
✨

**Pull request merged**
