### PR TITLE
Fix diff range-based selection dragging the mouse

### LINKED ISSUE #17673: The window in GitHub Desktop doesn't scroll automatically anymore when I want to select a large block of lines
### The problem

I used to be able to hold the mouse/trackpad pointer on a line, like line 2000, for example and then scroll the window all the way up to line 1 to select or deselect a large number of changes. Now the screen doesn't scroll anymore! This will severely impede my work. I need to be able to select large swaths of text, and GitHub desktop allowed me to do that while seeing if there were any changes between the blocks I wanted to deselect. Was this behavior removed intentionally? Can it be restored? Thanks!

### Release version

Version 3.3.5 

### Operating system

MacOS Monterey 12.6.7

### Steps to reproduce the behavior

1. Make changes to a file with thousands of lines of code.
2. Go to line 2500 (or something), click and hold on that line to deselect the change.
3. Move the mouse up past the top of the screen, keeping the button held.

Expected behavior: screen scrolls up to the top really fast allowing you to deselect all the text above where you started in a matter of seconds

Observed behavior: screen doesn't scroll at all

### Log files

_No response_

### Screenshots

https://github.com/desktop/desktop/assets/16783389/d322047f-9dcf-49aa-b9c5-1debca88cd0f

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sergiou87**
Closes #17673

## Description

This PR addresses two issues related to the new diff engine:
1. It didn't update the UI properly when (de)selecting multiple lines by dragging the mouse around. The selection would be tracked internally, but the UI wouldn't show changes until the user releases the mouse button.
2. It wouldn't scroll the diff when the user is dragging the mouse out of the bounds of the diff itself, making it harder to (de)select a big number of lines.

### Screenshots

https://github.com/desktop/desktop/assets/1083228/c26f75c2-3f52-4f3b-afe6-9e1fb969b0a0

## Release notes

Notes: [Fixed] Selecting or deselecting lines in a diff by dragging the mouse now scrolls the contents as needed

### CODE REVIEW

**Review by niik — DISMISSED** [review]
I'm seeing some weirdness when testing this out, it seems it won't deselect until it gets into the removed lines?

**Comment by sergiou87** [comment]
What the… 🤯  Let me look into that

**Comment by sergiou87** [comment]
The problem was the need to specify the column in the "temporary selection" piece of the state, which led to weird behaviors like that one even in current prod in side-by-side view:

https://github.com/desktop/desktop/assets/1083228/aae82fc4-c349-4523-bff7-0317249ef166

Instead, I decided to follow the approach used in the previous diff engine: base that "temporary selection" on the line number in the original diff.

**Comment by percyhanna** [comment]
I came here to report this bug, but found this PR. Does this fix work? Would love to see this fixed as I use the range-based diff selection frequently.

**Review by tidy-dev — APPROVED** [review]
✨  Thanks for those changes. Works a lot smoother and last line selection works as expected.

**Pull request merged**
