### PR TITLE
Keeping organization when switching tabs on publish repository modal

### PR DESCRIPTION
**Pull request by brendonbarreto**
This is my first PR to the project.

closes https://github.com/desktop/desktop/issues/6546

### CODE REVIEW

**Comment by tierninho** [comment]
Tested and LGTM however I could not test the Enterprise organization retention in the dev environment.

**Comment by billygriffin** [comment]
Hi @brendonbarreto, thanks so much for submitting your first pull request in Desktop! 🎉 Our team is really focused on our 1.6 release scheduled to go out Thursday, so I don't anticipate a thorough review until after that. Welcome to the community and looking forward to hopefully getting this into the product. ❤️

**Comment by brendonbarreto** [comment]
Thanks for the welcome @billygriffin , and for the quick feedback!

**Comment by brendonbarreto** [comment]
@iAmWillShepherd I made the changes you requested. Now each tab has its own state. Sorry for any mistake, I'm new to typescript world (but I already find it beautiful)

**Comment by iAmWillShepherd** [comment]
@brendonbarreto Have a look at https://github.com/desktop/desktop/pull/6776. I added a bit of type safety to what is being done in this PR. If it looks good to you, I can either push to your branch or we can go with the new PR (you'd still get credit of course 👍 ).

**Comment by brendonbarreto** [comment]
@iAmWillShepherd I think we can go with the new PR (#6776)

**Comment by iAmWillShepherd** [comment]
Closing due to https://github.com/desktop/desktop/pull/6636#issuecomment-460992713

**Comment by pajenterprisesllc** [comment]
committee

**Pull request closed without merging**
