### PR TITLE
1.4.0-beta3 release notes draft

### PR DESCRIPTION
**Pull request by outofambit**
- [x] finalize release notes
- [x] release to beta channel

### CODE REVIEW

**Comment by outofambit** [comment]
@shiftkey good to know!

**Comment by outofambit** [comment]
i think i'm gonna replace these with the same release notes as the prior betas for clarity

**Comment by say25** [comment]
Not sure if this is a bug or not, but in all the 1.4.0 betas I havent been seeing release notes after clicking either of the `Quit and Restart` buttons

**Comment by shiftkey** [comment]
@say25 we've only changed the behaviour of this link - previously it just took you to the release notes URL on `desktop.github.com`, but now it will show the dialog in #3601:



I know there are other ideas floating around (for example, I hope @nerdneha opens an issue to track [this comment](https://github.com/desktop/desktop/pull/3601#issuecomment-418841199), so if you've got suggestions about how we can refine this then let us know!

**Pull request merged**
