### PR TITLE
Only fetch the default remote

### PR DESCRIPTION
**Pull request by joshaber**
[Some chat context](https://github.slack.com/archives/C17LP0XU3/p1494522423885147)

The current behavior of fetching all remotes is confusing given that our UI talks about, e.g., "Fetch origin" but really it fetches more than `origin`.

Our multi-remote support is weak. We should whole-ass it when we get the chance instead of half-assing it now.

tenor

### CODE REVIEW

**Comment by alrz** [comment]
How is this post-beta? "**auto** fetch **all**" behavior is just inconvenient.

**Comment by joshaber** [comment]
@alrz Ah sorry, we were a bit unclear. By post-beta we meant after the initial beta launch. We'll land this soon, once we think the app has stabilized.

**Comment by niik** [comment]
@joshaber How much longer do you think we should hold off mergin this?

**Comment by joshaber** [comment]
I'd like to feel that the app is stabilized before we land these. I _think_ we're close, but given that we've done a release every day so far this week, I don't think we're there yet.

**Comment by joshaber** [comment]
I'm ok with reviewing and landing this now 🙏

**Pull request merged**
