### PR TITLE
correct diff rendering for docx file

### LINKED ISSUE #1990: Binary diff doesn't show anything, not even a message indicating it's a binary file
### Description

In the native client binary files would show a messge indicating the diff is of a binary file, but in this client it shows nothing at all.

### Version
**GitHub Desktop version:** 0.6.0
**OS version:** Win10 CU (10.0.15063)

### Steps to Reproduce

1. Add a file such as a word doc (docx) to your repo
1. Modify it
1. Select the file in the changed file list
1. Look at the diff view for the file

**Expected behaviour:** A message should be shown indicating the file in question is a binary file so there's no diff to view.

**Actual behaviour:** Nothing shows in the diff view

**Reproduces how often:** With every binary file

#### Additional Information

Comparison view with the native client.

image

### PR DESCRIPTION
**Pull request by shiftkey**
Fixes #1990 

It looks like Git is clever enough to diff a DOCX file without any using `.gitattributes` to bundle an external diff driver [like this old advice](http://blog.martinfenner.org/2014/08/25/using-microsoft-word-with-git/):

```
$ git diff HEAD --no-ext-diff --patch-with-raw --no-color -- word-doc.docx
:100644 100644 f7f02d0... 0000000... M  word-doc.docx

diff --git a/word-doc.docx b/word-doc.docx
index f7f02d0..4f71cf5 100644
--- a/word-doc.docx
+++ b/word-doc.docx
@@ -1 +1,3 @@
+WRITE SOME WORDS

+AND THIS LINE
```

It's not clear to me why we're not also getting this diff output when we run the same command in Desktop, so let's get to the bottom of it.

 - [x] add failing test
 - [x] remove global `gitattributes` file from Windows packaging on `dugite-native` - [release](https://github.com/desktop/dugite-native/releases/tag/v2.13.0-rc3)
 - [x] confirm test is fixed with update for `dugite`

### CODE REVIEW

**Comment by shiftkey** [comment]
So the Git we bundle in Desktop (MinGit) is a cut-down version of the main Git for Windows, and it looks like we're missing this tool:

```
Failed to locate unzip command '/usr/bin/unzip'
```

This will require a patch to `dugite-native` and the `dugite` to add in the missing tool.

**Comment by xt0rted** [comment]
@shiftkey since we're able to get a diff with the desktop client, is it possible to also get this on the website? Right now it just shows `Binary file not shown.` for each modified `.docx` in the commit.

**Comment by shiftkey** [comment]
@x0rted server-side diff rendering is a whole other scenario. I need to go spelunking into Git's general behaviour here, as the use of an external tool for this file extension is intriguing (and might not be supported everywhere).

**Comment by shiftkey** [comment]
@xt0rted so this is related to the default behaviour of `gitattributes` in Git for Windows:

 - [the global gitattributes defines handlers for docx files and others](https://github.com/git-for-windows/build-extra/blob/master/git-extra/gitattributes) 
 - [the `astextplain` script launches a perl script](https://github.com/git-for-windows/build-extra/blob/master/git-extra/astextplain#L15) (I thought running Perl scripts wasn't supported in MinGit 🤔 )
 - and here's the [`docx2txt.pl`](http://docx2txt.cvs.sourceforge.net/viewvc/docx2txt/docx2txt/docx2txt.pl?view=markup) script
 - if we could get this to work on Windows, this introduces other issues like ensuring users don't accidentally try to partially commit changes to these types of files

As the Git embedded in `dugite-native` doesn't have the same behaviour for macOS and Linux, let alone the discussion about server-side rendering, I'm going to drop these `gitattributes` from a `dugite-native` update so that we're showing the "binary files differ" message on all platforms to close this bug out.

If you'd like to see us refine our diff rendering defaults, please open a new issue over on https://github.com/desktop/dugite-native and we can dig into the technical details there.

**Pull request merged**
