### PR TITLE
Introduce PR integration on the beta channel

### PR DESCRIPTION
**Pull request by joshaber**
`enablePreviewFeatures` is great because it's allowed us to develop and merge PR integration in small pieces. But the feature is at the point now where I'd like to live with it and let others live with it, in order to shake out the bugs and find usability problems.

So to that end, I've introduced `enableBetaFeatures` which, as you might guess, enables features for the beta channel.

This is a decent sized change in that it introduces a new variant of feature-flagging and also beta ships PR integration. So this can wait until next week when more people are around.

### CODE REVIEW

**Comment by niik** [comment]
I'm thrilled that we'll be able to target beta users now but I have one small concern with this. Under the previous regime it was all or nothing which made it very easy to reason about implicit dependencies of components. With this I can see a hypothetical scenario where we forget to convert one `enablePreviewFeatures` check into a `enableBetaFeatures` for some feature which leaves the feature only partially working. Imagine forgetting to enable the retrieval of data from the API but enabling the UI components that requires that data. Something we wouldn't notice until after we've shipped to beta.

I wonder if it would make more sense here to keep the `enableBetaFeatures` method but not export it and instead add a `enablePRIntegration` (or something more cleverly named). Moving us more towards feature flags in their true sense. The `enablePRIntegration` method would just return the result of `enableBetaFeatures` but conceivably we could leverage this in the future to gradually turn on features using more advanced logic.

That way we'd have a clear inventory of what features still aren't shipped and we'd be able to transition them from dev to beta by just changing the one spot. Additionally it'll be much easier to find and remove all checks for a particular feature when we're ready to ship it for realz.

**Comment by joshaber** [comment]
I like all that reasoning 👍 💯

I'll wait until more folks chime in before I make that change.

**Comment by j-f1** [comment]
If we add switches for each feature, it would be possible to make a `chrome://flags`-style UI for folks to enable and disable different beta features.

**Comment by shiftkey** [comment]
> That way we'd have a clear inventory of what features still aren't shipped and we'd be able to transition them from dev to beta by just changing the one spot.

**Comment by joshaber** [comment]
👍 

I gave the merge tool integration a similar treatment. This is ready now, I think 🙏

**Pull request merged**
