### PR TITLE
Bump Electron to v19

### PR DESCRIPTION
**Pull request by sergiou87**
## Description

This PR upgrades Electron to v19. Luckily, no API changes affected us 🎉  so it'll be easy to revert/cherry-pick later if needed.

I've tested it as much as I could, but it'd be nice if other people did the same before merging it or deploying to beta 😨  Thanks!

## Release notes

Notes: no-notes

### CODE REVIEW

**Comment by tsvetilian-ty** [comment]
@sergiou87 🎉 

I tested the PR against a list of issues marked as bugs. I will refer to them below so it's easier to close them after merging the PR.

1. https://github.com/desktop/desktop/issues/14009 - Fixed! For some reason, I can't capture it on screen recording 😞
2. https://github.com/desktop/desktop/issues/14263 - This issue is related to the first one on the list 🆙 ⬆️ 
3. https://github.com/desktop/desktop/issues/14037 - Fixed! (the gif is 15fps but the animations are visible)
### Before
before-fix
### After
after-fix

4. https://github.com/desktop/desktop/issues/13940 - Fixed! Environment: GitHub Desktop fullscreen, resolution 1920x1080 and scale 175%
> Couldn't test multi-monitor case, where the displays have different scales, and the GitHub Desktop window is dragged between them!
### Before
Screenshot 2022-06-16 143045

### After
image


#### Potentially fixed issues

Perhaps https://github.com/desktop/desktop/issues/13939 and https://github.com/desktop/desktop/issues/14017 are fixed as well. Someone with a multi-monitor setup can test them too.

**Comment by sergiou87** [comment]
Thanks so much for testing and for linking the issues @tsvetilian-ty!! ❤️

**Review by niik — COMMENTED** [review]
Could we update our version of Node to 16.14.2 as well to stay in sync with Electron? Will probably require requesting a new Windows arm build though

**Comment by sergiou87** [comment]
@niik I asked for a new build of node for Windows ARM in https://github.com/nodejs/build/issues/2540#issuecomment-1158942640 and it seems we're not gonna get one very easily this time 😢 

I'd say we don't upgrade node yet in order to merge this PR, and see if we could get a build for Windows ARM soon. Otherwise, we should probably stop supporting Windows for ARM entirely until the situation changes. As of today, support for it is not official and limited to betas. The only link to those builds is in our README file, and according to our metrics only 62 users have installed it so far in the last year (and I'm one of them 😂).

Thoughts?

**Comment by niik** [comment]
> I'd say we don't upgrade node yet in order to merge this PR

Yeah, I'm fine with that given that it's such a minor bump. It doesn't affect end users but it's nice to stay in sync when we can.

**Review by tidy-dev — APPROVED** [review]
✨

**Pull request merged**
