### PR TITLE
Fix NDDB consistency

### LINKED ISSUE #5293: The New Feature for Alerting User When Base Branch Moves Ahead of Current is Inconsistent
## Description
The new feature "Notification displayed in History tab when the base branch moves ahead of the current branch" seems inconsisent.  If I take a base branch, make a commit to it, flip to a new branch and move to the history tab, I would expect to see the alert jump out at me, but instead, I don't see anything.  I don't even see the blue dot on the history tab when in the changes tab.  I only trigger the alert the first time if I click the text box that lets us choose the branch to compare, then I immediately get the alert.  After the first time the alert is triggered, it then begins to work as expected.  If I flip back to a base branch that has the newer commit to it, then back to the non-base branch, the history tab has a blue indicator and clicking on the history tab immediately shows the alert.

## Version
* GitHub Desktop: v1.3.1
* Operating system: macOS 10.13.6

## Steps to Reproduce
1. Using a test repo with just a master branch, make a new branch
2. Add a commit to this new branch
3. Flip back to the master and add a commit to the master
4. Flip back to new branch and expect to see the alert showing that the new branch is behind master (but no alert shows)
5. Click text box to compare and compare with master, alert may show up now
6. Clear the text box for comparing a branch to another
7. Flip back to master, then back to new branch and see that alert pops up now as I would expect.

### Expected Behavior
I'd expect that the alert would show up in the same manner that it shows up during step 7: As soon as I flip to a branch that is behind a base branch, the blue dot should appear in the history tab and flipping to the history tab, the alert should show up without having to play around with the comparison text box.

### Actual Behavior
I get two different ways that the alert is triggered.  The first time it is triggered, which calls for clicking the comparison box and flipping back and forth on the changes and history tab, and every time after the first, which is it automatically coming up as I think it should.

Sorry if this is vague or unclear, it is hard to describe.  I will try to explain better if it is still not understood.

## Additional Information
branch bug

### PR DESCRIPTION
**Pull request by iAmWillShepherd**
Fixes #5293

### CODE REVIEW

**Comment by shiftkey** [comment]
@iAmWillShepherd a few initial questions:

 - this looks like some changes similar to #5259, but I don't think it's related - are we able to focus on just the changes to address #5293 here?
 - do we want to get #5259 into the next release?
 - any pointers for reviewing and verifying this PR?

**Comment by shiftkey** [comment]
Feel free to rebase this on top of `master` now that #5259 is merged if it'll help simplify the diff

**Comment by JosephTLyons** [comment]
Is it decided if this will be addressed in the next update cycle or a quick hotfix?

**Comment by shiftkey** [comment]
> Has it been decided if this will be addressed in the next update cycle or a quick hotfix?

@JosephTLyons I think we'd like this in sooner rather than later, but I'll let @iAmWillShepherd report back after he's done investigating what the fix looks like.

**Comment by iAmWillShepherd** [comment]
@JosephTLyons I'm targeting to have this in for the next release, 1.3.1, but if I can get a fix in before then, we may release it sooner.

**Comment by JosephTLyons** [comment]
V1.3.2?

**Comment by shiftkey** [comment]
@iAmWillShepherd how's this progressing?

**Comment by shiftkey** [comment]
@iAmWillShepherd any objections to closing this PR out for now? I'm happy to revisit the original issue about what we should be doing to address the issue.

**Comment by iAmWillShepherd** [comment]
@shiftkey sorry for letting this slip, I had touched it before going on vacation. And I'm cool with closing.

**Comment by billygriffin** [comment]
@iAmWillShepherd I'm unclear on what we're doing here. Did we make sufficient progress here to where we're close to resolving the bug in #5293, or is this really just a first stab and it requires quite a bit more to get it across the line?

**Pull request closed without merging**
