### PR TITLE
Update app icon

### LINKED ISSUE #7536: Desktop Dock icon doesn't match size of other circle icons
**Please describe the problem you think should be solved**
The GitHub desktop dock icon does not match Atom's or Safari's circle size. 
image

**[Optional] Do you have any potential solutions in mind?**
The white stroke seems to match ~1.5pt but the size of the circle itself is ~2pt too big in diameter.

### LINKED ISSUE #10855: Icon for macOS Big Sur
### Describe the feature or problem you’d like to solve
big sur has redesigned its icons and is beginning to change third-party applications to more friendly icons.
image

### Proposed solution
I think github desktop should also support the new icon design specifications
https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/

### Additional context
Reference: Icons for other well-known third-party applications updated for big sur
- [iterm](https://gitlab.com/gnachman/iterm2/-/issues/8969) 
- [reader5](https://apps.apple.com/jp/app/reeder-5/id1529448980?mt=12) 
- [bartender4](https://www.macbartender.com/Bartender4/)

### PR DESCRIPTION
**Pull request by ampinsk**
Updating our Mac app icon for Big Sur! Thanks for the help with this @tobiasahlin!

Closes #10855 
Closes #7536

Frame 2
1024x1024

### CODE REVIEW

**Review by cretuemanuel — DISMISSED** [review]

**Review by 6068 — APPROVED** [review]

**Comment by ampinsk** [comment]
I cleared my cache and tested this on Big Sur and Catalina and it _should_ work. Would love for others to test!

**Comment by say25** [comment]
@ampinsk I believe this work would also close https://github.com/desktop/desktop/issues/7536

**Comment by ampinsk** [comment]
I tested this again with slightly tweaked colors and shadows and think this is ready to go, review pending!

**Review by niik — APPROVED** [review]
Did a test release and everything is looking great afaict. Let's get this onto the next beta!

**Comment by jstevens79** [comment]
I've updated, tried clearing caches and everything I can think of, but still get the old, round icon. Any ideas on how to get the new one to show up?

**Pull request merged**
