### PR TITLE
Highlighter: Add .hpp support for C++

### LINKED ISSUE #3413: No syntax highlighting for "*.hpp" files.
### Description

C++ source code in "*.hpp" files has no syntax highlighting.

### Version

**GitHub Desktop version:** v1.0.9

**OS version:** Microsoft Windows [Version 10.0.10586]

### Steps to Reproduce

1. Create/clone any Git repository.
2. Create a file with `.hpp` extension: `test.hpp` for example.
3. Add any C++ code into that file.
4. Commit your changes.
5. Open History tab in GitHub Desktop and select that commit.

**Expected behavior:** C++ syntax must be highlighted.

**Actual behavior:** No C++ syntax highlighting.

**Reproduces how often:** Always.

### PR DESCRIPTION
**Pull request by say25**
Closes #3413

### CODE REVIEW

**Comment by niik** [comment]
Hey @say25. Could you please submit a PR to https://github.com/desktop/highlighter-tests adding a sample `.hpp` file so that we can tests this out and help us avoid breakage in the future?

**Comment by say25** [comment]
@niik that feels like it doesn't follow convention. 
For examples: 
1. `.c` and `.h` support for C 
2. `.sc` and `.scala` for Scala

This goes back to my comment about listing supported file types in https://github.com/desktop/desktop/pull/3401

> Sounds good @niik any advantage to showing file extensions supported per language?

**Comment by say25** [comment]
I'm more than happy to add it now. I'm just explaining why I didn't in the first place

**Comment by shiftkey** [comment]
@say25 it's all good - we're still kind of figuring out the easiest way to manage these, without adding too much friction for everyone. For these newer files I guess we're mostly worried about catching regressions - and having that testbed of files helps us be proactive about these.

**Comment by say25** [comment]
@shiftkey Do we want to add `.h` for C and `.sc` for Scala ect. to the highlighter tests repo?

**Comment by shiftkey** [comment]
@say25 nah, just worry about the new file extensions we're adding support for

**Comment by shiftkey** [comment]
Dropping the `ready-for-review` label until the corresponding `highlighter-tests` PR is ready to merge.

**Comment by say25** [comment]
Just before I finished https://github.com/desktop/highlighter-tests/pull/7

**Pull request merged**
