### PR TITLE
Added Accelerator and Access key for Exit

### LINKED ISSUE #6507: Add a File menu keyboard shortcut for program Exit
I'm a keyboard-shortcuts kind-of-guy so a **File Menu** shortcut to **Exit** would be lovely (-:

At the moment, for me, it's an `<Alt>-F ; <Up-Arrow> ; <Enter>` affair.

Thanks
[GitHub Desktop 1.5.1 on Windows 10 (Intel x86_64)]

### PR DESCRIPTION
**Pull request by AndreiMaga**
Added Alt+F4 as a shortcut for quit in the default menu and added access key Alt+F+X for it

## Overview

**Closes #6507**

## Release notes

Notes: [Improved] Keyboard shortcut now shown next to Exit menu item on Windows

### CODE REVIEW

**Comment by AndreiMaga** [comment]
I think and hope this is ready for review 😄

**Comment by AndreiMaga** [comment]
Got it, will work on it right now, hope I have something by the end of the day ^^

**Comment by AndreiMaga** [comment]
I hope this fixes it.

**Comment by niik** [comment]
Thank you so much @AndreiMaga! We've already begun preparations for the next production release so expect to see this in the release after the next one.

**Pull request merged**
