### PR TITLE
Add instructions for enabling preview features

### PR DESCRIPTION
**Pull request by j-f1**
- [x] macOS
- [ ] Windows
- [ ] Linux

### CODE REVIEW

**Comment by j-f1** [comment]
I only have a macOS box, so I’d appreciate some 💭 on the other two platforms.

**Comment by joshaber** [comment]
I'm nervous about documenting something permanent like `launchctl`. I could see unsuspecting users enabling it and then forgetting about it and not knowing how to disable it.

**Comment by j-f1** [comment]
Should I close this PR, then add a check for a key in `localStorage` that can be more easily set on any platform?

**Comment by joshaber** [comment]
>Should I close this PR, then add a check for a key in localStorage that can be more easily set on any platform?

I like that idea 👍

**Comment by shiftkey** [comment]
> I only have a macOS box, so I’d appreciate some 💭 on the other two platforms.

Windows 7 and up have `SETX` on the command line, which works pretty much how you'd expect:

```shellsession
$ SETX GITHUB_DESKTOP_PREVIEW_FEATURES 1
```

The only caveat here is that it won't be applied for the current shell session.

**Comment by j-f1** [comment]
I’m closing this in favor of a `localStorage` key as discussed above.

**Pull request closed without merging**
