### PR TITLE
Dynamically set max width of resizable component

### PR DESCRIPTION
**Pull request by marzepani**
Related to #2745 (and #1588)

## Description

The max-width limit of the sidebar and file list is too small on wide screens. This PR dynamically sets the max-width of every resizable component to one-third of the main window. It does not listen to the window resize event, but it recalculates on every drag start to keep it simple.

## Release notes

Notes:
I don't think the width of the sidebar and file list should be automatically resized when the main window is resized. Auto-resizing can be quite annoying. Al least to me, it is.

### CODE REVIEW

**Review by Luckylukee — APPROVED** [review]
#10706

**Review by ibtisam167 — APPROVED** [review]

**Review by paul-szczepanek-arm — APPROVED** [review]
Why is this PR stuck? Looks great!

**Comment by Shahryarmohammadie** [comment]
good

**Comment by marzepani** [comment]
It has been one year now that I opened this PR. Is anyone interested in reviewing, accepting, rejecting, or commenting?

**Comment by sergiou87** [comment]
Sorry about the radio silence @marzepani 😓 

We discussed about this PR a few weeks ago, and we liked the idea but were afraid it could break anything without us noticing, so we wanted to test it thoroughly but so far we haven't found the time yet 😭

**Comment by danny007in** [comment]
better use percentage for width.

**Comment by adamgit** [comment]
This appears to be a trivial change that takes an *already broken* part of the UI and makes it less broken. How is there a risk here that 'something else' might get broken? It's barely changing 8 lines of code.

Would it help if I submitted a PR that simply removes the offending code, the max-size limit that should never have been there in the first place, as per glennreid's comment - now 3 years old - https://github.com/desktop/desktop/issues/2745#issuecomment-957914585 ?

**Comment by niik** [comment]
Thanks so much for wanting to contribute here @marzepani, we really appreciate it! I'm going to close this in favor of #13439 which hopefully will let us relax the constraints of the resizable components without running into the risks that @sergiou87 alluded to.

**Pull request closed without merging**
