### PR TITLE
Don't persist branch and PR filters

### LINKED ISSUE #7437: Branch filter persistence causes confusion when trying to switch branches
**Please describe the problem you think should be solved**

In a usability test yesterday for stashing, someone really struggled with the branch filter persisting information from a previous filter because they couldn't figure out why `master` wasn't showing in the list of branches. We did that for consistency, but I think it may cause more issues than it helps, and I'd love to revisit that decision.

1. Create a new branch via the branch filter box

Screen Shot 2019-04-30 at 12 07 27 PM

2. After branch is created, click branch dropdown to try to switch back to `master`
3. Be confused because `master` (or any other branch you'd want to switch to) is nowhere to be found.

Screen Shot 2019-04-30 at 12 09 13 PM

**Do you have any potential solutions in mind?**

After you've switched to a new branch, it seems like clearing the filter text would be a reasonable approach. I know we've heard that for the repo filter, not clearing it can be helpful because you can filter by similar types of repos (and soon by org!), but I'm skeptical that the value that provides on branches outweighs mitigating the confusion that arises by not understanding why you're only seeing the filtered branches when trying to switch to a different branch.

This was originally raised in #6002 and the PR was #6088

cc: @tierninho @Daniel-McCarthy

### PR DESCRIPTION
**Pull request by billygriffin**
Closes #7437 

In #6002 (issue) and #6088 (PR) we persisted the branch and PR filters when users open and close the branch and PR dropdowns. We've seen feedback from users and experienced the confusion ourselves, and this reverts that change. I'm particularly appreciative to @Daniel-McCarthy for their efforts in doing this work in the first place, and I apologize that I didn't foresee the potential unintended consequences from a product perspective.

Filtering branches:
Screen Shot 2019-05-08 at 1 25 13 PM

After closing and reopening:
Screen Shot 2019-05-08 at 1 25 24 PM

## Release notes

Notes:

`Don't persist branch and pull request filters after switching branches`

### CODE REVIEW

**Comment by billygriffin** [comment]
Thanks @tierninho! As discussed briefly in Slack, if they're still in the context of searching by branch or by PR and have the dropdown expanded, I think it's ok to retain that persistence. It's once they leave that context that we should clear it out so the next time they're able to see all of them.

**Comment by Daniel-McCarthy** [comment]
@kkayri [This comment](https://github.com/desktop/desktop/issues/7437#issue-438910164) explains in more depth why these changes are being made.

**Comment by Rodion8888** [comment]
If you encounter bugs in any of our clients, please open a terminal and type keybase log send

**Comment by Rodion8888** [comment]
If you encounter bugs in any of our clients, please open a terminal and type keybase log send

**Comment by Rodion8888** [comment]
/keybase/public/your_username.

**Comment by Rodion8888** [comment]
/keybase/public/your_username.

**Comment by Rodion8888** [comment]
https://keybase.io/docs/server_security/code_signing_key.asc

**Pull request merged**
