### PR TITLE
Check if notification matches current repository

### PR DESCRIPTION
**Pull request by sergiou87**
## Description

While investigating #15422, I noticed the app isn't using the repo owner/name to decide whether or not it should show the notification 🤦‍♂️  That check probably got lost due to a previous refactor. This PR brings that check back, and takes fork behavior into account.

## Release notes

Notes: [Fixed] Notifications are shown only when they are relevant to the current repository

### CODE REVIEW

**Comment by tidy-dev** [comment]
I thought that if I opened a PR in desktop/desktop and then was working in desktop/dugite. I should get a notification about desktop/desktop PR failing so I could switch to it. Is that not so?

**Comment by sergiou87** [comment]
@tidy-dev the idea was not bothering users with notifications from repositories other than the currently selected one. The notification dialog, however, has a "Switch to repository" button because you might receive the notification, and then switch to another repo before you interact with the notification. In that case, the notification will suggest you to switch to the repo it belongs to.

Does that make sense? Happy to discuss about this behavior with the team 😄

**Review by tidy-dev — APPROVED** [review]
✨  

> idea was not bothering users with notifications from repositories

Ah ok. I just didn't realize that is how it was intended to work.

**Comment by angusdev** [comment]
`idea was not bothering users with notifications from repositories`

Is it good? For me, notification is to notify me that something I need to know but I'm not currently focusing on, and it's how it works in mobile phone.  Also there shouldn't be very frequent for normal user. Or open source maintainers will get many notifications?

**Comment by sergiou87** [comment]
@angusdev yeah the intention is to have "high-signal notifications", as in things we are 99.99% sure are relevant to you. You could be in the same repo working on a different branch, and want to know about things that happen in your previous branch.

In any case, after discussing with the team, we'll gather some metrics about how many users get events from the current repo vs from other recent repos, and use that data to decide if we change this behavior in the future.

Thanks for your feedback! ❤️

**Pull request merged**
