### PR TITLE
show the current branch before the default branch

### LINKED ISSUE #2322: Create new branch from current branch
Can you please make Create New Branch from current branch instead of master?

Looks more logical to me. 
I do it wrongly from master all the time =\9

### PR DESCRIPTION
**Pull request by shiftkey**
Fixes #2322 

Minor thing, but I figure this is the best way to force the discussion :trollface:

### CODE REVIEW

**Comment by joshaber** [comment]
The order was a very conscious design that @niik and @donokuda outlined in https://github.com/desktop/desktop/issues/1137. So I'll throw this in design review for them to look at.

**Comment by shiftkey** [comment]
> We've operated under the assumption that we should switch what branch is selected by default from the current branch to the default branch. This is probably the most contentious issue and I'd love some discussion around it. Our thinking was that creating a branch that's not based off of master (in the majority of cases) is the exception rather than the norm.

This is a good point, and I'll throw my 2c in for this change seeing as I'm the only opening this PR:

 - users are only going to see this dialog when they're not on the default branch - it feels a bit counter-intuitive to then favour the default branch for these cases
 - switching branches can be time-consuming when the current branch and default branch diverge greatly - if you're on a non-default branch, maybe you want to keep working there?

**Comment by donokuda** [comment]
> users are only going to see this dialog when they're not on the default branch - it feels a bit counter-intuitive to then favour the default branch for these cases

I can see that given that we've diverged from the default behavior of `git checkout -b`.

> switching branches can be time-consuming when the current branch and default branch diverge greatly - if you're on a non-default branch, maybe you want to keep working there?

I also don't have strong feelings on this. 😅 For me, it comes down to how often you intend on branching off of a feature branch (as in, I'm about to try something out that I'm not sure will work) vs. master (as in, I'm about to start on a new task.)

**Comment by niik** [comment]
As @joshaber said, this was a conscious decision that we made. We want to promote creating branches off of the default branch (the GitHub flow) which we believe is the majority use case. If there's a strong argument to be made for our assumptions being false I can get behind a change but I'd like to have more feedback than we have at present before flip-flopping on that decision. 

This PR and the originating issue seems to be filled a lot of "no strong feelings" so I guess what I'm saying is that I would want someone to have strong feelings and arguments so that we're not being reactive and ending up upsetting people who are happy with the current state of affairs.

Lastly I'll summarize by saying that I absolutely welcome discussion around this, and explicitly called out my want for it in the original issue but that I don't think we have enough off it yet to make a decision to change this flow.

**Comment by shiftkey** [comment]
> This PR and the originating issue seems to be filled a lot of "no strong feelings" so I guess what I'm saying is that I would want someone to have strong feelings and arguments so that we're not being reactive and ending up upsetting people who are happy with the current state of affairs.

cc @jamland for further feedback on this

**Comment by jamland** [comment]
For me, this looks much obvious. Same as
`git checkout -b new-branch-from-current`
vs
`git checkout -b new-branch-from-master master`

And second thing is that, currently, you need to do the same action twice to create from current branch. This is not big deal but anyway:
**1. Pick branch-1**
2. Click New Branch
3. Name branch
**4. Pick branch-1**
5. Click Create Branch

But I see a sense in your decision:
> We want to promote creating branches off of the default branch (the GitHub flow) which we believe is the majority use case.

I'm not sure about majority flow & does anyone else have the same problem /maybe it just because I'm inattentive 😬 which is true/  
Ofc I don't want to force you to do one-man feature.
For the statistics, personally, doing branches from other than master half of the times.

**Comment by Janpot** [comment]
In case you're looking for statistics: new branches from master, 100% of the time

**Comment by InfiniteAlgorithm** [comment]
I have seen a use case where `master` is the live/client-ready/mass consumption branch, and all dev work is branched from a `develop` branch. In this scenario, 100% of branches are off `develop` and merges always funnel through `develop` --> `master`.

While in this example yes, a toggle for the default branch to modify the default branch would be a convenience, I agree the majority use case would default as `master` and do not believe this case warrants a change to that assumption.

**Comment by j-f1** [comment]
@InfiniteAlgorithm
If you change the default branch of the repository to `develop`, the one that says “master” will change to “develop.”

**Comment by joshaber** [comment]
So thinking about how we can resolve this, we could start tracking how often users choose each option. If they usually switch, then it seems like a good case for this PR.

**Comment by xt0rted** [comment]
With this dialog I switch to the current branch more often than leaving it on master. The reason is because I'm moving on to a new piece of work that depends on the prior work which hasn't been merged yet. I also sometimes get a little side tracked and start on the next piece of work before the current is finished so I want to branch & save before going back to what I should have been doing.

If I'm branching from master than more often than not it's after I was just in the console pulling from upstream at which point the dialog doesn't give these options.

**Comment by timofonic** [comment]
@shiftkey Any news about this?

**Comment by shiftkey** [comment]
@iAmWillShepherd for the most part, I keep coming back to this point:

>  We want to promote creating branches off of the default branch (the GitHub flow) which we believe is the majority use case.

It's not like we're hiding an option here (the original issue was about changing the default), and I'm struggling to think of additional benefits we've not covered that might justify this change.

I'm going to close it out, address the original issue, and if others feel strongly about the other ideas in here like this, then please open a fresh issue with details to discuss it further:

> So thinking about how we can resolve this, we could start tracking how often users choose each option. If they usually switch, then it seems like a good case for this PR.

**Pull request closed without merging**
