### PR TITLE
Show ? in Dark Mode Blank State

### LINKED ISSUE #6915: "no commit found" graphic has missing question mark
We made a change in https://github.com/desktop/desktop/pull/6910 to restore the "no commit found" graphic but we uncovered that, for the dark theme, the ? inside the speech bubble is missing:

Contrast that with the light theme:

The SVG file that needs to be tweaked is `app/static/common/empty-no-commit.svg`

### PR DESCRIPTION
**Pull request by say25**
## Overview

**Closes #6915**

## Description

- Adds question mark in dark mode svg by cutting it out of the speech bubble shape. 
    - Had to brush up on some [SVG syntax](https://stackoverflow.com/questions/3742479/how-to-cut-a-hole-in-an-svg-rectangle)

### Notes to Reviewer

- It was kinda hard to see the changes as this svg is just one line unlike some of the other svgs in Desktop ([UFO](https://raw.githubusercontent.com/desktop/desktop/development/app/static/common/ufo-alert.svg), [Paper Stack](https://raw.githubusercontent.com/desktop/desktop/development/app/static/common/paper-stack.svg), [Empty No Branches](https://raw.githubusercontent.com/desktop/desktop/development/app/static/common/empty-no-branches.svg)). Maybe its worth multi-lining this guy then looking at the diff?

#### Light Mode

image

#### Dark Mode

image

## Release notes

Notes: ```[Improved] Visibility of "?" the no commit selected graphic in the dark theme```

### CODE REVIEW

**Comment by shiftkey** [comment]
> * It was kinda hard to see the changes as this svg is just one line unlike some of the other svgs in Desktop

@desktop/design any objections to this?

**Comment by outofambit** [comment]
I would not be opposed to making this SVG multiline at all! In fact I'd prefer it! 😄 

also thanks for digging into thsi @say25!

**Comment by shiftkey** [comment]
@say25 feel free to add a commit to this branch which improves the formatting of the SVG, and we can close this out.

**Comment by say25** [comment]
On it now 😄

**Comment by say25** [comment]
@outofambit @shiftkey did a new line commit followed by the actually change commit

**Comment by shiftkey** [comment]
@say25 that's great - thanks for making the change clearer!

**Comment by shiftkey** [comment]
Gonna merge this in now because of multiple approvals and trying to pay down our outstanding PRs queue.

**Pull request merged**
