### PR TITLE
Upgrade to Electron 6

### PR DESCRIPTION
**Pull request by kuychaco**
⚠️Superseded by #8967 ⚠️

Kicking off the work to move us to Electron 6, as Electron 5 will be unsupported in the coming months (once Electron 8 is released)

## Release notes

Notes:

### CODE REVIEW

**Comment by tierninho** [comment]
I combed through the 230+ [known issues](https://github.com/electron/electron/issues) with Electron 6 (at least the labeled ones) to try an uncover any potential bugs that we may face. Most were one-offs will little to go, as anything major was already squashed. 

Some **trends** I spotted are below, which I will keep my eye on when testing commences in a few days. 

### 6.1.x known issues with:
- iframe/ webFrame
- Zooming, Full screen mode, resizing windows
- Native tabs

### 6.0.x known issues with:
- Global shortcuts: https://github.com/electron/electron/issues/20567
- Offscreen memory leaks: https://github.com/electron/electron/issues/20559
- Rendering crashes: https://github.com/electron/electron/issues/20461 and https://github.com/electron/electron/issues/20334 and https://github.com/electron/electron/issues/20278 and https://github.com/electron/electron/issues/19842 and https://github.com/electron/electron/issues/18177
- Black screen / white screen: https://github.com/electron/electron/issues/20263 and https://github.com/electron/electron/issues/20109
- Full screen and resizing: https://github.com/electron/electron/issues/20237 and https://github.com/electron/electron/issues/15494 and https://github.com/electron/electron/issues/20228 and https://github.com/electron/electron/issues/9608 and https://github.com/electron/electron/issues/20178 and https://github.com/electron/electron/issues/19934 and https://github.com/electron/electron/issues/19921 and https://github.com/electron/electron/issues/18842 and https://github.com/electron/electron/issues/19712
- Devtools and dark mode: https://github.com/electron/electron/issues/19468 and https://github.com/electron/electron/issues/19589 and https://github.com/electron/electron/issues/18830 and https://github.com/electron/electron/issues/13008
- Modal focus and menus: https://github.com/electron/electron/issues/18502 and https://github.com/electron/electron/issues/12760
Scrolling: https://github.com/electron/electron/issues/17635 and https://github.com/electron/electron/issues/14261 and https://github.com/electron/electron/issues/18925

**Comment by kuychaco** [comment]
@tierninho reports after smoke testing:
> All is checking out thus far in Mac and Windows :white_check_mark: Will do a more thorough round after the holidays

**Comment by kuychaco** [comment]
@tierninho further reports:

> no issues have been found upon further testing in Mac/Windows.

🎉

**Comment by tierninho** [comment]
As we do not have an Electron 7 issue/PR yet, I am posting some observations here in regards to [known issues](https://github.com/electron/electron/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A7-0-x+) with v7:

Window resizing
- Closing child window hangs app: https://github.com/electron/electron/issues/20086
 - Resizing windows crash: https://github.com/electron/electron/issues/19921
- Another resizing issue: https://github.com/electron/electron/issues/18978

Loading:
- LoadURL results in hanging: https://github.com/electron/electron/issues/19921
- Reloading crash: https://github.com/electron/electron/issues/15366

Keyboard:
- no navigation enabled: https://github.com/electron/electron/issues/11587
- shortcuts not working: https://github.com/electron/electron/issues/19747

**Comment by kuychaco** [comment]
Closing this as it has been superseded by #8967

**Comment by Adamsmith66** [comment]
hey guys I wanna someone favor

**Pull request closed without merging**
