### PR TITLE
Update test manifest with rbb scenarios

### PR DESCRIPTION
**Pull request by meaghanlewis**
This PR:
- adds a section for RBB
- updates references from `History` tab -> `Changes`

### CODE REVIEW

**Comment by shiftkey** [comment]
@meaghanlewis feel free to merge this in if there's no other changes you want to make to the manifest

**Comment by meaghanlewis** [comment]
Thanks @shiftkey. There's no other changes I want to make, but it looks like I don't have permission to merge. Can you merge this?

**Comment by agisilaos** [comment]
@meaghanlewis Since the core team is distributed, they leave the PR's approved for quite some time so, the member(s) of the team can check the approved PR and raise any concerns etc.

**Comment by iAmWillShepherd** [comment]
Sorry about that @meaghanlewis .

**Pull request merged**
