### PR TITLE
allow for local build in getSha

### LINKED ISSUE #6000: Local build errors on getSha
## Description

probably introduced by https://github.com/desktop/desktop/pull/5663

## Version

* GitHub Desktop: `master`

* Operating system: Mac OS 10.13.6

## Steps to Reproduce

* clone repo
* `yarn`
* `yarn build:dev`

### Expected Behavior

successful build

### Actual Behavior

```shellsession
/Users/outofambit/GitHub/desktop/script/build-platforms.ts:25
  throw new Error(
        ^
Error: Unable to get the SHA for the current platform. Check the documentation for the expected environment variables.
    at Object.getSha (/Users/outofambit/GitHub/desktop/script/build-platforms.ts:25:9)
    at Object.<anonymous> (/Users/outofambit/GitHub/desktop/script/build.ts:53:67)
    at Module._compile (module.js:652:30)
    at Module.m._compile (/Users/outofambit/GitHub/desktop/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/outofambit/GitHub/desktop/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at Object.<anonymous> (/Users/outofambit/GitHub/desktop/node_modules/ts-node/src/bin.ts:147:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
error Command failed with exit code 1.
```

### PR DESCRIPTION
**Pull request by outofambit**
## Overview

**Closes #6000**

## Description

- accounts for local environment by checking if `NODE_ENV` is `development`
- should it return something besides an empty string?

### CODE REVIEW

**Comment by shiftkey** [comment]
Oops, I guess I did overlook local development at the time. That line was just for debugging purposes so I'd recommend just reverting it to what it was doing before:

```diff
diff --git a/script/build.ts b/script/build.ts
index ab69f54c5..0f68248af 100755
--- a/script/build.ts
+++ b/script/build.ts
@@ -43,14 +43,14 @@ import {
 } from '../app/package-info'
 
 import { getReleaseChannel, getDistRoot, getExecutableName } from './dist-info'
-import { getSha, isRunningOnFork, isCircleCI } from './build-platforms'
+import { isRunningOnFork, isCircleCI } from './build-platforms'
 
 const projectRoot = path.join(__dirname, '..')
 const outRoot = path.join(projectRoot, 'out')
 
 const isPublishableBuild = getReleaseChannel() !== 'development'
 
-console.log(`Building for ${getReleaseChannel()} from commit id ${getSha()}…`)
+console.log(`Building for ${getReleaseChannel()}…`)
 
 console.log('Removing old distribution…')
 fs.removeSync(getDistRoot())
```

**Comment by shiftkey** [comment]
Closing in favour of #6004

**Comment by scottge** [comment]
It's giving the same error when I do 'yarn build:prod'.   Am I supposed to do the production build in local development env?

**Comment by shiftkey** [comment]
@scottge thanks for the heads up. I've opened https://github.com/desktop/desktop/pull/6005 to address that step.

**Pull request closed without merging**
