### PR TITLE
Don't dismiss dialogs when dragging from the dialog to the backdrop

### LINKED ISSUE #8276: Modal / Popup too easy dismissive
Hi there, 

First of all, thank you for creating an easy way to work with GitHub from a GUI. 

Now, the issue: I want to create a repository so I open up the modal / popup. I had to redo all the steps over and over again because whenever I clicked outside the popup, it closed... 

Seriously, this should not be dismissive unless we click the `close` / `cancel` button. 

image

* GitHub Desktop: 2.1.3
* Operating system: Windows 10

Thank you,
Alex S.

### LINKED ISSUE #8544: Add Local Repository -> Create Repository Instead -> Window Disappears
### Describe the bug

If you click "_File->New repository_" you are taken to the "_Create a new repository_" window. The cursor is already focused on the "_Name_" input field. 

If you use the mouse to highlight any of the text in the "_Name_" or "_Description_" fields then and then let go of the mouse button off the side of the window, GH Desktop will close the "_Create a new repository_" window without giving the user an opportunity to save their changes. It is incredibly frustrating. 

I think it has something to do with an "_onmouseup_" event. The issue seems to only happen when a mouse click is initiated on the window and ended off the window. I cannot confirm but it seems more sensitive when you get the window to open using "_Add local repository_" rather than "_New repository_."

### Version & OS

Windows 7 SP1
GH Desktop v2.2.1
GH Desktop v2.2.2

### Steps to reproduce the behavior

1. Open GH Desktop.
2. Create a new repository.
3. Type a name for your new repository.
4. Highlight the name that you typed in. Start clicking ON the input field.
5. End click OFF THE SIDE of the "_New repository_" window.
6. If you let go of the mouse button AFTER the cursor has left the "_New Repository_" window; the window will close unexpectedly.

### Expected behavior

The window should only close when the "_onclick_" and "_onmouseup_" events BOTH happen outside of the "_New repository_" window.

### Actual behavior

If any "_onmouseup_" events happen outside the "_New repository_" window while it is open; it will close unexpectedly.

### Screenshots

N/A

### Logs

The following logs seem to correspond to the unexpected behaviour...
_2019-10-28T18:11:51.829Z - info: [ui] Current tutorial step is NotApplicable_
_2019-10-28T18:13:54.943Z - info: [ui] Current tutorial step is NotApplicable_
_2019-10-28T18:15:37.716Z - info: [ui] Current tutorial step is NotApplicable_
_2019-10-28T18:16:28.472Z - info: [ui] Current tutorial step is NotApplicable_
_2019-10-28T18:16:34.525Z - info: [ui] Current tutorial step is NotApplicable_
_2019-10-28T18:16:45.376Z - info: [ui] Current tutorial step is NotApplicable_
_2019-10-28T18:16:55.024Z - info: [ui] Current tutorial step is NotApplicable_
_2019-10-28T18:16:59.300Z - info: [ui] Current tutorial step is NotApplicable_

### PR DESCRIPTION
**Pull request by niik**
Closes #8544

## Description

This ensures that in order to dismiss a dialog by clicking on the backdrop the user must press down  as well as release their pointer device over the backdrop. Prior to this PR it was possible to press down on the pointer device over the dialog contents, drag the cursor outside of the dialog, and release in order to dismiss the dialog.

## Release notes

Notes: [Improved] Don't dismiss dialogs when dragging the mouse

cc @billygriffin

### CODE REVIEW

**Comment by billygriffin** [comment]
@niik Thanks! Doesn't this also close #8544?

**Comment by niik** [comment]
> @niik Thanks! Doesn't this also close #8544?

Silly me, I even reopened that issue so that I could refer to it from this PR but then I messed it up. I've updated the PR body now. I'm not sure if we should say that this issue closes #8276 or not? It's not super clear whether the original reporter was referring to click and drag or just click there. What do you think?

**Comment by billygriffin** [comment]
@niik I think it's reasonable to say it just closes #8544 for now, and we can think about #8276 in the context of #8349 maybe?

**Comment by niik** [comment]
> @niik I think it's reasonable to say it just closes #8544 for now, and we can think about #8276 in the context of #8349 maybe?

Yeah, that's my gut feeling as well.

**Pull request merged**
