### PR TITLE
Prevent scrollbars on the y-axis from appearing.

### PR DESCRIPTION
**Pull request by hanbings**
[#17320](https://github.com/desktop/desktop/issues/17320)

## Description

- Fix: When pasting text that exceeds the width of the window into the Commit Messgae (Summary) input box in the Commit Panel at once, a scrollbar will be generated in the entire Commit Panel.

### Screenshots

GIF

## Release notes

Notes:

### CODE REVIEW

**Review by tidy-dev — CHANGES_REQUESTED** [review]
Thank you for wanting to fix this!

I pulled and tested it out and I am not seeing a change in behavior. I inspected and this  added css rule isn't being applied as it is overwritten.

Shows the overflow-y being overwritten by #repository-sidebar .panel css rules

I tested with setting it in the `#repository-sidebar .panel` ruleset per this PR and it does correct the pasting issue.. but it reverts an accessibility fix in that if a user zooms to 200%, we need the panel to scroll vertically, with this fix it does not.

Thus, I believe what we really want is to control the `overflow-x` as that is the horizontal scroll.

If you would like to make the change, 

Need to add `overflow-x: hidden` to `#repository-sidebar .panel  ` rule.
https://github.com/desktop/desktop/blob/b6643f10443846b9122910f276f50b73c9aa141d/app/styles/ui/_repository.scss#L25-L30

This will stop the horizontal scrollbar from appearing when pasting, users can interact with the input as normal to see entire contents.

**Comment by hanbings** [comment]
I've added the style, thanks for your help. @tidy-dev

**Comment by sergiou87** [comment]
Ouch! I just noticed this PR and submitted my own here: https://github.com/desktop/desktop/pull/17472 Sorry!

I _think_ my changes are more focused behind the culprit of the issue (the description explains where it comes from) but I'll discuss with the team.

**Comment by hanbings** [comment]
Okay, no problem, as long as the problem can be solved. (Just close the PR when appropriate)
Thanks everyone.

**Comment by sergiou87** [comment]
Closed in favor of https://github.com/desktop/desktop/pull/17472

Thanks again for taking the time to look into this! 🙇‍♂️

**Pull request closed without merging**
