### PR TITLE
Fix permission issue when loading extension

### LINKED ISSUE #14183: There is no React Dev Tool when developing the app
### Describe the bug
There's no React Dev Tool in the inspect panel. Looking at the code it should have though, so I'm reporting this as a bug.

### Version & OS

I'm on the latest development branch, using MacBookPro with M1 Max.

### Steps to reproduce the behavior

1. yarn
2. yarn build:dev
3. yarn start

### Expected behavior

There should be a React Component Tab

image

### Actual behavior

There is not
image

### Logs

While there's an error in the log saying the extensions encounter an error: `Cannot read properties of undefined (reading 'instance')`
The error goes away once I upgrade electron to `"electron": "^17.1.2",`

Here the log after the upgrade:
[2022-03-16.desktop.development.log](https://github.com/desktop/desktop/files/8259635/2022-03-16.desktop.development.log)
- There are no errors now, but the app still doesn't have React Dev Tool

I even tried manually loading the dev tools as suggested here:
https://www.electronjs.org/docs/latest/tutorial/devtools-extension

Still no Dev Tool, and also no error/warning in the log

### PR DESCRIPTION
**Pull request by tsvetilian-ty**
Closes #14183

## Description
- Update `electron-devtools-installer` dependency
- Applied allowFileAccess option to `installExtension()`

### Screenshots
image

### CODE REVIEW

**Comment by tsvetilian-ty** [comment]
`electron-devtools-installer` uses additional dependency to [microsoft/tslib](https://github.com/microsoft/tslib), which uses [BSD Zero Clause License](https://github.com/microsoft/tslib/blob/main/LICENSE.txt), but [atom/legal-eagle](https://github.com/atom/legal-eagle) doesn't support 0BSD as permissive licenses.

**Comment by tsvetilian-ty** [comment]
Update: Opened PR (atom/legal-eagle#19) in [atom/legal-eagle](https://github.com/atom/legal-eagle) to add Zero-Clause BSD as permissive license

**Review by sergiou87 — CHANGES_REQUESTED** [review]
Thanks for this @tsvetilian-ty!! ❤️ 

I just checked about the tslib license, and I think you don't need to update legal-eagle for this. Instead, you can change the `script/licenses/license-overrides.ts` file to add a new entry at the bottom for `tslib@2.3.1` (you'll notice we already have one for 2.0.0, which can be removed).

You can probably create an object with the license data and reuse it, something like…
```typescript
const tslibLicenseOverride = {
  repository: 'git+https://github.com/microsoft/tslib',
  license: 'BSD',
  source:
    'https://github.com/microsoft/tslib/blob/74f1ff794985b33657b599b611e82937e3074617/LICENSE.txt',
  sourceText: `Copyright (c) Microsoft Corporation.

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.`,
}
...
  'tslib@2.0.0': tslibLicenseOverride,
  'tslib@2.3.1': tslibLicenseOverride,
```

**Comment by tsvetilian-ty** [comment]
@sergiou87 I didn't catch that there is an option for license override 😵‍💫 😄

**Review by sergiou87 — APPROVED** [review]
Looks good and works like a charm, thank you!! 🙇‍♂️

**Pull request merged**
