### PR TITLE
make this label more explicit

### PR DESCRIPTION
**Pull request by shiftkey**
This was something @nerdneha raised when we were pairing a while ago, and I was :thumbsup: to making this label clearer. And with [label improvements](https://github.com/blog/2505-label-improvements-emoji-descriptions-and-more) just shipped we can add a better description to go with it.

### CODE REVIEW

**Comment by nerdneha** [comment]
i'm definitely 👍 but i'm going to leave it to the rest of @desktop/core to discuss

**Comment by lee-dohm** [comment]
Yeah, I think this is a good change :+1:

**Comment by jamescriscoe** [comment]
Changes approved
1 approved review by reviewers with write access. 
@iAmWillShepherd
iAmWillShepherd approved these changes
See review
All checks have passed
3 successful checks

ci/circleci — Your tests passed on CircleCI!
Details

continuous-integration/appveyor/pr — AppVeyor build succeeded
Details

continuous-integration/travis-ci/pr — The Travis CI build passed
Details
This branch has no conflicts with the base branch
Only those with write access to this repository can merge pull requests.

**Comment by iAmWillShepherd** [comment]
Deleted @jamescriscoe comment because it appeared to be spam.

**Comment by shiftkey** [comment]
This label has ben updated in the issue tracker.

**Pull request merged**
