### PR TITLE
Added Coda 2 support (Mac)

### PR DESCRIPTION
**Pull request by kerkenit**
## Description

Added support for the Coda 2 editor from [Panic](https://www.panic.com/coda/)

## Release notes

Notes: no-notes

### CODE REVIEW

**Comment by tierninho** [comment]
In general it seems to work well. 👍 

PS. Coda 2 looks like it is getting replaced by Nova. https://www.panic.com/nova/ Not a blocker by any means.

**Comment by kerkenit** [comment]
Hi @tierninho I didn't run the app. I don't know how to compile this app.
If you can send me some instructions how to build I can test the code myself try to fix this issue.
Thanks in advantages!

**Comment by tierninho** [comment]
If you would like to attempt a similar integration for Nova, please open a new pull request.  There is no obligation to do it. Thanks for setting up Coda 2.

**Comment by outofambit** [comment]
@kerkenit we haven't heard back from you in a while, so I'm going to close this pull request but please let us know if you want to continue working on this!

**Pull request closed without merging**
