### PR TITLE
Add support for Typora editor in macOS, Windows

### LINKED ISSUE #5558: add support for Typora
There are currently two choices for an external editor in a local repo on my Mac OS machine: `Sublime Text` and `BBEdit`. These are likely popular choices, but they're certainly not the only good choices. 

I think the best solution long-term is to allow users to add any app they wish. If that's impractical, I'd like to see at least the following two apps added to Mac OS: 
1. Typora 
2. Text Edit

### PR DESCRIPTION
**Pull request by joaomlneto**
Adds support for the [Typora](https://typora.io) external editor

Small-ish quirk: focus doesn't jump to the editor when opened.

Fixes #5558

### CODE REVIEW

**Comment by shiftkey** [comment]
Tenatively moving this into 1.4.1 (subject to review)

**Comment by shiftkey** [comment]
> Small-ish quirk: focus doesn't jump to the editor when opened.

I'm not sure how to fix this one either - the OS should help bring Typora to the front after launching 🤷‍♂️

**Comment by shiftkey** [comment]
@joaomlneto I see Typora also has support for Windows and Linux builds - are you interested in adding support for those? If you don't have access to a Windows or Linux VM then it might be easier to just track an issue for someone who is using that setup to help contribute that work...

**Comment by iAmWillShepherd** [comment]
TIL what a great little editor Typora is thanks to @joaomlneto 💟

**Comment by joaomlneto** [comment]
> Typora also has support for Windows and Linux builds - are you interested in adding support for those?

- Linux: definitely :-) give me an hour
- Windows… never tried any development. But I guess I can give it a go!

**Comment by IntelOSt** [comment]
cmd.to

**Pull request closed without merging**
