### PR TITLE
make new rebase flow available for beta users

### LINKED ISSUE #5953: Better support rebase workflows
A big theme of the past year of our work on Desktop has been working to make collaboration easier. A big part of that, and something we're still iterating on, is supporting merging work from one branch to another. However, in hearing from our users and talking to folks in the wild, we know that many workflows either require or benefit from rebasing as opposed to merging. Therefore, we'd like to make this possible in Desktop.

There are two primary problem areas we want to focus on.

1. **This is the problem described in #3422: When I pull in Desktop, I don't want it to create a merge commit because it clutters my commit history and makes it harder to quickly discern "real" commits.**

2. **I'm required to (or prefer to) rebase when bringing code from one branch to another branch, and Desktop does not allow me to do this.** (described in #1652)
2a. Merging brings together branches in one fell swoop, and I can't tell what code was written when chronologically.

Considerations for problem 1:

1. Is this an optional selection that exists in preferences? Is there some other way to choose to rebase when pulling as opposed to pulling normally?
2. What happens if there's a conflict / multiple conflicts during the pull?

Considerations for problem 2:

1. How do you enter the rebase experience?
2. How do we show people what commits are going to be rebased so they have comfort around what's going to happen?
3. How does it work when you run into a conflict / multiple conflicts throughout the rebase?
4. How do you know when you're done?

Note: We're considering interactive rebasing as out of scope for this initial iteration, and may be something we look at further along.

Next steps:

- [x] Design prototype
- [x] Usability testing of prototype
- [x] Take feedback to produce designs and share
- [ ] Build and release initial iteration

cc: @shiftkey @ampinsk @nerdneha

### PR DESCRIPTION
**Pull request by shiftkey**
## Overview

Closes #5953

We're planning to get a rebase MVP ready for beta this week, and once we're feeling good to go we should merge in this change to enable the feature flag for our beta users.

## Release notes

Notes: `[New] enable rebase flow for beta users to gather feedback`

### CODE REVIEW

**Comment by shiftkey** [comment]
I'm going add `ready-for-review` once we've settled on a timeline for the beta release.

cc @billygriffin to help figure out who is running point on it

**Comment by billygriffin** [comment]
@shiftkey No constraint on my end, but @nerdneha is ultimately responsible for specifics around releases so I'll defer to her. My only limitation would be @tierninho giving a "final" 👍 that it's buttoned up and ready to ship to beta.

**Comment by tierninho** [comment]
As #7167 was just tested and fixed, I think we are in a good state. Getting all the rebase work into one beta build would be ideal for testing purposes. Overall, I believe it is stable, and will be on the look out for edge cases. The only other open rebase issue is #7199 which I will get to today, but not sure it that will hold up beta or not.

**Comment by shiftkey** [comment]
Moving this on to `ready-to-review` as my two outstanding rebase-related PRs have been approved today, so I think that's all I'm trying to land for the next beta.

**Pull request merged**
