### PR TITLE
[Stashing] Changed the button title from Clear to Discard

### LINKED ISSUE #7304: [Stashing] Update button title of clear button in stash diff UI
Change the _Clear_ button text to _Discard_.

ui

### PR DESCRIPTION
**Pull request by roottool**
## Overview

**Closes #7304**

## Description
This PR changes the button title in stash diff UI from `Clear` to `Discard`.

### Screenshot
ToDiscard

## Release notes

Notes: no-notes

### CODE REVIEW

**Comment by shiftkey** [comment]
Thanks for the contribution @roottool! I'm going to ask @iAmWillShepherd to identify when we can land this - hopefully it'll go out with our next beta, but it shouldn't be long after that!

**Comment by iAmWillShepherd** [comment]
Going to merge this now to ensure it makes beta.

**Comment by iAmWillShepherd** [comment]
Thanks for your contribution @roottool! 💯

**Comment by billygriffin** [comment]
Congrats on your first contribution being merged into GitHub Desktop @roottool! We should have a beta coming out this week and then production in the next few weeks, so look out for those to see it ship to users. 😄

thank you

**Pull request merged**
