### PR TITLE
feat(integration): add Tabby terminal integration for macOS

### LINKED ISSUE #16040: Add Tabby terminal integration for macOS
### The feature request

Add [Tabby](https://github.com/Eugeny/tabby) terminal integration for macOS

### Proposed solution

PR #16041.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ansidev**
Closes #16040

## Description

- Add Tabby terminal integration for macOS

### Screenshots

Screen Shot 2023-01-31 at 14 48 17
Screen Shot 2023-01-31 at 14 48 58

## Release notes

Notes: [Added] Add Tabby terminal integration for macOS

### CODE REVIEW

**Review by tidy-dev — CHANGES_REQUESTED** [review]
👋 Thank you for wanting to contribute. I pulled this down and tested it out. However, it appears to fail to open to directory of the repository. Likely you need to modify the launch parameters as done for a couple of other editors in the `launch` method of the `shells\darwin.ts` you have already been modifying. For that, you will likely need to refer to the Tabby docs to determine how to address it.

**Comment by ansidev** [comment]
> 👋 Thank you for wanting to contribute. I pulled this down and tested it out. However, it appears to fail to open to directory of the repository. Likely you need to modify the launch parameters as done for a couple of other editors in the `launch` method of the `shells\darwin.ts` you have already been modifying. For that, you will likely need to refer to the Tabby docs to determine how to address it.

I fixed.

**Review by tidy-dev — CHANGES_REQUESTED** [review]
This is looking great! Sorry, I forgot to check this before, but one more little change. Can you add it to the list of shell integrations for macOS is the `shell-integration.md`? 🙏 

Something like:
image

**Comment by ansidev** [comment]
> This is looking great! Sorry, I forgot to check this before, but one more little change. Can you add it to the list of shell integrations for macOS is the `shell-integration.md`? 🙏
> 
> Something like: image

Done.

**Review by tidy-dev — APPROVED** [review]
✨ Thanks for those changes!

**Pull request merged**
