### PR TITLE
Remove overeager caching from merge-branch-chooser

### LINKED ISSUE #19710: Branch Merge Results Differ Between Remote and Local
### The problem

Hello,

I’ve noticed some odd behavior with branch merging recently, and it seems that the behavior differs depending on whether the branch is remote or local. I’d like to request a review of this issue.

I’ve attached some screenshots for reference:

| Screenshot 1 | Screenshot 2 |
|--------------|--------------|
| image | image |
| Merging `origin/main` into branch `b`, shows up-to-date. | Merging the **local branch** `main` into branch `b`, shows 11 commits, which shouldn’t exist. |

| Screenshot 3 | Screenshot 4 |
|--------------|--------------|
| image | image |
| Merging branch `b` into branch `c`, inconsistent behavior observed. | Another example of merging branch `b` into branch `c`. |

This doesn’t seem to happen consistently, but to help with testing, I’ve shared the repository I used for testing:
[https://github.com/zeikar/merge-test](https://github.com/zeikar/merge-test).

Thank you!

### Release version

3.4.10-beta3 (arm64)

### Operating system

macOS 15.1.1 (24B91)

### Steps to reproduce the behavior

1. Create a new repository.
2. Create a new branch.
3. Test merging between the local branch and the remote branch.

### Log files

_No response_

### Screenshots

_No response_

### Additional context

It seems to work correctly after restarting the application.

### PR DESCRIPTION
**Pull request by niik**
Closes #19710

## Description

So in #19626 I added a caching layer to make it really quick to scroll through the list of branches using a keyboard. Unfortunately it took me until debugging #19710 to realise that the cache key I use to cache the results from `getAheadBehind` was `...[branchname]`. So for example `...main` which is the worst case scenario. Once we had calculated the number of commits from the current branch to main that would get cached (essentially) in perpetuity regardless of what branch you were on and regardless of whether the tip of main had changed or not.

The first approach to solving this was to use the tip sha's as the cache key as we do for determineMergeability. Unfortunately it turns out the list of branches and the current branch tip is snapshotted into the `ChooseBranchStep` so it doesn't change until the dialog is closed and reopened.

Given that we want this to go out in a hotfix the simplest and safest solution is to just remove the caching for now and look for ways to add it back in later properly.

## Release notes

Notes:

### CODE REVIEW

**Review by tidy-dev — APPROVED** [review]
Makes sense!

**Comment by willetta22** [comment]
> Closes #19710
> 
> ## Description
> So in #19626 I added a caching layer to make it really quick to scroll through the list of branches using a keyboard. Unfortunately it took me until debugging #19710 to realise that the cache key I use to cache the results from `getAheadBehind` was `...[branchname]`. So for example `...main` which is the worst case scenario. Once we had calculated the number of commits from the current branch to main that would get cached (essentially) in perpetuity regardless of what branch you were on and regardless of whether the tip of main had changed or not.
> 
> The first approach to solving this was to use the tip sha's as the cache key as we do for determineMergeability. Unfortunately it turns out the list of branches and the current branch tip is snapshotted into the `ChooseBranchStep` so it doesn't change until the dialog is closed and reopened.
> 
> Given that we want this to go out in a hotfix the simplest and safest solution is to just remove the caching for now and look for ways to add it back in later properly.
> 
> ### Screenshots
> ## Release notes
> Notes:

**Review by Rock1raw — COMMENTED** [review]
Data info

**Comment by SoeAung95** [comment]
Margr

**Comment by SoeAung95** [comment]
Marge.and release

**Review by MurdoqZodoq — COMMENTED** [review]
Unit B 644 Joseph E Lowery NW 30318 GA

**Comment by hedayatullahhafizi** [comment]
19730

**Comment by hedayatullahhafizi** [comment]
19730

**Comment by 3406Momo** [comment]
**search**

**Comment by Nm774499** [comment]
> Unit B 644 Joseph E Lowery NW 30318 GA

**Comment by blackroseoneblackroseone** [comment]
ssh -T git@github.com

**Pull request merged**
