### PR TITLE
Improved error message for enterprise users related to their internet connection

### LINKED ISSUE #2574: No internet connection message for Enterprise users
For .com user we flash a 'no internet connection message' when trying to publish a repo without a connection, yet for Enterprise we do not give the same message.

Seems like this message should include "check your internet connection" or we should use the same messaging for the .com user.
screen shot 2017-08-29 at 1 58 41 pm

tested in 0.8.1-beta2, mac.

Reproduce:
- set up new repo to publish to Enterprise
- turn off internet and fill out Enterprise server to trigger messaging

### PR DESCRIPTION
**Pull request by agisilaos**
Fixes #2574 

So with that change I improved the error message of the enterprise users. For example now if they're not connected to internet the error message will remind them of that fact and they will check their connection. 

Would love to know if you like this change and how we can improve the message even more.

### CODE REVIEW

**Comment by j-f1** [comment]
Thanks for contributing! It looks like your commit isn’t associated with your account. To fix this, go to [your email settings](https://github.com/settings/emails) and add your `@microsoft.com` email address

**Comment by agisilaos** [comment]
hey @j-f1, sorry for that. Fixed it by making the commit with an email connected to my account. Is that ok? Excited for this PR to get merged! :)

**Comment by shiftkey** [comment]
@agisilaos it looks like you have a merge conflict with `master` - probably due to #2822

**Comment by agisilaos** [comment]
Ah I see, how I can fix that @shiftkey? Can't press the resolve conflicts button because I don't have write access.

**Comment by shiftkey** [comment]
@agisilaos I don't think the web editor can resolve this one. We have [a handy guide](https://help.github.com/articles/about-merge-conflicts/) about merge conflicts, and [how to resolve them on the command line](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/).

**Comment by agisilaos** [comment]
Seems like I fixed the conflict with my latest commit @shiftkey ✨

**Pull request merged**
