### PR TITLE
watching for index.lock to be safer about committing

### LINKED ISSUE #908: handle the presence of index.lock better
Seems to be an uptick in these occurring, at least on Windows. VSCode 1.9.0 might be to blame (i wasn't running Desktop:TNG at the time):

### LINKED ISSUE #2566: Committing while app is refreshing gives an error
I didn't capture a screenshot for this in time, but I just tried a couple times to hit the commit button and got the same error popup each time about how another git process was running and there was already an index.lock file. I noticed the second time that the "Push origin" button was showing "Refreshing repository". I think because the app was refreshing the repository that _that_ was the other git process that was ongoing, and the reason I couldn't commit. It felt a bit odd, like the right hand didn't know what the left was doing.

Maybe the commit button could be disabled while the app is doing stuff? I didn't tell it to refresh the repository; I'd prefer to be able to disable auto-refreshes like that (see #1128) instead of disabling the commit button.

I'm in version 0.8.0 on macOS.

### PR DESCRIPTION
**Pull request by shiftkey**
This is an experiment to address #908 and #2566 by monitoring for the presence of an `index.lock` file within the current repository and propagating that back through the app state.

It turns out that it's fairly easy to watch a directory for changes, so I leveraged `fs.watch` and some learnings from how [`file-watcher`](https://www.npmjs.com/package/file-watcher) works internally to put together a watcher for the existence of `index.lock`.

This is then flowed through the app state and down to the commit button, to sit alongside the rest of the state that we use to determine whether the app should let the user commit changes.

Fixes #908 
Fixes #2566 

 - [x] docs
 - [x] merge #2568 
 - [x] fix impacted test and it's `Maximum call stack size exceeded` error
 - [x] feedback
 - [x] testing

### CODE REVIEW

**Comment by joshaber** [comment]
I've heard some rumblings from the Atom team about file watching. I think they have some expertise here that could be useful. /cc @smashwilson, @BinaryMuse

**Comment by smashwilson** [comment]
> I've heard some rumblings from the Atom team about file watching. I think they have some expertise here that could be useful. /cc @smashwilson, @BinaryMuse

We are indeed working on our own native filesystem watching implementation at [@atom/watcher](https://github.com/atom/watcher). It _may_ be useful here for you once it's ready, because:

* I want to have it gracefully fall back to stat polling in situations like monitoring an NFS mount.
* I want it to fail gracefully on Linux once watch descriptors are exhausted. There is a _per-user_ watch descriptor limit that's about 8k by default on Ubuntu.

Other than that, it's likely to be overkill for you:

* A lot of the work I'm doing is to make it extra scalable to many watch roots (~1000x watchers, on directories of ~10000x entries) because it's exposed as a public API in Atom for packages to use.
* I'm also taking a fair amount of pain to correlate rename events and correctly classify filesystem entry kinds (file, directory, symlink). Because you're only watching for `index.lock` I don't think that's important here.
* We aren't even supporting non-recursive watchers yet, although it is on the 1.0 milestone.

In the meantime, `fs.watch` should be sufficient for what you're doing here :smile:

**Comment by shiftkey** [comment]
@smashwilson thanks for the extra context. I'll keep on trucking along with this approach in the meantime! 💖

**Comment by joshaber** [comment]
I have some concerns with this approach and I apologize because I should have raised them sooner :hurtrealbad: 

They broadly fit into two categories:

#### UX

1. We don't communicate to users why the button is disabled. If a lock file gets left behind by a crashed process, the button's just stuck, mysteriously disabled.
1. Most of the time we could just retry the commit with a delay and the user would never have to know or care.

### Technical

1. Watching the file system is inherently racy. It's entirely possible that in the time it takes for the file watcher to notice the lock file (or its absence) and propagate that state to the UI, the lock status will have changed.
1. The signal-to-noise ratio is high. There will be a lock file a lot of the time, but it only matters rarely.

**Comment by shiftkey** [comment]
@joshaber it's all good, I figured this would just be a starting point which is why I kept it simple.

> Most of the time we could just retry the commit with a delay and the user would never have to know or care.

This seems like an reasonable alternative to evaluate, but we'd still eventually find ourselves needing to deal with this situation with either solution:

> If a lock file gets left behind by a crashed process

Which we should probably think about while we're tackling this problem. 

> It's entirely possible that in the time it takes for the file watcher to notice the lock file (or its absence) and propagate that state to the UI, the lock status will have changed.

Using VSCode to test this PR, you'll see the commit button flicker disabled-then-enabled whenever VSCode does a `git status` on the repository. It's pretty snappy, but also might lead to confusion around why it's doing that.

> The signal-to-noise ratio is high. There will be a lock file a lot of the time, but it only matters rarely.

**Comment by j-f1** [comment]
> you'll see the commit button flicker disabled-then-enabled whenever VSCode does a git status on the repository

This could be fixed by waiting a few hundred milliseconds after `index.lock` appears before disabling the button.

**Comment by shiftkey** [comment]
De-prioritizing this for now, will ponder on alternatives in the meantime

**Pull request closed without merging**
