### PR TITLE
Create new GitStore when default branch changes

### LINKED ISSUE #1489: updated default branch isn't shown in branch list until after restart
### Description

If the default branch is changed on the GitHub or GitHub Enterprise server, this is refreshed in the local IndexedDB but not displayed until a restart.

### Version

What version of GitHub Desktop are you running? This is displayed under the
`About GitHub Desktop` menu item. If you are running from source, include
the commit by running `git rev-parse HEAD` from your local repository.

**GitHub Desktop version:** 1.5.1

**OS version:** macOS Sierra 10.12.4

### Steps to Reproduce

1. Create a new repository, make a commit, publish to GitHub
1. Create a new branch, named `second-branch` 
1. Publish the branch to the server
1. Visit the repository's branches settings page: `https://github.com/{account}/{repository}/settings/branches`
1. In the branch selector page, select the branch `second-branch` and press `Update`.
1. Switch back to the application and switch between repositories to force a refresh
1. Open the branch list

**Expected behaviour:** Default branch is listed as `second-branch`

**Actual behaviour:** Default branch is still `master`

**Reproduces how often:** it reproduces despite switching or performing a fetch until the app is restarted.

### PR DESCRIPTION
**Pull request by joshaber**
Fixes #1489 

As I said [in the issue](https://github.com/desktop/desktop/issues/1489#issuecomment-317098395), this is a bit fiddly. The root of the problem was that state was being cached by repository ID in a few different places. So even if the values of the repository (or, more specifically, the values of its GitHub repository) changed which should invalidate the cache, some state would continue to be cached.

### CODE REVIEW

**Comment by joshaber** [comment]
🏷 📌

**Comment by mwoolweaver** [comment]
I'm on Windows 10 using GitHub Desktop 1.6.6 and i'm still not seeing any change on the Desktop app even tho GitHub.com show the default branch being changed. Have closed the app multiple times with 0 change in behavior.

**Comment by tierninho** [comment]
@mwoolweaver Thanks for filling. Just tested this based on the steps from the original issue here https://github.com/desktop/desktop/issues/1489#issue-228918738 and all seems fine. Can you attached your logs? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs in Explorer (Windows).

**Comment by mwoolweaver** [comment]
@tierninho here you go kind stranger. 

[2019-05-21.desktop.production.log](https://github.com/desktop/desktop/files/3204704/2019-05-21.desktop.production.log)

**Comment by tierninho** [comment]
@mwoolweaver This error message `fatal: unable to access 'https://github.com/mwoolweaver/tweetStats.git/': Could not resolve host: github.com
` seems to indicate a connectivity problem. Do you currently have any antivirus software installed other than the default antivirus that ships with Windows?

Additionally, are you using a proxy server to access the internet? Git requires special configuration to work behind proxy servers, see #1998, #2789

**Comment by mwoolweaver** [comment]
No anti-virus and I use a vpn? but no proxy server

**Comment by mwoolweaver** [comment]
Ok so after further testing it seems to be a bunch of user error on my part. Sorry for any confusion i might have caused

**Comment by tierninho** [comment]
No worries. Thanks for the update!

**Comment by mwoolweaver** [comment]
somehow i missed the part where it required a 2nd repo to switch between before the change takes effect.

**Comment by mido1966** [comment]
Pls No Email mor pls Tank you



Von meinem Samsung Galaxy Smartphone gesendet.


-------- Ursprüngliche Nachricht --------
Von: Michael Woolweaver <notifications@github.com>
Datum: 22.05.19 00:10 (GMT+01:00)
An: desktop/desktop <desktop@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [desktop/desktop] Create new GitStore when default branch changes (#2411)


No anti-virus and I use a vpn? but no proxy server

**Comment by mido1966** [comment]
Pls No Email mor pls Tank you



Von meinem Samsung Galaxy Smartphone gesendet.


-------- Ursprüngliche Nachricht --------
Von: Tiernan L <notifications@github.com>
Datum: 22.05.19 00:09 (GMT+01:00)
An: desktop/desktop <desktop@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [desktop/desktop] Create new GitStore when default branch changes (#2411)


@mwoolweaver<https://github.com/mwoolweaver> This error message fatal: unable to access 'https://github.com/mwoolweaver/tweetStats.git/': Could not resolve host: github.com seems to indicate a connectivity problem. Do you currently have any antivirus software installed other than the default antivirus that ships with Windows?

Additionally, are you using a proxy server to access the internet? Git requires special configuration to work behind proxy servers, see #1998<https://github.com/desktop/desktop/issues/1998>, #2789<https://github.com/desktop/desktop/issues/2789>

**Pull request merged**
