### PR TITLE
Use unicode emoji

### PR DESCRIPTION
**Pull request by sergiou87**
Based on #19101

## Description

This PR prefers the use of unicode emoji characters over image-based emojis.

#### Windows

image
image
image

#### macOS

image
image
image

## Release notes

Notes: [Improved] Use OS emojis

### CODE REVIEW

**Review by niik — APPROVED** [review]
Looks good! There's two things I'd like to address as part of this work but I'm happy if we do it in a separate PR.

First I'd like for us to not include the image assets in the final bundle for the emoji that have unicode representation. Secondly I'd like for us to align with dotcom's behavior of inserting the unicode character when typing `:+1...` in a text editor instead of inserting the literal `:+1:` string. I can take a stab at the latter.

**Comment by sergiou87** [comment]
Love it! I will merge this now and take care of the assets later. Loving your PR already 😍

**Comment by mustafaabobakr** [comment]
@sergiou87 Hey, 
###  Where to get this emoji "memes" pack?

image

**Comment by sergiou87** [comment]
@mustafaabobakr https://github.com/github/gemoji

**Pull request merged**
