### PR TITLE
Add Jetbrains PhpStorm, WebStorm Editors for Linux

### PR DESCRIPTION
**Pull request by patinthehat**
## Description
This PR adds the Jetbrains PhpStorm and WebStorm editors for Linux. These editors have already been added for the Windows platform.

### CODE REVIEW

**Review by sergiou87 — DISMISSED** [review]
Thank you for this! 🙌

**Comment by patinthehat** [comment]
@sergiou87 the failed checks are unlikely to be from the changes in this PR as they do not add functionality.  You can likely merge this PR safely even though the checks have not passed. :+1:

**Comment by sergiou87** [comment]
```
$ prettier --check "./**/*.{ts,tsx,js,json,jsx,scss,html,yaml,yml}"
Checking formatting...
[warn] app/src/lib/editors/linux.ts
```

I'm afraid they're not and you have to fix the format of those changes. You can run `yarn lint:fix` and that's it! (or run `Format` from VS Code, it should do the same)

**Comment by patinthehat** [comment]
> you have to fix the format of those changes

@sergiou87 Ah, sorry about that! Everything is all formatted correctly now. Thanks for the heads up! :smile:

**Review by sergiou87 — APPROVED** [review]
No worries! It's all good 😄  Thanks for the quick fix :shipit:

**Pull request merged**
