### PR TITLE
port registry usage to use PowerShell API

### LINKED ISSUE #3105: unable to detect PowerShell due to group policy blocking registry access
### Description

In the previous version of GitHub desktop client I could specify PowerShell as the shell to launch for a given project, and it gave me cool information in the command line about the current state of the repo (if I was ahead/behind, conflicts, changes, etc.). There is no longer an option for me to select PowerShell in the new version. There is a drop down in advanced options for shell, but it only has "Command prompt" in it.

### Version

**GitHub Desktop version:** 1.0.4

**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

1. Launch the client
2. Go to File -> Options and click on the Advanced tab
3. Click the drop down for Shell.

Expected: A number of shells are available (cmd, ps, bash, etc.)
Actual: only cmd is available.

4. Launch the cmd shell for a project.
Expected: it gives data about the local branch vs. tracking branch in the command line
Actual: it does not.

**Expected behavior:** That I can use PowerShell for git through github desktop client and that it gives me information in the shell about the branch.

**Actual behavior:** It is not possible and I can only use a command prompt with no info.

**Reproduces how often:** 100%

### LINKED ISSUE #3123: Open in Atom not working in Github Desktop
### Description

I have just installed Atom 1.21.1 (x64), and then Github Desktop (1.0.4) on a Win 10 Pro machine. In the desktop client I cloned a repository form Gitlab, and up to this point, everything seemed to work fine. Up to the point I wanted to open the repository in Atom. I tried the menu, right clicking, etc., and it simply does nothing. Reinstalled Atom and Github Desktop, several times actually with different degrees of removing the pieces left over by the uninstall, but bo luck. I did my best to google the issue, but still no luck.
Funny thing though, on another laptop, Win 10, same versions for Atom and the Github Desktop, same installation procedure (first Atom then the Desktop) opening the repository in Atom worked fine from the first attempt, though it takes a while.

### Version

**GitHub Desktop version:** 1.04

**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

1. Install Atom (x64)
2. Install Github Desktop (x64)
3. Clone a Wiki repository from, say Gitlab (*.wiki.git)
4. Try to open the repository in Atom.

**Expected behavior:** The repository should open in Atom.

**Actual behavior:** Nothing. The repository doesn't open in Atom.

**Reproduces how often:** Every time.

### Logs
2017-10-22T16:36:35.660Z - info: [ui] launching: 1.0.4 (Windows 10.0.15063)
2017-10-22T17:28:56.706Z - info: [ui] [AppStore] loading 1 repositories from store
2017-10-22T17:28:56.708Z - info: [ui] [AppStore] found account: empgithub (null)
2017-10-22T17:28:56.967Z - info: [ui] launching: 1.0.4 (Windows 10.0.15063)
2017-10-22T17:47:13.693Z - info: [ui] [AppStore] loading 1 repositories from store
2017-10-22T17:47:13.695Z - info: [ui] [AppStore] found account: empgithub (null)
2017-10-22T17:47:13.882Z - info: [ui] launching: 1.0.4 (Windows 10.0.15063)
2017-10-22T18:13:25.055Z - info: [ui] [AppStore] loading 1 repositories from store
2017-10-22T18:13:25.057Z - info: [ui] [AppStore] found account: empgithub (null)
2017-10-22T18:13:25.251Z - info: [ui] launching: 1.0.4 (Windows 10.0.15063)

### PR DESCRIPTION
**Pull request by shiftkey**
Fixes #3105 
Fixes #3123

Strap yourselves in folks, it's time for a story.

[Group Policy](https://en.wikipedia.org/wiki/Group_Policy) is a thing which lets administrators lock down their Windows machines. And here's the group policy for stopping apps from writing to the registry:

In theory, `reg.exe` shouldn't need to write the registry when you do `REG QUERY [key]` but here we are:

And we can't fix `reg.exe` so I'm all:

And I start looking at alternatives. I really want to not use PowerShell here but it turns out we're already doing something very similar in `squirrel-updater.ts`:

 - we find `powershell.exe` - so we assume it's already installed

https://github.com/desktop/desktop/blob/24d46faec25e2f2117f84c4e0f522e838a262492/app/src/main-process/squirrel-updater.ts#L160-L171

 - we then spawn a process, handling encodings

https://github.com/desktop/desktop/blob/24d46faec25e2f2117f84c4e0f522e838a262492/app/src/main-process/squirrel-updater.ts#L173-L187

 - we parse the output

https://github.com/desktop/desktop/blob/24d46faec25e2f2117f84c4e0f522e838a262492/app/src/main-process/squirrel-updater.ts#L189-L191

Fiiine, let's do this. This means I avoid the worries about active code pages from before.

 - [x] tests all pass
 - [x] unify powershell-esque code into a reusable module
 - [x] cleanup jank from previous `reg.exe` approach
 - [x]  `Out-String` the result to ensure it's formatted nicely for parsing

### CODE REVIEW

**Comment by shiftkey** [comment]
@damieng just a heads up - `winreg` also depends on `reg.exe`, not sure if you've had any reports like this but it's used [here](https://github.com/atom/atom/blob/eeacc157eecbe958887235eae6821725dee05931/src/main-process/win-shell.js) in Atom.

**Comment by shiftkey** [comment]
The only reservation I have about this PR is the performance impact - it goes from 50-70ms to 300-600ms, which becomes significant on the preferences view when we do this a bunch concurrently.

**Comment by niik** [comment]
> The only reservation I have about this PR is the performance impact - it goes from 50-70ms to 300-600ms, which becomes significant on the preferences view when we do this a bunch concurrently.

Could we use something which accesses the native APIs directly? Like https://www.npmjs.com/package/windows-registry ?

**Comment by damieng** [comment]
Yeah we've had a couple of reports of problems with not being allowed access to reg.exe but we use it to setup our shell integration on launch from the installer/updater as well as in the settings view where you can toggle the various integration options.

That windows registry npm package does look useful though. My experience with doing crazy shell tricks to work around issues tells me whatever you come up with will be flakey between OS versions. (We do a powershell trick for --wait and it's been a crazy ride)

**Comment by shiftkey** [comment]
> Could we use something which accesses the native APIs directly? Like https://www.npmjs.com/package/windows-registry ?

@niik this is a good shout. I'm not sure why I avoided it when I was initially looking at our registry support - maybe because the API was rather raw? I'll give it a shot and see if it's faster than the PS approach.

**Comment by begoldsm** [comment]
@shiftkey huge ups for even doing this heavy lifting investigative work. Thank you thank you thank you!

**Comment by j-f1** [comment]
@begoldsm

> Is it possible to do the registry read check one time?

This sounds like a good idea, but how would it handle installing or uninstalling supported editors?

**Comment by begoldsm** [comment]
@j-f1 that is a good question. There could, perhaps, be an explicit option to "add/remove" an editor which could require elevation when it does it's check? I am not familiar with all the surface area where GitDesktop reads from the registry. 
Ideally it would be possible to just read from the registry using standard tools, but from my quick search PowerShell is the only one I have found that is built in.

**Comment by shiftkey** [comment]
> Out of curiosity, is it possible to do the registry read check one time (during initial install) and then save the values that are important to the app in AppData? 

This doesn't cover the ability for users to add and remove items, as @j-f1 mentioned. The app refreshes it's list of editors and shells on each launch but will defer it until you do something with the app (like open the Options view). That won't cover everyone (for example, if you an install an editor after checking your options and noticing it's not there), but keeps the code simple enough.

> There could, perhaps, be an explicit option to "add/remove" an editor which could require elevation when it does it's check?

I'd rather not make this something that requires manual work by the users, let alone all the work to manage elevation correctly.

> I am not familiar with all the surface area where GitDesktop reads from the registry.

Here's the current list:

 - We [check](https://github.com/desktop/desktop/blob/0cf02e3b09755215c34a87596a738e90fb8d430c/app/src/lib/shells/win32.ts#L41-L43) where your PowerShell install is found
 - We [check](https://github.com/desktop/desktop/blob/0cf02e3b09755215c34a87596a738e90fb8d430c/app/src/lib/shells/win32.ts#L55-L57) for a Git for Windows install so we can enable Git Bash
 - The install location for each editor under [`app/src/lib/editors/win32.ts`](https://github.com/desktop/desktop/blob/master/app/src/lib/editors/win32.ts)

**Comment by begoldsm** [comment]
@shiftkey ah that makes sense. Then yeah, I am not sure if there is a better way in windows to read from the registry when this group policy exists :(

**Comment by j-f1** [comment]
@shiftkey 

> getting additional work incorporated seems unlikely in the short term: CatalystCode/windows-registry-node#52

You could fork the repo and `npm install desktop/windows-registry-node`.

**Comment by shiftkey** [comment]
@j-f1 after spending a bunch of time with `windows-registry-node` I don't think it's worth trying to mash in here. I've got some simple native code which I'll package up once it's working correctly and use that instead.

**Comment by damieng** [comment]
Can you let me know when you've packaged that up?  Would be nice to get
Atom off of the command-line wrapper as it often fails in schools and work
environments as reg.exe is locked down.

**Comment by shiftkey** [comment]
@damieng sure thing - I only currently need [`RegEnumValue`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724865%28v=vs.85%29.aspx) (and crimping a lot from [this sample](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724256%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396)) but let me know if there's other functionality you need and I can pull that in at some stage.

**Comment by shiftkey** [comment]
Alright, I went back to the drawing board and have a working registry API that's pure C++. The start is https://github.com/desktop/lean-mean-registry-client/pull/9 and I'll open a PR to migrate us over to this new library once it does what we need it to do.

**Pull request closed without merging**
