### PR TITLE
Rely on Git's init.defaultBranch config

### LINKED ISSUE #11447: GitHub Desktop still defaults to creating a default branch titled master instead of main in some cases
### Describe the bug

GitHub Desktop still defaults to creating a default branch titled master instead of main when building out a new repository. GitHub was moving away from this practice to be more inclusive.

### Version & OS

Version 2.6.2 on Windows 10

### Steps to reproduce the behavior

1. Log into your account on GitHub and open GitHub Desktop (if they aren't open already)
2. Navigate to your repositories (https://github.com/{{YOUR_PROFILE_NAME}}?tab=repositories)
3. Click the green 'New' button that should be in the upper left corner
4. Add a valid repository name
5. Add a valid repository description
6. Public/private doesn't matter
7. Click 'Create repository'
8. Once it is created, go to GitHub Desktop and File>Clone repository...
9. Click the refresh button to the mid-upper left
10. Click your new repository's name
11. Click the Clone button near the bottom
12. Current branch is now set to **master.**

You cannot rename master from here by going to Branch>Rename or by hitting Ctrl+Shift+R.
This does not change if you create a file, until that file is pushed.

### Expected behavior

In step 12, I expected that the current branch would be set to **main.**

### Actual behavior

In step 12, the current branch was set to **master.**

### Screenshots

A screenshot of a repository called i_caused_a_bug with the current branch set to master. A file named foo.py is displaying it's diff, which only includes the comment "# foo.y"

github_desktop_bug_report_master_0

### Logs

[2021-01-23.desktop.production.log](https://github.com/desktop/desktop/files/5860573/2021-01-23.desktop.production.log)

### Additional context

I just hope it's fixed soon. It seems like if I create a new repository from GitHub Desktop (test in the logs), it sets the first branch to main as expected, so that's a good start.

### PR DESCRIPTION
**Pull request by niik**
Closes #11447 

## Description

While clearing out TODOs ahead of my parental leave I saw that I had made a note to rip out some workarounds we put in place while we waited for Git 2.28+. Since we shipped 2.29 in #11469 

⚠️ I didn't test this before pushing and I obviously can't take any ownership of it so please review thoroughly and make any necessary changes ⚠️

### CODE REVIEW

**Review by sergiou87 — DISMISSED** [review]
What a beautiful cleanup! Thank you! 😍 

I'll take ownership of this 😌

**Comment by sergiou87** [comment]
I made a few additions:
- Use the default branch name when creating a new (non-tutorial) repo.
- Grab the default branch name from a GH repo before cloning it via API and use that. This will only affect empty repos.
Cloning empty repos hosted somewhere else will use the app's default branch name instead.

Things I tried to test this PR:
- Changed the default branch name in my account's Settings -> Repositories to `something` and created a tutorial repository. The branch created in that tutorial repository should be `random`.
- Changed the default branch name in the app's Settings -> Git, and create new repositories. They should have the branch name from the app Settings.
- Cloned empty repositories hosted in GH. Their branch name is whatever is in my GH account's Settings -> Repositories
- Cloned empty repositories not hosted in GH. Their branch name matches what I have in the app Settings.
- Cloning non-empty repositories respects all existing branches.

@tidy-dev do you think you could give this PR another look 👀   and maybe also test it in case I overlooked something? 🙏

**Review by roriwin — APPROVED** [review]

**Review by tidy-dev — APPROVED** [review]
Looks good - I pulled it down and tested it out. 

Works as expected: 
- creating new repos in app uses default branch from app
- creating new repo and clone from GitHub.com uses default branch from GitHub.com settings (empty or non empty)
- cloning empty repos from non-github.com uses app default branch
- cloning non empty repo respects repo's defined default branch

A scenario I tested in addition to see what it did was:
- Create a repo on GH
- Clone it
- Got to repo settings > branch on GH and change default branch
- Fetching on app does not retrieve/set this new default branch 

It appears this scenario already behaved this way - also this flow is also not directly related to the changes (fetching vs. cloning) But, just figured I would throw it out there as a means that default branch isn't respected... when maybe it should be?

Something similar appears documented here (@sergiou87 pointed it out) https://github.com/desktop/desktop/issues/11530

**Comment by sergiou87** [comment]
Thanks for such a thorough testing!! ❤️

**Pull request merged**
