### PR TITLE
[Spike] Use Cypress for Automated UI Testing

### PR DESCRIPTION
**Pull request by tierninho**
Adding the cypress testing framework as it supposedly runs Electron.

- [x] Add local dependencies
- [x] Get Cypress to open GitHub Desktop
- [ ] Write a base case test to prove concept
- [ ] Figure out how to move forward with Cypress

cc @iAmWillShepherd

### CODE REVIEW

**Comment by iAmWillShepherd** [comment]
Their [docs](https://docs.cypress.io/faq/questions/using-cypress-faq.html#Can-I-test-my-Electron-app) say they use Cypress to test their electron app, so this **is** possible. We'll need to have a look at their test suite to see if they do anything special.

**Comment by GBailey7** [comment]
https://circleci.com/gh/desktop/desktop/2440?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
https://github.com/desktop/desktop/pull/3981/commits/d5d7e0a59db5abe4b62cdb39eb13f4f7e231413
https://circleci.com/gh/desktop/desktop/2440?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-linke

**Comment by GBailey7** [comment]
File changed

**Comment by GBailey7** [comment]
https://guides.github.com/features/mastering-markdown/

**Comment by shiftkey** [comment]
@tierninho as discussed in chat, I'm going to close this out for now while this is on the backburner. Feel free to open a fresh PR when you revisit it.

**Pull request closed without merging**
