### PR TITLE
Update integrations docs with new GCM support

### PR DESCRIPTION
**Pull request by steveward**
Related to https://github.com/desktop/desktop/pull/18890.

## Description

- this PR updates our integration docs for GitLab, Bitbucket, and Azure DevOps to reference the new Git Credential Manager option.

## Release notes

Notes: no-notes

### CODE REVIEW

**Review by sergiou87 — DISMISSED** [review]
Beautiful work!

✨ 😗 👌 ✨

**Review by niik — DISMISSED** [review]
I love it. When do you reckon we should ship this? Now or when we're at a higher release percentage?

**Comment by steveward** [comment]
> When do you reckon we should ship this? Now or when we're at a higher release percentage?
 
I think the only downside to shipping now is the potential for a few issues to be opened by users asking why they don't have GCM yet, but I would expect that to be minimal. I don't have a hard preference either way.

**Review by niik — APPROVED** [review]

**Comment by niik** [comment]
> I think the only downside to shipping now is the potential for a few issues to be opened by users asking why they don't have GCM yet

Yeah, I agree. Better to ship it now 👍

**Pull request merged**
