### PR TITLE
Update Windows logo

### PR DESCRIPTION
**Pull request by ampinsk**
This updates our logo on Windows! I tested it on Windows and it seems to look good, except for some reason this spot is still showing the old logo:

Screen Shot 2021-02-05 at 1 53 06 PM

Would love someone's help figuring this out! 🤔

### CODE REVIEW

**Comment by tidy-dev** [comment]
It appears to be a caching thing.

I went to install the latest test version on my VM to try it out and was getting errors.. so then tried to uninstall old version.. it failed.. then removed app data folder and restarted. Finally old version was removed. 

Then, installed test version with new app. Then performed search like you have above and I didn't even get the old icon. I got a generic file icon.

Then, I found this. 
https://superuser.com/questions/1247025/icons-not-showing-in-windows-10-search/1342092#:~:text=Set%20the%20display%20scaling%20to,%25%20and%20then%20100%25%20again.

I did the highlighted part and sign out and signed in and now. I now have new icon.

image

**Comment by tidy-dev** [comment]
Yep. Definitely a cache. Just tried again and all I had to do was sign out and sign back in and I got the new icon (after install prod version back, doing scaling thing, sign out sign in to see old icon, then installing 2.6.3 test6 version again)

Interesting related issue.. was looking to see if we could cause an icon cache clear on install or not. Not sure at this point. But putting this here for reference.
https://github.com/electron-userland/electron-builder/issues/2062

**Comment by sergiou87** [comment]
Same problem with the cache, and also fixed it changing the scaling.

If Windows doesn't take long to invalidate the cache, I'd say we don't need to do anything specific about this 🤞

**Review by tidy-dev — APPROVED** [review]
Looks awesome! 💖

**Comment by sergiou87** [comment]
I love this, thank you! 😍

**Comment by say25** [comment]
Seems to be working on latest beta, nice icon looks great 😄

**Review by mrkingfoxx — COMMENTED** [review]
Yay

**Pull request merged**
