### PR TITLE
don't rely on PATH for knowing where to find chcp

### LINKED ISSUE #2678: Failed To Launch
Error: spawn chcp ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Version: 0.8.1
OS: Windows 6.1.7601

### PR DESCRIPTION
**Pull request by shiftkey**
Fixes #2678:

 - [x] use the known path for `chcp`, don't rely on `PATH` being helpful
 - [x] catch errors and log in the unlikely scenario this has been removed

### CODE REVIEW

**Comment by joshaber** [comment]
(But regardless, this looks good and you should feel free to merge it when CI is 💚)

**Comment by shiftkey** [comment]
> It looks like an exception was being thrown, but I don't see where we'd be preventing that here?

The child process emits an `'error'` event inside [`child_process.js`](https://github.com/nodejs/node/blob/v7.4.0/lib/internal/child_process.js#L213) and we weren't handling it locally, which is bubbling up to our `uncaughtException` [handler](https://github.com/desktop/desktop/blob/0fd567373e2885b1ffc99dc7a27d6bc048bdd8ff/app/src/ui/index.tsx#L79-L96) which is feeding it to the error reporting mechanism.

My gut feeling is that we shouldn't be trusting `PATH`, and pointing to the known `chcp` location is a safer bet. But I've not been able to recreate this locally yet so I'm in the dark around what the root cause is.

**Comment by shiftkey** [comment]
🍎

**Comment by shiftkey** [comment]
Actually, going to ensure this is hardened in a couple of places before reviewing again...

**Comment by shiftkey** [comment]
I won't worry about gold-plating this now that someone has confirmed they didn't have  `C:\Windows\System32\` on their `PATH`.

**Pull request merged**
