### PR TITLE
Add support for Git Bash and PowerShell via the Windows Terminal app

### LINKED ISSUE #16980: Add "Git Bash (via Windows Terminal)" and "PowerShell (via Windows Terminal)" to Integrations/Shell option
### The feature request

When Windows Terminal is a user's primary terminal, being able to open the repository in Git Bash via the Windows Terminal is sometimes preferable than opening a standalone Git Bash application. (See similar previous request: #14071)

### Proposed solution

I think this is as simple as the following:

In `enum Shell`, add:
```ts
WindowTerminalGitBash = 'Git Bash (via Windows Terminal)',
WindowTerminalPowerShell = 'PowerShell (via Windows Terminal)',
```

In `shells/win32.ts`, in the following section of `getAvailableShells`:
```ts
if (windowsTerminal != null) {
  shells.push({
    shell: Shell.WindowTerminal,
    path: windowsTerminal,
  })
}
```
Add two new shell definitions:
```ts
shells.push({
  shell: Shell.WindowTerminalGitBash,
  path: windowsTerminal,
  extraArgs: ['-p "Git Bash"'],
})
shells.push({
  shell: Shell.WindowTerminalPowerShell,
  path: windowsTerminal,
  extraArgs: ['-p "PowerShell"'],
})
```

And finally, in `launch`, add two more cases to `Shell.WindowTerminal`:
```ts
case Shell.WindowTerminal:
case Shell.WindowTerminalGitBash:
case Shell.WindowTerminalPowerShell:
```
And support `extraArgs`:
```ts
return spawn(windowsTerminalPath, ['-d .', ...foundShell.extraArgs ?? []], { shell: true, cwd: path })
```

Note: Adding a profile to the args passed to wt doesn't actually do anything if the user has removed them from their Windows Terminal profiles list, so it's not going to cause errors for people. It'll just open the default command prompt profile.

### Additional context
I've tested out the above code changes and they seem to work, here's a little demonstration of what it looks like:

image
image
image

Side note: If this gets approved, I can submit the changes as a pull request. Let me know!

### PR DESCRIPTION
**Pull request by ChiriVulpes**
Closes #16980

## Description

This commit is the exact changes suggested in the issue except following the formatting better.

### Screenshots

image
image

## Release notes

Notes: Added shell options for opening Git Bash and PowerShell via the Windows Terminal app.

### CODE REVIEW

**Review by tsvetelina999 — COMMENTED** [review]
F

**Comment by tsvetilian-ty** [comment]
Thanks for the contribution @ChiriVulpes 🥳 

I have a few questions regarding your PR. Can the user have a "Windows Terminal" without having a "Git Bash" profile in the terminal? Isn't it possible for the user to rename the profiles?

**Comment by ChiriVulpes** [comment]
If the user has renamed the default profiles in Windows Terminal, these options open Windows Terminal's default shell (whatever that's configured to.) I assume if you don't have Git Bash installed it works the same way, or perhaps WT bundles it? I can look into that if you'd like. 

I do realise that this way of handling this isn't perfect, but the alternatives are running CLI commands against WT or checking its config files at startup to check profiles, and/or a UI where you specify any number of your own custom shell commands, both of which did not seem in scope with my initial feature request.

**Comment by sergiou87** [comment]
Thank you for your contribution @ChiriVulpes 💖 

Unfortunately we think this approach could be problematic since, as @tsvetilian-ty points out, it's possible that the profile is named differently (or that even Git Bash is not installed at that point). We plan to spend some time on improving our editor/shell integration support in the upcoming months and that should hopefully address your needs, so we have decided to close this PR.

Thank you for your patience and sorry for the late reply.

**Pull request closed without merging**
