### PR TITLE
Replace auth error with not found error for non-existent GitHub repos

### LINKED ISSUE #5661: Auth error prompt when cloning repo from nonexistent URL
## Description

On trying to clone a repo using an incorrect URL, Desktop raises an authentication error instead of indicating that the repo wasn't found in the user's profile. 

## Version

* GitHub Desktop: 1.3.5

* Operating system: macOS High Sierra 10.13.6

## Steps to Reproduce

1. Click on Clone repository. 
2. Navigate to the URL section. 
3. Enter an invalid URL. 

### Expected Behavior

Desktop raises an error prompt stating that the provided repo URL is invalid. 

### Actual Behavior

Desktop goes into a loop of error prompts related to authentication. If correct username and password is provided, then the same prompt is raised again.

## Additional Information

screen shot 2018-09-16 at 5 07 09 pm
screen shot 2018-09-16 at 5 07 27 pm

### PR DESCRIPTION
**Pull request by kanishk98**
## Overview

**Closes #5661**

## Description

Adds an `else` block when resolving the cloning URL to return `null` if the `repo` object is `null`, but the account and identifier are valid. Causes app to show the following error:

Github

Discussion regarding possible solutions and test cases at #5816.

Here's what I've tested:
1. `https://github.com/username/no_repo`: Shows error as intended. :heavy_check_mark: 
2. `https://github.com/username/private_repo`: Clones repo. :heavy_check_mark: 
3. `git@github.com:username/no_repo`: Shows error as intended. :heavy_check_mark: 
4. `git@github.com:username/private_repo`: Clones repo. :heavy_check_mark: 
5. `github_username/no_repo`: Shows fatal: repository does not exist. Not sure if we should change this to the more user-friendly error as in the gif above. :confused: 
6. Non-GitHub git URLs, but with the wrong repo URL: Same problem as (5). 

Please also check #5816 for other test cases/solutions that should be considered.

The `account` variable [here](https://github.com/desktop/desktop/blob/2f6dca06b5bc4b1269b5da88d32647ff9d617b6a/app/src/ui/clone-repository/clone-repository.tsx#L607) seems to be `null` in cases 5 and 6, which is probably why we try to clone the repo first and then worry about errors when the `Promise` resolves. 

In case of GitHub URLs, wouldn't it be better to set the account variable correctly?

Marking PR as WIP to allow for discussion on the above. 

## Release notes

Notes: Fixes problem with non-existent repos being flagged as auth errors

### CODE REVIEW

**Comment by kanishk98** [comment]
Hmm, not sure why the CircleCI workflow failed. Looks like I can't rerun it either, so I'll have to wait for some help.

**Review by Dewit62 — DISMISSED** [review]

**Comment by tierninho** [comment]
@kanishk98 Thanks for putting this together!

Some of my testing notes thus far, which is a follow up from [here](https://github.com/desktop/desktop/pull/5816#issuecomment-442966212)
- https://github.com/username/no_repo: Shows error as intended. ✅ 
- https://github.com/username/private_repo: Clones repo. ✅ 
- git@github.com:username/no_repo: Shows error as intended. ✅ 
- git@github.com:username/private_repo: Clones repo. ❌ hangs forever and throws error below
- github_username/no_repo: Shows fatal: repository does not exist. ✅ 
- Non-GitHub git URLs, but with the wrong repo URL: ⬇️ I suggest this modal get nixed
Screen Shot 2019-05-31 at 2 26 12 PM

The error from the ❌ 
```
install.ts:23 `git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- git@github.com:tierninho/wefwerwe.git /Users/tierninho/Documents/GitHub/tests/fff/wefwerwe` exited with an unexpected code: 128.
stderr:
Cloning into '/Users/tierninho/Documents/GitHub/tests/fff/wefwerwe'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 2: Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open preferences and verify that you're signed in with an account that has permission to access this repository.)
```

build 69d9964a8b, mac

**Comment by kanishk98** [comment]
@tierninho thanks for testing this out. 

> git@github.com:username/private_repo: Clones repo. hangs forever and throws error below

I'm unable to reproduce this on my system. I'll attach a gif below for reference, please let me know if I've got the test case wrong:

Correct URL for private repo:

ssh

> Non-GitHub git URLs, but with the wrong repo URL: arrow_down I suggest this modal get nixed

Yeah, I should've taken care of this in the beginning. I'll update this PR soon. Thanks!

**Comment by tierninho** [comment]
@kanishk98 Thanks for confirming. 👍 Probably a local issue with computer then.

**Comment by kanishk98** [comment]
Alright, there's a potential solution to the failing check that I'd like to discuss:

If we use a try-catch instead of just checking `!success`, then we get the following flow for non-existent and private repo URLs:

GitHub

I think we can give better messages to the first error message (maybe "We couldn't find the git repo at ${url}, check if you're logged in")? and then present the second error message as usual. 
Since this is more of a UX problem, I'll wait for someone else's ideas. :)

Pushing https://github.com/desktop/desktop/pull/7634/commits/8b608a958a906bcd94337ae8aec99912aebf6b90 to this PR so you can check out the flow on your end.

**Comment by niik** [comment]
Hey @kanishk98, thanks so much for wanting to contribute. I apologize for this having sat for so long without a review. We're working through a bit of a backlog.

I would love to help get this over the finish line and into the next production release. I've updated this branch to incorporate all the changes since it was last updated and made a few small tweaks. Would you mind if I pushed those changes to this branch and then we could have another engineer do a review on my changes? If not I'm happy to either open a PR targeting this branch or close this PR and incorporate your changes into a new PR.

**Comment by kanishk98** [comment]
Hey @niik, thanks a lot for picking this up!
Please feel free to do as you prefer. I do believe that pushing your new changes to this branch would be the best way to continue development for this fix, but again, it's entirely up to you. 

If you'd like me to carry on or need anything from my end, please let me know. 

Thanks once again!

**Review by niik — APPROVED** [review]
Thank you so much for working on this @kanishk98! Gonna try to get this into the next production release toward the end of the month.

**Comment by kanishk98** [comment]
No worries at all, great to see this merged!

**Comment by edt-andrew** [comment]
I had this problem but signing out and then signing in again fixed it.

**Pull request merged**
