### PR TITLE
Added Support for WebStorm

### LINKED ISSUE #7160: WebStorm is not being detected as an External Editor on Windows
## Description
WebStorm is still not being correctly detected on Windows as an external editor and, after looking at the code, I risk to say that it's not being detected at all.
It has been said that Github Desktop only supports WebStorm 32bits but that's not true because WebStorm is trickier to detect that the other editors (see aditional information for more details)
This reopens issue #6077 which, in turn, also relates to pull request #6272.

## Version
* GitHub Desktop: 1.6.5
* Operating system: Windows 10

## Steps to Reproduce
1. Open GitHub Desktop Options
2. Go to the Advanced tab
3. Check the external editor's drop-down and you'll see that WebStorm isn't there.

### Expected Behavior
WebStorm should show up if installed

### Actual Behavior
WebStorm doesn't show up.

## Additional Information
WebStorm uses the version number of the first installed version to name the key in windows registry so we'll need to find a way to make sure we look for a reg key LIKE 'WebStorm' because it will be something like 'WebStorm 201x.y.z'.

### PR DESCRIPTION
**Pull request by otelom**
## Overview
Closes #7160 

## Description
Adds WebStorm integration as an External Editor

## Release notes
- Fixes WebStorm detection on Windows.

@shiftkey

### CODE REVIEW

**Comment by otelom** [comment]
@shiftkey @billygriffin I need some help, for some reason I cannot select WebStorm from the drop-down.
I've coded it into being detected and it is being correctly detected as well as the launcher (.exe) path but for some reason every time I click WebStorm item in the drop-down it selects the first item which, in my case is, Visual Studio Code.
I still have 2 tests to run but I don't think it will be related so I'd appreciate some feedback.

**Comment by otelom** [comment]
@shiftkey, @billygriffin , I stand by my previous message even though it passed all tests.
It didn't at first because I forgot to run prettier.
I'll be waiting for your feedback

**Comment by otelom** [comment]
@shiftkey and @billygriffin can you guys run this branch in your computers and test it?
I think it might work for your but not for me for some reason...

**Comment by iAmWillShepherd** [comment]
Thanks for your contribution, @otelom!

I've been reviewing your PR and I have been unable to get WebStorm to show up in the list of external editors after installing the latest version. Once I get past this issue, I may be able to help with the issue you're experiencing, selection not working.

**Comment by otelom** [comment]
Hi @iAmWillShepherd thank you for getting back to me.
I think my code will detect WebStorm but the thing is that for some reason I can't test my code because the select won't open to display it's options!
I reached out to WebStorm Support and they assured me that this is the correct way to detect WS. The only downside is that their keys vary from version to version but that's not a problem as long as we can detect one version we know how to get the others working (by adding all the other keys or maybe we'll find a better way)
Have you tried running my code and see if the select box will open for you? Because might be something with my environment....
Keep me updated
Thanks.

**Comment by iAmWillShepherd** [comment]
@otelom, yes, I tried testing out this PR and was unable to see WebStorm in the drop down menu.

**Comment by otelom** [comment]
@iAmWillShepherd I see but that doesn't mean the code isn't right.
It probably just means that you installed WebStorm in a previous version.
Can you check your windows registry and look up for a key like:
HKEY.HKEY_LOCAL_MACHINE
SOFTWARE\\WOW6432Node\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\WebStorm XYZ

Let me know what is your XYZ and I'll update my code to see if my theory checks out.

If you can attach a printscreen of your registry so that I can see clearly the key name and it's properties.

Thanks.

**Comment by iAmWillShepherd** [comment]
> It probably just means that you installed WebStorm in a previous version.

I don't quite understand what you mean here ☝️ 

Screen Shot 2019-05-03 at 10 09 39 AM

**Comment by iAmWillShepherd** [comment]
Removed `ready-for-review` label since there seems to be more investigation needed.

**Comment by otelom** [comment]
@iAmWillShepherd 

> Removed `ready-for-review` label since there seems to be more investigation needed.

Not sure I agree.
Later today I'll push a new update so that you can see it working.



> > It probably just means that you installed WebStorm in a previous version.
> 
> I don't quite understand what you mean here ☝️

Perfect, I got what I needed from that print screen.
I'll explain it to you later today.

**Review by outofambit — CHANGES_REQUESTED** [review]
Hi @otelom and thanks for your work on this. Unfortunately I think there are some critical and blocking limitations in this implementation. I don't see any logic for handling this case (mentioned here: https://github.com/desktop/desktop/issues/7160#issue-425158572):

> WebStorm uses the version number of the first installed version to name the key in windows registry so we'll need to find a way to make sure we look for a reg key LIKE 'WebStorm' because it will be something like 'WebStorm 201x.y.z'.

and from https://github.com/desktop/desktop/pull/7161#issuecomment-488403301 it sounds like this is still an issue in practice as well.

While we're happy to help verify and debug pull requests, the level of effort required here is outside our current capacity to do so. If you are able to verify yourself that this implementation can reliably detect WebStorm, we'll be happy to pick this back up and take another look. If you decide the effort is too significant to take on right now, no worries on our end, just let us know or close this PR.

**Comment by otelom** [comment]
Hey guys,
Just want to let you know that I'm a little swamped in work this next week or two but I'll get back to this for sure. 
I'm pretty sure my code would work I just need a better way to get all versions detected. I have some ideas...
I'll try to find a way to get this working.

**Comment by iAmWillShepherd** [comment]
This PR has not been updated since May 9th, so I'm going to close it.

@otelom, if you've made additional progress since then, feel free to re-open this PR once you've pushed them 👍

**Comment by spiropoulos94** [comment]
Hello guys, did we reach any solutions regarding the webstorm integration on github desktop? 
Thank you in advance.

**Comment by otelom** [comment]
@spiropoulos94 I found the problem and I tried a solution but then I got swamped at work and I haven't had time to come back to it since. The webstorm has works differently then all other editors so identifying it is a little challenge but it can be done. I'll see if I can get back to this in November.

**Comment by jspri3** [comment]
bump!

**Comment by otelom** [comment]
This can't be that hard but I'm so busy that I don't know if I can get to
it anytime soon.
Fortunately it's not that big of an issue so can be postponed as it has
been, sorry... I also use Webstorm but anyway...
One day I'll take another look at this. At the time I got it working on my
machine so it's just a way of trying again.

**Pull request closed without merging**
