### PR TITLE
Show alert icon in repo list for missing repositories

### LINKED ISSUE #4254: Unable to see a “missing” repos on Repo List
## Description

Often you delete a repo from disk and there’s still a reference in GHD.

GHD Classic used to show such repos
screen shot 2018-03-15 at 17 45 41

GHD Electron does not.
screen shot 2018-03-15 at 17 50 09

### PR DESCRIPTION
**Pull request by gingerbeardman**
Fixes #4254

matches look of GHD Classic

### CODE REVIEW

**Comment by gingerbeardman** [comment]
Ticks https://github.com/desktop/desktop/issues/4254

**Comment by niik** [comment]
Hey @gingerbeardman, thanks for you contribution! Could you please drop a screenshot of how this looks on your machine?

**Comment by gingerbeardman** [comment]
Sure thing

screen shot 2018-03-16 at 14 31 49

**Comment by tierninho** [comment]
tested = ✅

**Pull request merged**
