### PR TITLE
Upgrade from Xcode 9.3.0 to 9.3.1 on CircleCI

### PR DESCRIPTION
**Pull request by appplemac**
## Overview

CircleCI will soon deprecate Xcode 9.3.0. More details [here](https://discuss.circleci.com/t/removing-support-for-xcode-versions-9-0-0-9-3-0-and-9-4-0/30084).

Moving the project from 9.3.0 to 9.3.1 should have no impact on the CircleCI jobs, and it will help avoid problems due to Xcode 9.3.0 image deprecation. Plus it will help the project to hit fewer Xcode bugs.

### CODE REVIEW

**Comment by shiftkey** [comment]
> On May 14th, 2019, we are removing the support for the following Xcode versions on CircleCI for macOS:

Oh, this is rather soon. Thanks @appplemac for bringing this to our attention!

I guess this is fine, but I'm going to let it sit for a day and look into how the build has changed to ensure our native Node modules are unaffected.

**Comment by appplemac** [comment]
Yep, sounds great. Thanks for taking a look. Please mention me here if you see any issues with the Xcode 9.3.1 image in CI. 🙏

**Comment by shiftkey** [comment]
@appplemac I note that our use of `yarn` is triggering a deprecation note from the version of Node installed on the build agents (this is minor because we build the native modules against a set version of Electron, but if any of our build tools require native modules they'll be built against this version):

Here's a build on the new agent: https://circleci.com/gh/desktop/desktop/9523

Screen Shot 2019-05-07 at 6 59 53 PM

Here's a build from today on the older agent: https://circleci.com/gh/desktop/desktop/9522

Screen Shot 2019-05-07 at 7 00 33 PM

Short of tweaking the build script to run `node -v`, is there a good reference for what other software is included in these images? Other platforms let you pull in a version of Node but I don't think we've had to do that for CircleCI in the past...

**Comment by glenjamin** [comment]
Previously you were using node 9.10, with this PR you'd be using 10.1.

[The full manifest for 9.3.0](https://circle-macos-docs.s3.amazonaws.com/image-manifest/build-405/index.html) (we've recently removed the link from our docs)

[The full manifest for 9.3.1](https://circle-macos-docs.s3.amazonaws.com/image-manifest/build-419/index.html)

You can see the list of other supported versions here: https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions

Going from 9.3.0 to 9.3.1 is the most likely to be compatible with no other changes, but if you wanted to try going to one of the newer images that might be a better long-term choice.

**Comment by shiftkey** [comment]
@glenjamin thanks for the links! Once this goes green I'm going to merge it and publish a test release to ensure everything is working as expected!

**Pull request merged**
