### PR TITLE
Disable drag-and-drop interaction when a popup is in the foreground

### PR DESCRIPTION
**Pull request by iAmWillShepherd**
Fixes issue #1749

## Before
before

## After
after

### CODE REVIEW

**Comment by j-f1** [comment]
Is there a way to make the cursor have a 🚫 on it so the folder doesn’t just get dropped into oblivion?

**Comment by shiftkey** [comment]
@j-f1 maybe. I think you want to listen to the `dragover` event and set `e.dataTransfer.dropEffect = 'none'` to reject it based on [this doc](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/dropEffect). Not sure about the other options, or how this works on other OSes.

I'll let @iAmWillShepherd chime in too.

**Comment by j-f1** [comment]
Maybe `move` or `copy` for when the drag-and-drop will be accepted?

**Comment by tierninho** [comment]
✅  tested for UI and functionality

**Comment by shiftkey** [comment]
Moving the enhancement discussion out to https://github.com/desktop/desktop/issues/4004 as that can be addressed separate to this fix.

**Comment by iAmWillShepherd** [comment]
@shiftkey you got to it before I could. 

@j-f1, that should be a separate issue since we don't change the cursor on drag-and-drop events when there isn't a popup in the foreground.

**Pull request merged**
