### PR TITLE
Point to the correct version of node

### PR DESCRIPTION
**Pull request by iAmWillShepherd**
Should link to the version of node we are using on CI.

### CODE REVIEW

**Comment by shiftkey** [comment]
I think once this and #3131 land we can revisit #1766, but that's not a priority

**Comment by shiftkey** [comment]
:apple:

**Comment by niik** [comment]
> I think once this and #3131 land we can revisit #1766, but that's not a priority

@shiftkey Should we hold on this until #3131 lands or is this ready to go?

**Comment by iAmWillShepherd** [comment]
@niik This should wait until the other PR is merged.

**Pull request merged**
