### PR TITLE
Upgrade to CodeMirror ^5.60.0

### LINKED ISSUE #10355: Syntax highlighting is broken for new private property symbol in javascript/typescript
### Describe the bug

When looking at a diff written in Typescript or Javascript, if there are any private class properties using the new `#` symbol, they are highlighted in a near unreadable red color.

### Version & OS

Windows 10
Github Desktop 2.5.3

### Steps to reproduce the behavior

1. Create a javascript/typescript file
2. Add a class with a private member using the new `#` symbol
3. Open the diff in Github Desktop

### Expected behavior

The diff should show proper syntax color highlighting.

### Actual behavior

All lines containing the new `#` symbol, color the code lines an almost unreadable red.

### Screenshots
image

### PR DESCRIPTION
**Pull request by say25**
Closes #10355

## Description

- Updates CodeMirror for the purpose of keeping it up-to-date and getting syntax highlighting for private property symbol in javascript/typescript

### Related 

- Highlighter Tests PR - https://github.com/desktop/highlighter-tests/pull/45

#### Before

image

#### After

image

## Release notes

Notes:
- Adds syntax highlighting for private property symbol in javascript/typescript

### CODE REVIEW

**Review by sergiou87 — COMMENTED** [review]
At first sight, I don't see anything obviously problematic in the codemirror upgrade, after looking at [its release notes](https://github.com/codemirror/CodeMirror/releases). It would still require some testing to make sure no regressions were introduced, though 😄

**Comment by jhall11784** [comment]
Accept node

**Review by sergiou87 — APPROVED** [review]
I've tested it and everything worked as expected so far! I'm happy to merge this (probably after the upcoming release)

Thanks again @say25 !! ❤️

**Review by Seli1705 — COMMENTED** [review]
- - @say25

**Pull request merged**
