### PR TITLE
add the declaration for dist-info and tidy up a bit

### PR DESCRIPTION
**Pull request by shiftkey**
Not sure why I didn't do this before. This means we can keep it as JS until we figure out how to extract the bits that the webpack scripts need...

### CODE REVIEW

**Comment by j-f1** [comment]
If you create a `dist-info.d.ts` file, TypeScript `import` statements will use that file to get the types of the exports, but the JS file will be used at runtime. For example:

```ts
// foo.d.ts
export interface Foo {
  bar: string
}
export const foo: Foo
```

```js
// foo.js
exports.foo = {
  bar: 'baz'
}
```

```ts
// bar.ts
import { foo } from './foo'

console.log(foo.bar) // => baz
```

**Comment by shiftkey** [comment]
@j-f1 oooooh, interesting. I'll see if that works locally, that might make the whole `global.d.ts` here unnecessary!

**Comment by mathieudutour** [comment]
> `legal-eagle` is a module and that would require an @types package (or a declaration file in the package)

you can also do something like
```ts
declare module 'legal-eagle' {
  export default function(
    options: LegalEagleOptions,
    callback: (error: Error | null, summary: LicenseLookup) => void
  ): void
}
```
,put that in whatever file you want and typescript will pick up the definition whenever you import `legal-eagle` (you don't pollute the global scope that way)

**Comment by j-f1** [comment]
That declaration looks good. Complete code:

```ts
declare module 'legal-eagle' {
  interface Options { /* ... */ }
  inteface LicenseLookup { /* ... */ }

  declare function legalEagle(
    options: Options,
    callback: (error: Error | null, summary: LicenseLookup) => void
  ): void

}
```

**Pull request merged**
