### PR TITLE
Swap electron development extension installer library

### PR DESCRIPTION
**Pull request by jacortinas**
## Description
Due to some kind of incompatibility with Electron 24 and `electron-devtools-installer` [issue link](https://github.com/MarshallOfSound/electron-devtools-installer/issues/238), react devtools does not automatically install or become available in the development environment. This fixes that issue by moving to an updated `electron-extension-installer` library.

## Release notes

Notes: no-notes

### CODE REVIEW

**Review by tidy-dev — DISMISSED** [review]
Looks pretty straight forward. Thanks!

**Comment by tidy-dev** [comment]
Hmm.. just saw the license issue. Maybe we can't use this package. Looking..

**Comment by tidy-dev** [comment]
Legal-eagle must flag BlueOak-1.0.0 for having a non-permissive license.. but It seems like BlueOak-1.0.0 is a permissive license.

**Comment by niik** [comment]
> Legal-eagle must flag BlueOak-1.0.0 for having a non-permissive license.. but It seems like BlueOak-1.0.0 is a permissive license.

It's not part of the list of permissible licenses here: https://github.com/atom/legal-eagle/blob/b78443856a964f38c543c66b3b4feff5411c1167/src/legal-eagle.coffee#L230 which is why this is failing. It's extracting the license just fine so the override isn't necessary but it's not detected as a permissive license.

Given that legal-eagle is deprecated I think we should see if we can find a more modern approach. I know we have internal tooling for this but I'm not sure if we can avail ourselves of that. I'll ask around some

**Comment by khusikhusi12** [comment]
mujhe ek websit banawana hai pleas help me

**Pull request closed without merging**
