### PR TITLE
enable adding self-signed certificates on Windows

### PR DESCRIPTION
**Pull request by shiftkey**
We bumped Electron to 1.6.11 in #1430 which supported adding self-signed certificates to the user's trusted root certificate store (see https://github.com/electron/electron/pull/9242 for more) but we didn't enable the dialogs for Windows.

Here's the new flow with a self-signed certificate on Windows:

 - when signing in to GHE for the first time we probe to check the server is valid and quacks like a GHE server
 - the certificate error gets raised by Electron, and we ask the user to carefully confirm this is what they expect
 - after adding the certificate, the second probe of the GHE instance is successful

### CODE REVIEW

**Comment by niik** [comment]
@shiftkey Is there any way for us to get a notification once the certificate dialog is terminated so that we could retry automatically rather than let the user go through the flow again?

**Comment by shiftkey** [comment]
@niik not that I'm aware of - it'd have to be something from Electron itself

**Comment by niik** [comment]
> @niik not that I'm aware of - it'd have to be something from Electron itself

Looking at the recording you posted earlier it seems like the dialog is sticking around after we pop the certificate dialog though? Are we blocking the renderer when showing the modal and, if so, couldn't we do the retry synchronously?

**Comment by shiftkey** [comment]
> Are we blocking the renderer when showing the modal and, if so, couldn't we do the retry synchronously?

It currently does (on Windows at least), due to [this Win32 API](https://github.com/electron/electron/blob/master/atom/browser/ui/certificate_trust_win.cc#L87) being blocking and requiring user interaction. And there is a [callback](https://github.com/desktop/desktop/blob/master/app/src/main-process/app-window.ts#L241) that gets invoked as part of `dialog.showCertificateTrustDialog` but that's unused currently in the app.

We don't have any smarts around being able to return to the previous dialog, and I'm not opposed to going down this path, but I'd like to get this fix into the next update to address recent reports about this like #2598.

**Comment by niik** [comment]
> We don't have any smarts around being able to return to the previous dialog in app.tsx, and I'm not opposed to going down this path, but I'd like to get this fix into the next update to address recent reports about this like #2598.

Okay, if you open an issue about addressing the remaining work I'll get this merged. Needs a merge tho

**Comment by joshaber** [comment]
>We don't have any smarts around being able to return to the previous dialog in app.tsx, and I'm not opposed to going down this path, but I'd like to get this fix into the next update

Yeah, I think @niik and I have talked about this in the past: sometimes we really want our dialogs to be a stack instead of replacing the current dialog. But I agree that's separate from this fix.

**Comment by shiftkey** [comment]
Tracking the polish work in https://github.com/desktop/desktop/issues/2622

**Comment by shiftkey** [comment]
:apple:

**Pull request merged**
