### PR TITLE
Upgrade octoicons

### PR DESCRIPTION
**Pull request by rafeca**
Closes https://github.com/desktop/desktop/issues/10223

## Description

This PR updates the `@primer/octoicons` package to v10.0.0, which includes the refreshed icons that have recently been shipped on GitHub.com

### Technical details

Something to take into account is that with the new icons release, icons can now have multiple SVGs depending on the size. 

This PR, though, will discard additional sizes and will only take into account the `16` size (or the first one available if `16` does not exist) for all the icons.

The reasoning behind that is that currently we don't have a way to not include the icons that are not being used in the JS bundle, so including all sizes for each icon would increase the bundle size (and anyways we're rendering the icons with a height of `16px` most of the times).

I'm planning to refactor a bit the script that generates the octoicons data to make the `app/src/ui/octicons/octicons.generated.ts` file export each icon separately, so we can take advantage of WebPack's tree shaking capabilities (once https://github.com/desktop/desktop/pull/10185 gets merged) to not include in the bundle icons or sizes that are not used in the app.

### Screenshots

image

## Release notes

Notes: [Added] Refresh the design of the app icons.

### CODE REVIEW

**Comment by rafeca** [comment]
First issue that I found with the new icons is with the `arrow-up`/`arrow-down` icons. We were using the thick arrows (`arrow-small-up`/`arrow-small-down`) as a way to indicate download/upload actions, but now that there's a single arrow icon that is much thinner, things don't look as good:

Screen Shot 2020-07-17 at 17 21 05

Screen Shot 2020-07-17 at 17 21 38

Screen Shot 2020-07-17 at 17 17 47

I've tried replacing them by the `upload`/`download` icons but things don't look better:

Screen Shot 2020-07-17 at 17 26 35

Screen Shot 2020-07-17 at 17 27 02

Screen Shot 2020-07-17 at 17 25 54

I think we need some additional design tweaks here...

**Comment by niik** [comment]
Outside of the arrow issue there seems to be some problem with the SVGs in this PR. The repository icon isn't supposed to be filled

Screen Shot 2020-07-17 at 17 25 54

image

And the fork icon and branch icons have a missing hole
image
image


image

**Comment by ashygee** [comment]
> but now that there's a single arrow icon that is much thinner, things don't look as good

@rafeca can you expand a bit more on this? The arrow in context looks good to me for the most part, minus the smaller arrow which I think needs some reconsideration. I actually like the use of the `upload` arrow for Publish branch. The pill shapes that contain the arrows in the repo list view could use more padding and I think that will help the icons to feel better.

+1 to @niik 's comment as well about the SVGs not rendering correctly. Let us know if you all need support from our DS engineers on this.

**Comment by rafeca** [comment]
> Outside of the arrow issue there seems to be some problem with the SVGs in this PR. The repository icon isn't supposed to be filled

Good catch! I'll take a look at that!

> @rafeca can you expand a bit more on this? The arrow in context looks good to me for the most part, minus the smaller arrow which I think needs some reconsideration. I actually like the use of the upload arrow for Publish branch. The pill shapes that contain the arrows in the repo list view could use more padding and I think that will help the icons to feel better.

In my eyes the redesigned arrows have a more directional meaning than the previous ones (on my mind they look like pointing to something that it's on the top rather that indicating upload:

Screen Shot 2020-08-06 at 13 58 41

Screen Shot 2020-08-06 at 13 48 26

I think that's a good thing and now the semantical meaning of the arrows is more clarifying, it's just that we're currently using wrongly the `arrow-up` and `arrow-down` icons to indicate push/pull.

I think that the upload/download buttons fit better, but we need to do some tweaks to our current designs to make them fit well: we have some very small "pills" (the smallest ones have a height of 12px) and we'll need to make them bigger (and add more padding as you mention) to accommodate the more detailed new icons.

> +1 to @niik 's comment as well about the SVGs not rendering correctly. Let us know if you all need support from our DS engineers on this.

Thanks for the offer! I'm taking a look at this, but it would actually be good to talk to the DS engineers about the octoicon react components (we're not currently using them and instead build them ourselves from the SVGs, to work around some accessibility issues).

**Comment by rafeca** [comment]
I've fixed the issue with the icons not being generated correctly: it was caused by the new `fillRule` attribute that was added to the paths to the SVGs, which we were not reading. This is one of the drawbacks of manually generating the SVGs ourselves by parsing the path data from octoicons.

I'm going to update the screenshots.

**Comment by brooklynO** [comment]
I've actually only drawn the add co-author one so far. Here that is: 

[add-coauthor.svg.zip](https://github.com/desktop/desktop/files/5100024/add-coauthor.svg.zip)

@ampinsk I put that on the very draft icons page in the ui kit in case you want to take a look. I think you also had another one started there.

**Comment by rafeca** [comment]
In 8f459da I've changed the direction of the animation of the sync button to be counterclockwise, since the new sync icon has the arrows pointing in a counterclockwise direction:

previous icon:

Screen Shot 2020-08-24 at 18 47 01

new icon:

Screen Shot 2020-08-24 at 18 47 14

The animation now looks like (attaching a gif with a `.mov` screen recording, since I couldn't create a gif with enough fps:

[animation.zip](https://github.com/desktop/desktop/files/5119167/animation.zip)

**Comment by niik** [comment]
> In [8f459da](https://github.com/desktop/desktop/commit/8f459da151a13abceebde2fde89c96d35cef4b1e) I've changed the direction of the animation of the sync button to be counterclockwise, since the new sync icon has the arrows pointing in a counterclockwise direction:

Wow, great spot. Having looked at that animation and tried it out in the app it feels really weird for me to have it spin counterclockwise. For our purpose (i.e. as a progress icon) it should spin clockwise. I've added a custom sync icon that's flipped horizontally and turned the spin direction back.

**Comment by niik** [comment]
In lieu of a redrawn arrowSmallUp/Down I've increased the width of the arrows in the ahead/behind view. It's not great because it does eat into our limited toolbar button width but it's good enough that we can merge this and work on custom icons separately IMO.

image

**Review by niik — APPROVED** [review]
Excited to get this refresh in!

**Comment by rafeca** [comment]
> Wow, great spot. Having looked at that animation and tried it out in the app it feels really weird for me to have it spin counterclockwise. For our purpose (i.e. as a progress icon) it should spin clockwise. I've added a custom sync icon that's flipped horizontally and turned the spin direction back.

Sounds good!

**Pull request merged**
