### PR TITLE
Enable "reset to commit" in beta builds

### PR DESCRIPTION
**Pull request by sergiou87**
Related #12393 

## Description

Enable "reset to commit" in beta builds.

## Release notes

Notes: [Added] Reset a branch to a specific commit

### CODE REVIEW

**Review by tidy-dev — CHANGES_REQUESTED** [review]
Just so this doesn't get shipped to beta without the alert dialog, can we go ahead and switch the confirmation to be an alert dialog?

**Comment by sergiou87** [comment]
I thought we decided to keep only this alert when changes were in progress, right?

image

**Comment by tidy-dev** [comment]
Yes. That is the one I am talking about. It isn't an alert dialog. Needs the `role="alertdialog"` and `aria-describedby` added so that screen readers will announce the message on open.

**Comment by sergiou87** [comment]
Ohhhh!!! Good point, and great catch, I thought you were talking about adding another alert 🤦‍♂️ Fixing that right now…

**Comment by sergiou87** [comment]
Done in [fe99464](https://github.com/desktop/desktop/pull/18470/commits/fe994647821ba530dab3829ccb8d9194687940ed)

**Review by tidy-dev — APPROVED** [review]
✨

**Pull request merged**
