### PR TITLE
release notes dialog spacing tweaks

### PR DESCRIPTION
**Pull request by outofambit**
did a little design tweaking based on talking with @donokuda. mostly just paddings/margins.

two columns

one column

### CODE REVIEW

**Comment by donokuda** [comment]
Looking at the second screenshot, I feel like there's a lot of horizontal spacing around the column.

I wonder if a single column should have a larger width, or we could consider reducing the width of the dialog itself.

**Comment by outofambit** [comment]
screen shot 2018-09-06 at 11 00 30 am

**Comment by iAmWillShepherd** [comment]
I'm in agreement with @donokuda on this one. I think we should reduce the width of the dialog or reduce the padding around the content a bit.

**Comment by outofambit** [comment]
@iAmWillShepherd thanks! are you referring to the initial screenshots? or this one: https://github.com/desktop/desktop/pull/5552#issuecomment-419188991 ?

**Comment by iAmWillShepherd** [comment]
Oops, yea, I was referring to the latest one, I still think we can either use more of that white-space, or remove it. But, since we will be iterating on the design of in-app release notes, it may not be worth the time to keep tweaking what you have.

I'm going to go ahead and merge this 👍

**Comment by outofambit** [comment]
@donokuda 🍕

**Comment by outofambit** [comment]
as of 096de75:
screen shot 2018-09-06 at 4 17 04 pm

**Pull request merged**
