### PR TITLE
[Added] Add Zed Preview as an external editor option

### PR DESCRIPTION
**Pull request by filiptronicek**
## Description

Recently, Zed introduced their [Preview release channel](https://zed.dev/releases/preview) along with a new app for its utilization. This PR contributes the Zed Preview editor to be used and opened from within GitHub Desktop. 

## Related issues

The regular flavor of the editor has been contributed in https://github.com/desktop/desktop/pull/16338. I have tried to keep the changelog entry & PR title similar. 

## Release notes

Notes: Add Zed Preview as an external editor option

### CODE REVIEW

**Comment by filiptronicek** [comment]
cc @JosephTLyons because you authored the original PR for adding Zed 👋

**Comment by JosephTLyons** [comment]
This is super cool! We use preview at Zed - stoked at the idea of opening it through Desktop!

**Comment by tsvetilian-ty** [comment]
Thanks for the contribution 🥳 ! I can confirm it works. @filiptronicek could you add Zed to the list with supported editors in `editor-integration.md`?

Something like:
```markdown
[Zed](https://zed.dev/) - both stable and Preview channel
```

**Comment by filiptronicek** [comment]
Should be good now, @tsvetilian-ty

**Review by tidy-dev — APPROVED** [review]
✨  Thank you for the contribution!

**Review by mervy9327 — COMMENTED** [review]
#17192

**Pull request merged**
