### PR TITLE
Changed the casing of the enums and their references

### LINKED ISSUE #7279: [Stashing] Use SentenceCase and string values for UncommittedChangesStrategy enum
This issue was brought up in https://github.com/desktop/desktop/pull/7210#discussion_r274673721.

https://github.com/desktop/desktop/blob/777c5110832a30a9cee05c32553923ec0fbf8b16/app/src/models/uncommitted-changes-strategy.ts#L1-L5

**What needs to change?**
1. Use sentence casing on each named constant
1. Use string values instead of numbers (implicit)

### PR DESCRIPTION
**Pull request by ADustyOldMuffin**
## Overview

**Closes #7279**

## Description

- The enum UncommittedChangesStrategy should have all of the values SentenceCased and set to strings to match the rest of the code base.

## Release notes

Notes: no-notes

### CODE REVIEW

**Comment by shiftkey** [comment]
@ADustyOldMuffin is there a particular reason why you closed this PR? I think this was a pretty good start to addressing the issue!

**Comment by ADustyOldMuffin** [comment]
I needed to merge the changes in the development branch into my own as it was missing a

**Comment by ADustyOldMuffin** [comment]
> @ADustyOldMuffin is there a particular reason why you closed this PR? I think this was a pretty good start to addressing the issue!

I did the wrong thing whoops! I need to pull the latest dev branch and fix the conflicts.

**Comment by shiftkey** [comment]
@ADustyOldMuffin no problem, and take your time. 

Feel free to comment here when you think it's ready to review, and we'll pull it into our queue.

**Comment by ADustyOldMuffin** [comment]
@shiftkey Alright, I believe it should be good to review!

**Pull request merged**
