### PR TITLE
Updated Error message

### PR DESCRIPTION
**Pull request by tiagodenoronha**
Fixes issue #5766

### CODE REVIEW

**Review by tierninho — COMMENTED** [review]
🚢

**Review by tierninho — APPROVED** [review]
🚢

**Comment by tierninho** [comment]
@tiagodenoronha @Daniel-McCarthy if either of you wants to work on the dynamic email / username check mentioned [here](https://github.com/desktop/desktop/issues/5766#issuecomment-425222801), feel free. Thanks!

**Review by outofambit — APPROVED** [review]

**Comment by Daniel-McCarthy** [comment]
I would be more than happy to do so, however I'd love to give @tiagodenoronha a chance to do so first if they would like to.

And congratulations on your first contribution!

**Comment by Daniel-McCarthy** [comment]
Okay, in that case I will have a pull request for this change soon.

**Comment by tierninho** [comment]
@tiagodenoronha looks like you already started? https://github.com/desktop/desktop/pull/5775

**Comment by Daniel-McCarthy** [comment]
Oh, good thing you mentioned this! I was about to submit my own as well.

**Pull request merged**
