### PR TITLE
handle "bad revision" error when starting a rebase

### LINKED ISSUE #7871: Cannot start rebase due to bad revision error
When attempting to initiate a rebase, the `Start rebase` button failed to work, ending in two console errors without notifying the user. I was playing around with LFS files in this repo as seen in the logs below, but I do not see any commits.

### Error 1:
```
install.ts:23 `git rev-list c8fb8d4517e993455b727b3dc25b272c08f6b680..origin/dsdsdffds --reverse --oneline --no-abbrev-commit --` exited with an unexpected code: 128.
stderr:
fatal: bad revision 'c8fb8d4517e993455b727b3dc25b272c08f6b680..origin/dsdsdffds'

(The error was parsed as 27: Bad revision.)
```

### Error 2:
```
Uncaught (in promise) p: Bad revision.
    at Object.t.git (file:///Applications/Beta%20Desktop.app/Contents/Resources/app/renderer.js:11:6105)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Result of `git show c8fb8d4517e993455b727b3dc25b272c08f6b680` is:
```
commit c8fb8d4517e993455b727b3dc25b272c08f6b680 (asassaaasdas)
Author: TL <tierninho@github.com>
Date:   Mon Jun 24 08:04:47 2019 -1000

    ;';'

diff --git a/100MB copy 3.zip b/100MB copy 3.zip
new file mode 100644
index 0000000..07704c3
Binary files /dev/null and b/100MB copy 3.zip differ
diff --git a/100MB copy 4.zip b/100MB copy 4.zip
new file mode 100644
index 0000000..07704c3
Binary files /dev/null and b/100MB copy 4.zip differ
(END)
```

and result of `git show origin/dsdsdffds` is:
```
➜  SM git:(dsdsdffds) git show origin/dsdsdffds
fatal: ambiguous argument 'origin/dsdsdffds': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

Screen Shot 2019-06-25 at 8 43 32 AM

2.1.0-beta1, mac

### PR DESCRIPTION
**Pull request by shiftkey**
## Overview

**Closes #7871**

## Description

This PR closes out the reported issue by:

 - handling the `BadRevision` error reported by Git in `getCommitsInRange`, and returning `null`  (rather than an empty array of commits)
 - updates callers of `getCommitsInRange` to handle this case
 - update the "Choose Branch" UI to provide context about why the user is not able to rebase this

@tierninho I've not been able to recreate this repository state on my side, so if you're able to verify this is fine UX-wise it'd be greatly appreciated.

## Release notes

Notes: `[Fixed] improved error handling when trying to rebase a ref that doesn't exist`

### CODE REVIEW

**Comment by tierninho** [comment]
> I've not been able to recreate this repository state on my side, so if you're able to verify this is fine UX-wise it'd be greatly appreciated.

Tried to recreate the error myself but no luck. I rebased the same two branches from the bug report and it succeeded. Spotted this when I selected the two branches (right before starting the rebase).

```
install.ts:27 Unable to rebase these branches because one or both of the refs do not exist in the repository
warn @ install.ts:27
getCommitsInRange @ rev-list.ts:134
_tickCallback @ internal/process/next_tick.js:68
async function (async)
getCommitsInRange @ rev-list.ts:106
startRebase @ dispatcher.ts:338
ChooseBranchDialog.startRebase @ choose-branch.tsx:358
Dialog.onSubmit.e @ dialog.tsx:342
callCallback @ react-dom.development.js:100
invokeGuardedCallbackDev @ react-dom.development.js:138
invokeGuardedCallback @ react-dom.development.js:187
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:201
executeDispatch @ react-dom.development.js:466
executeDispatchesInOrder @ react-dom.development.js:488
executeDispatchesAndRelease @ react-dom.development.js:586
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:597
forEachAccumulated @ react-dom.development.js:567
runEventsInBatch @ react-dom.development.js:728
runExtractedEventsInBatch @ react-dom.development.js:737
handleTopLevel @ react-dom.development.js:4201
batchedUpdates @ react-dom.development.js:12537
batchedUpdates @ react-dom.development.js:1939
dispatchEvent @ react-dom.development.js:4282
interactiveUpdates @ react-dom.development.js:12592
interactiveUpdates @ react-dom.development.js:1958
dispatchInteractiveEvent @ react-dom.development.js:4259
08:32:48.679 
```

If you have any tips, it would be appreciated, else I can just approve if you feel comfortable enough.  

f78ca723fb, mac

**Comment by shiftkey** [comment]
@tierninho 

> Spotted this when I selected the two branches (right before starting the rebase).

This feels like we're close to the original problem, because that output corresponds to this message:

https://github.com/desktop/desktop/blob/f78ca723fbdfa039eb09277fe138fef82d77380f/app/src/lib/git/rev-list.ts#L134-L136

What I'm curious about is whether you also saw the `Unable to start rebase. Check you have chosen a valid branch.` warning and was blocked from starting the rebase at all?

**Comment by tierninho** [comment]
> What I'm curious about is whether you also saw the `Unable to start rebase. Check you have chosen a valid branch.` warning and was blocked from starting the rebase at all?

Never received the `Unable to start rebase. Check you have chosen a valid branch.` warning. I was able to proceed with the rebase and successfully complete it.

**Comment by shiftkey** [comment]
@tierninho I'm gonna send a calendar invite for tomorrow morning your time to see if we can sit down and understand what's happening. That'll save us going back and forth in the meantime.

**Comment by shiftkey** [comment]
Just bumping this PR to indicate there's an extra case we didn't catch initially. 

In the test setup that @tierninho had in the bug report the rebase preview worked fine (because it was comparing two commit IDs), but starting the rebase tries to use the **tracking branch** for the target branch to detect if there are any remote commits (as part of the "force push" warning).

I need to update this area here to confirm the upstream is actually a valid ref, rather than assume it exists:

https://github.com/desktop/desktop/blob/f78ca723fbdfa039eb09277fe138fef82d77380f/app/src/ui/dispatcher/dispatcher.ts#L334-L353

If the upstream ref doesn't exist, we'll just do the rebase with local commits only.

**Comment by shiftkey** [comment]
@tierninho thanks for working through that with me - the last two commit should cover that case we've found. Let me know if there's anything else you spot while we're testing this "upstream missing" case...

**Comment by tierninho** [comment]
Thanks for the fix. 

Not seeing anything else at this point. All seems to be working as intended. 👍

**Pull request merged**
