### PR TITLE
styling changes for merge filter text box

### LINKED ISSUE #5998: Broken styling on merge modal
This isn't in production yet, but I noticed some funkiness on `master` on the merge modal header: 

screen shot 2018-10-25 at 10 35 27 am

It should look like this: 

screen shot 2018-10-25 at 11 53 53 am

Margin was added to `.filter-field-row` when there should be no margin, I _think_ it came from this commit: https://github.com/desktop/desktop/commit/b8a600971305c0f99ae5632de946ab883f25e05e

### PR DESCRIPTION
**Pull request by shiftkey**
## Overview

This is an alternative PR to #6015 to ensure it gets fixed in time for `1.5.0`

**Closes #5998**

## Description

- Version `1.5.0-beta1`

- This PR (updated screenshot)

## Release notes

Notes: no-notes

### CODE REVIEW

**Comment by JKirkYuan** [comment]
@shiftkey did you also want to remove the margin from the `border-bottom` property? My PR was updated yesterday and it looks like this now.

**Comment by shiftkey** [comment]
@JKirkYuan thanks for pointing out the border thing - I hadn't noticed that from the original screenshot.

On closer inspection of the original screenshot, it looks like this is what we need to do:

 - ensure the border between the filter and branch list stretches across the width of the modal
 - the filter text box should line up with the merge header (so some margin on the left and right)

But it's not clear to me how the filter text box should line up with the branches below - @ampinsk the original screenshot doesn't show things below the margin. I'll take a shot at it and see what feels right, but if you have any extra info it'd be great to hear it.

**Comment by shiftkey** [comment]
Dropping `ready-for-review` for now to dig into the proper fixes.

**Comment by shiftkey** [comment]
This is ready for another look. Unlike #6015 this change is focused on the stylings of the merge dialog, so our other filter boxes will be unaffected by this change.

**Comment by JKirkYuan** [comment]
@shiftkey this looks good! 💯 
screen shot 2018-10-31 at 7 46 43 am

**Comment by JKirkYuan** [comment]
@outofambit feel free to to close that PR!

**Comment by outofambit** [comment]
merging! thanks again for you help @JKirkYuan!

**Pull request merged**
