### PR TITLE
A temporary fix as proposed in #1646

### PR DESCRIPTION
**Pull request by Chrysaloid**
Addresses #1646. See [this comment](https://github.com/desktop/desktop/issues/1646#issuecomment-2186337511).

## Description

- Addition of **Custom User CSS**.
- Users can now create a file named `custom-user-css.css` in `\GitHubDesktop\app-3.4.1\resources\app\` and add their own CSS.

## Release notes

Notes: Addition of **Custom User CSS**

### CODE REVIEW

**Comment by niik** [comment]
Being able to provide custom CSS has been discussed before (eg https://github.com/desktop/desktop/issues/2609) and our stance on them have not changed since. 

An (albeit unsupported) workaround for this exists in that users can (and do) modify the CSS as well as the index.html with the downside of those changes disappearing when new updates gets applied (though the same would happen here since the custom-user-css.css file would be in a location that gets removed during updates).

**Comment by Chrysaloid** [comment]
I've read that issue (and also the related ones) but I don't understand what is a blocker here.

> the custom-user-css.css file would be in a location that gets removed during updates

Why is that? So what location doesn't get removed during updates? The location was just a proposal. What blocks us from specifying a safe location?

**Comment by niik** [comment]
> Why is that?

When GitHub Desktop is updated the entire application folder (i.e. ` \GitHubDesktop\app-3.4.1\` in your example) gets removed in favor of a new (say `app-3.4.2`).

> What blocks us from specifying a safe location?

There's no technical blocker here. This is just not a feature that we are comfortable adding to the project at this time. There are plenty of proposed solutions in the original issue (resizable pane, dedicated dialog etc) that we'd like to explore but as with all things it comes down to priorities.

We don't, however, believe that adding the ability to customize the CSS is a good path forward.

**Comment by Chrysaloid** [comment]
>When GitHub Desktop is updated the entire application folder (i.e.  `\GitHubDesktop\app-3.4.1\` in your example) gets removed in favor of a new (say `app-3.4.2`).

Understandable. Fortunately a relative path going 3 directories up to `\GitHubDesktop\custom-user-css.css` works.

>There are plenty of proposed solutions in the original issue (resizable pane, dedicated dialog etc)

Yes, I know. I should have specified that this is rather fix for #2609 that could work as temporary fix for #1646. My bad.

>We don't, however, believe that adding the ability to customize the CSS is a good path forward.

Why? I know what you said [here](https://github.com/desktop/desktop/issues/2609#issuecomment-327089152), but haven't you got [further along](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md) after 7 years? I did not miss the [followup comment](https://github.com/desktop/desktop/issues/2609#issuecomment-438811536) and I think that you understand that I'm not asking for GitHub-Team-made custom theme. All I'm asking is a way for everyone to tweak minor things in the app in the way they like. For me it's commit message box's height, for someone else it's the font and for the other person it's the app's colors. Who knows when those features will be implemented? Custom CSS gives users a solution now. And a solution is better then no solution.

**Pull request closed without merging**
