### PR TITLE
WIP: Add no-implicit-boolean-cast rule

### LINKED ISSUE #3538: Move away from relying on JS truthiness
See PR #3535 for more context. 

I think we should be explicit in our conditional statements instead of relying on truthiness. This should limit gotchas such as the one referenced above.

```ts
let a: ReadonlyArray<number> | null = null
let s: string | undefined = undefined

if (a) { }
if (a != null) { } //preferred

a = [0, 1, 2, 3]

if (a.length) { }
if (a.length > 0) { } //preferred
```

### PR DESCRIPTION
**Pull request by j-f1**
Fixes #3538. Eventually. I hope.

- [x] Basic implementation
- [ ] Use TypeScript’s type checker to determine variable types instead of requiring an explicit `: boolean`
- [ ] Investigate remaining error messages and add TYPES as needed
- [ ] Fix lint warnings

### CODE REVIEW

**Comment by j-f1** [comment]
This is currently blocked on getting access to the TypeScript AST node from the ESTree node I get inside the ESLint rule, so I can use the TypeScript type checker to infer variable types.

**Comment by j-f1** [comment]
I’ve PR’d that integration (https://github.com/eslint/typescript-eslint-parser/pull/415) and I’m using that version of `typescript-eslint-parser` here. There are still a few type issues that I’m trying to figure out (for example, `/foo/.test(bar)` is incorrectly typed as `any`).

**Comment by j-f1** [comment]
It turns out getting accurate T Y P E S is harder than I thought. This rule might involve a change to ESLint core.

**Comment by iAmWillShepherd** [comment]
Does TSLint not allow for this type of rule?

**Comment by j-f1** [comment]
> Does TSLint not allow for this type of rule?

It might, but:

1. I’m scheming towards eliminating TSLint at some point in the future, and
1. I’ve never used TSLint before.

**Comment by iAmWillShepherd** [comment]
> I’m scheming towards eliminating TSLint at some point in the future...

May I ask why? I'm thinking our linter should know about all types that TypeScript knows about. Right now, it seems we can't using ESLint to prevent things based on types.

**Comment by j-f1** [comment]
That’s a good point 👍, only leaving the fact that I’ve never written a TSLint rule before.

Should rewrite the rule in TSLint, or would you like to do that?

**Comment by iAmWillShepherd** [comment]
That's something I'm sure I can answer later this week. I first have to see if it's possible. Right now, I am under the assumption that it is possible.

**Pull request closed without merging**
