### PR TITLE
Upgrade Prettier to 1.14 (WIP)

### PR DESCRIPTION
**Pull request by j-f1**
I’ll comment when Prettier 1.14 is officially released and this is ready for review.

### CODE REVIEW

**Comment by shiftkey** [comment]
@j-f1 should I be worried that VSTS is complaining _on one agent_ in it's Prettier task about the YAML files that were updated in this PR?

```
2018-07-18T10:53:08.6980097Z $ ts-node script/prettier.ts
2018-07-18T10:53:38.2449297Z These files are not formatted correctly:
2018-07-18T10:53:38.2449691Z 
2018-07-18T10:53:38.2461294Z .github\config.yml
2018-07-18T10:53:38.2461553Z .github\lock.yml
2018-07-18T10:53:38.2461841Z .github\no-response.yml
2018-07-18T10:53:38.2462071Z .prettierrc.yml
2018-07-18T10:53:38.2462254Z appveyor.yml
2018-07-18T10:53:38.2462422Z circle.yml
2018-07-18T10:53:38.2462637Z script\.eslintrc.yml
2018-07-18T10:53:38.2462879Z script\electron-builder-linux.yml
2018-07-18T10:53:38.2463078Z vsts.yml
2018-07-18T10:53:38.2463209Z 
```

**Comment by j-f1** [comment]
Well, now the tests seem to have timed out :/ Can someone restart the VSTS tests?

**Comment by j-f1** [comment]
Bah, line endings.

**Comment by j-f1** [comment]
Can we just disable linting on everywhere but one job? That would probably make the CIs run faster. (plus it would make it so I don’t have to figure out what’s going wrong on Windows — but only VSTS, not Appveyor)

**Comment by shiftkey** [comment]
> Can we just disable linting on everywhere but one job?

Maybe we can revisit https://github.com/desktop/desktop/issues/2717 once I've centralized things on one group of CI platforms (VSTS or AppVeyor/Circle/Travis) but for the moment I need a 

Does the actual linting our YAML files need to be done in this PR? I see some TS/TSX changes already happening, maybe we can just upgrade Prettier and then figure out what's the matter with that VSTS build agent setup.

**Comment by kachkaev** [comment]
I created an issue for this issue with CRLF / LF in yaml files: https://github.com/prettier/prettier/issues/4956

**Comment by j-f1** [comment]
💂🏼

**Comment by shiftkey** [comment]
@j-f1 @kachkaev re-ran and everything seems fine https://github.visualstudio.com/Desktop/_build/results?buildId=4352&_a=summary&view=logs (commit status isn't propagated to here currently).

**Comment by kachkaev** [comment]
:party:

**Pull request merged**
