### PR TITLE
add support for Lite XL editor on Linux & macOS

### PR DESCRIPTION
**Pull request by KaMeHb-UA**
## Description

- Added support for Lite XL editor on Linux & macOS

## Release notes

Notes:

### CODE REVIEW

**Comment by KaMeHb-UA** [comment]
Please note that there is no **installable** builds for Windows yet so it can't be referenced

**Review by niik — CHANGES_REQUESTED** [review]
Hey @KaMeHb-UA, thanks for wanting to contribute! Would you mind adding this to the macOS and Linux sections in https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md as well?

**Comment by KaMeHb-UA** [comment]
Hi @niik, done

**Review by niik — APPROVED** [review]
Thanks @KaMeHb-UA!

**Pull request merged**
