### PR TITLE
Link to the issues sorted by least recently updated

### PR DESCRIPTION
**Pull request by joshaber**

### CODE REVIEW

**Comment by joshaber** [comment]
🏷 ⛱

**Comment by j-f1** [comment]
Could you add (maybe in a different PR) a list of the saved replies (i.e. this isn’t on our roadmap, please fill out the template etc.) that you use on this repo?

**Comment by joshaber** [comment]
We have a repo with our canned replies. It's currently private but I don't know that it really needs to be. @lee-dohm, do you have any Opinions on that?

**Comment by lee-dohm** [comment]
@joshaber I'm fine with sharing the canned replies somewhere public. I do feel that it is useful to be able to discuss and decide some aspects of our workflow privately, so I'd prefer to keep the repo itself private. I'm open to suggestions from everyone whether GitHub staff or not on how to improve our processes though!

**Comment by joshaber** [comment]
👍 I created a team for external contributors and added it to the repo. @j-f1, you should be able to see it now.

**Comment by joshaber** [comment]
#jolo

**Pull request merged**
