### PR TITLE
Add support for Pulsar code editor on macOS.

### PR DESCRIPTION
**Pull request by mdibella-dev**
## Description

Adds support for the [Pulsar ](https://github.com/pulsar-edit/pulsar) code editor on Darwin related systems (macOS).

### Screenshots

Bildschirm­foto 2023-02-27 um 18 17 21

### CODE REVIEW

**Comment by mdibella-dev** [comment]
Any chance to get a review?

**Review by tidy-dev — CHANGES_REQUESTED** [review]
Thanks for the contribution. Works as expected.  One small ask, could you please add reference to it in the [editor-integations.md under the macOs heading](https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md#macos)?

**Comment by mdibella-dev** [comment]
> Thanks for the contribution. Works as expected. One small ask, could you please add reference to it in the [editor-integations.md under the macOs heading](https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md#macos)?

Done.

**Review by tidy-dev — APPROVED** [review]
✨  Thank you for that change!

**Pull request merged**
