### PR TITLE
Add test summaries where supported by CI services

### PR DESCRIPTION
**Pull request by j-f1**

### CODE REVIEW

**Comment by j-f1** [comment]
That’s kinda useless

> Your build ran **281** tests in junit with **0 failures**
> **Slowest test:** update submodule to original commit git/submodule resetSubmodulePaths update submodule to original commit (took 0.41 seconds).

**Comment by j-f1** [comment]
Can someone cancel the Appveyor builds [#7809](https://ci.appveyor.com/project/github-windows/desktop/build/7809) and [#7810](https://ci.appveyor.com/project/github-windows/desktop/build/7810)? It looks like they’re stuck.

**Comment by shiftkey** [comment]
@j-f1 I had a chat with @nerdneha yesterday about some ideas for tracking longer-term metrics of the codebase beyond just test coverage. I'm not sure exactly what _value_ this gives us (the Appveyor one doesn't seem to be propagating the test results [here](https://ci.appveyor.com/project/github-windows/desktop/build/7811/tests), or is it somewhere else?)

Once she gets around to doing a brain-dump of her ideas, I'll make sure to point you at it.

**Comment by j-f1** [comment]
> I'm not sure exactly what value this gives us (the Appveyor one doesn't seem to be propagating the test results here, or is it somewhere else?)

The Circle support didn’t turn out nearly as nice as I’d expected, and I don’t have enough Windows-fu to get Appveyor’s support to work properly, so I’m closing this.

**Pull request closed without merging**
