### PR TITLE
Upgrade Codemirror

### LINKED ISSUE #6908: Certain TypeScript language features break syntax detection in code preview
## Description
Kept the title generic as there might be more examples of typescript features that do the same, but as far as I know there is only one: 

Using a constructor type signature to pass a class as a function parameter breaks the syntax in code preview. For example the following draft of code is adapted from a project I am working on, to make it simpler to understand why I used this feature:

```typescript

// Other color classes look like this
export class Red {
  public readonly id: number;
  private readonly store: ColorStore;
  private description: string;

  constructor(id: number, store: ColorStore, description: string) {
    this.store = store;
    this.description = description;
  }
}

export type AnyColor = Red | Blue | Yellow | Green | Purple | Orange;

export class ColorStore  {
  private _colors: AnyColor[];

  private createColor<T extends AnyColor>(type: (new (store: ColorStore, id: number, description: string) => T), id: number, description: string): T {
    const item = new type(this, id, description);
    this.addItem(item);
    return item;
  }

  public addItem<T extends AnyColor>(v: T): void {
    if (this._colors.find((x) => x.id === v.id))
      throw new Error(`The color with id ${v.id} already exists`);
    this._colors.push(v);
  }

  public getItem<T extends AnyColor>(id: number): T | undefined {
    return this._colors.find((x) => x.id === id);
  }

  public deleteItem<T extends AnyColor>(id: number): void {
    const index = this._colors.findIndex((x) => x.id === id);
    if (index < 0) return;
    this._colors.splice(index, 1);
  }
}

```

ColorStore is supposed to be an instantiable class, just imagine it with constructors. The method `createColor` uses the constructor signature from `Red` which would be the same for other colors defined in `AnyColor`. With this method the store can instantiate a new color with its specific class type and store it, all without type info loss/issues.

` private createColor<T extends AnyColor>(type: (new (store: ColorStore, id: number, description: string) => T), id: number, description: string)`

The problem is using this type of signature breaks the rest of the file in code preview. Here is a screenshot: 

Screenshot of Code Preview 

As you can see the syntax confusion becomes even more apparent when trying to use a variable in a string literal, which ends up displaying the rest of file as part of one. This makes comparing changes harder as it basically feels like viewing a text file.

## Version

* GitHub Desktop: 1.6.2

* Operating system: Microsoft Windows [Version 10.0.16299.904]

## Steps to Reproduce

1. Drop the code from the description into a new file in any repo.
2. View it in code preview.

### Expected Behavior

Proper typescript syntax detection.

### Actual Behavior

Improper detection after using a nifty language feature.

### PR DESCRIPTION
**Pull request by say25**
## Overview

Added tests to HighLighter - https://github.com/desktop/highlighter-tests/pull/34

**Closes #6908**

## Description

- Upgrade `codemirror` from `5.31.0` to `5.44.0`
- Upgrade `codemirror-mode-elixir` from `1.1.1` to `1.1.2`
- Fixes some TypeScript syntax highlights as outlined in #6908, presumably fixes other issues as well

image

## Release notes

Notes: Fixes general syntax highlighting issues? ¯\_(ツ)_/¯

### CODE REVIEW

**Comment by billygriffin** [comment]
Thanks!! This `ready-for-review` @say25?

**Comment by say25** [comment]
Yup @billygriffin, I hope this whole draft PR thing hopefully catches on soon so this isnt as up in the air 🎉

**Comment by shiftkey** [comment]
> I hope this whole draft PR thing hopefully catches on soon so this isnt as up in the air

Once our backlog of open PRs is manageable I plan to propose changes to [this document](https://github.com/desktop/desktop/blob/development/docs/process/pull-request-triage.md) about how we triage PRs to make this clearer.

**Comment by shiftkey** [comment]
Tentatively queued up for `1.7.0` because we already have #6707 on beta which we'd like to ensure is stable for the next release.

**Comment by shiftkey** [comment]
`highlighter-tests` PR has been approved and merged. Tested again locally, but I'm going to hold off on approving this to ensure it doesn't get merged before `1.6.3` is released...

**Comment by tierninho** [comment]
Played around with diffs and highlighting, and no issues thus far. Plan to give it more 👀post `1.6.3` release.

**Pull request merged**
