### PR TITLE
Ensure files marked for deletion in index are actually deleted

### LINKED ISSUE #4133: Modified Files Removed from Repo Incorrectly Committed as Modified Rather Than Deleted
### Description

Let's say you modify a config file and add a password to it. Whoops! Shouldn't be adding that to the repo! You add the config file to gitIgnore but it remains in the repo because it's already being tracked. No worries, you can just [run `git rm --cached [configFile]`](https://stackoverflow.com/a/1143800/5285364) in the command line. GitHub Desktop will correctly identify that the file is **Deleted** from the repository.

You add a helpful commit message, commit, and push.

You are then surprised to find out that GitHub Desktop did _not_ actually delete the file, but committed it as a modified file, storing the changes from the previous version. You now have sensitive information stored in your repo history and will need to [cleanse it](https://help.github.com/articles/removing-files-from-a-repository-s-history/).

Testing reveals that Visual Studio Code does not suffer from this issue (i.e. it's not something more fundamental/unsolvable). GitHub Desktop shouldn't either.

### Version

**GitHub Desktop version:** 1.1.0

**OS version:** macOS 10.13.3

### Steps to Reproduce

1. Modify a file (e.g. test.txt) but don't commit.
1. Add that file to gitIgnore.
1. Remove the file from the repo by running `git rm --cached test.txt`.
1. Verify that the file is marked for Delete in GitHub Desktop.
1. Commit the file (and gitIgnore).
1. Switch to History and notice that the file was not removed but committed as a modification.

**Expected behavior:** The file that is marked for delete and removed from the repo is committed as a deleted file, rather than committed as modified.

**Actual behavior:** The commit contains the modifications to the file, which remains in the repo.

**Reproduces how often:** 100%.

### Logs

No relevant information in logs.

#### Additional Information

None at this time.

### PR DESCRIPTION
**Pull request by iAmWillShepherd**
Fixes #4133 

### After

cc/ @shiftkey

### CODE REVIEW

**Comment by shiftkey** [comment]
@iAmWillShepherd and I paired on this earlier, and here's the root cause of the issue:

 - `git rm --cached {path}` will stop tracking the file in Git, but it results in two entries appearing in `git status` - the delete for the tracked file, and a new untracked file with the same path name
 - adding the file path to `.gitignore` does hide the new untracked file, but when we reset the index before staging the files from Desktop to commit, the delete for the tracked file is removed
 - because the file was modified before being deleted, the changes are then added to the commit by mistake

**Comment by niik** [comment]
Just a heads up that I haven't forgotten about this PR, I'm just still trying to think through the various scenarios.

**Comment by tierninho** [comment]
- [x] Tested this fix, and based on the outlined steps the expected behavior from #4133 it is working now.

**Comment by shiftkey** [comment]
:apple:

**Comment by shiftkey** [comment]
Bumping this PR because we had another report of this behaviour in #6983

**Comment by niik** [comment]
> Bumping this PR because we had another report of this behaviour in #6983

Suggesting we merge this post the 1.6.3 release.

**Comment by shiftkey** [comment]
The release branch for 1.6.3 has been cut from `development` already - #7010.

Feel free to merge this in whenever suits.

**Pull request merged**
