### PR TITLE
VS Codium support (WINDOWS ONLY)

### LINKED ISSUE #8000: support VS Codium as external editor
VS Codium is based on VS Code, the only differences being VS Codium is VS Code without MS branding/telemetry/licensing

### PR DESCRIPTION
**Pull request by Rexogamer**
## Overview

**Closes #8000**

## Description

-Adds VS Codium support. Note: not complete and I’m away from PC for a month so unable to continue.

## Release notes

Notes: Add support for VS Codium on Windows

### CODE REVIEW

**Comment by outofambit** [comment]
hi @Rexogamer thanks for starting on this! since you're going to be away for a while, i'm going to close this PR, but please reopen it or comment here when you're ready to continue. thanks!

**Comment by Rexogamer** [comment]
Sounds good

**Comment by Rexogamer** [comment]
After some help, it’s done. @outofambit, can you repopen?

**Comment by Rexogamer** [comment]
I might as well just make a new PR.

**Comment by Rexogamer** [comment]
Moved to #8163.

**Pull request closed without merging**
