### PR TITLE
add some missing keyboard shortcuts

### LINKED ISSUE #3327: Keyboard shortcuts for branch operations
Would it be possible to create some keyboard shortcuts for these two menu items?

image

I use them quite frequently and it'd be nice to have a shortcut for them 👍

### PR DESCRIPTION
**Pull request by say25**
Fixes #3327 

- Merge Into Current Branch - `CmdOrCtrl+Shift+M`
- Update From Default Branch - `CmdOrCtr+Shiftl+U`

### CODE REVIEW

**Comment by shiftkey** [comment]
Going to let this sit for a bit and confirm @desktop/core has no objections with the chosen keyboard shortcuts - once people start using these, they will probably not like us changing them without some really good reasons.

**Comment by say25** [comment]
Totally fair. Couldn’t come with anything better personally. Didn’t know if adding `Shift` made sense or not if `M` and `U` could have other meanings going forward

**Comment by joshaber** [comment]
I'd lean towards adding `Shift` so we can save the other shortcuts for more common actions.

**Comment by say25** [comment]
I shall add Shift

**Comment by iAmWillShepherd** [comment]
I'm cool with these.

**Comment by shiftkey** [comment]
I think this has had enough eyeballs. Thanks @say25!

**Pull request merged**
