### PR TITLE
Support ML Like

### PR DESCRIPTION
**Pull request by say25**
- Ocaml
- F#

Goes hand in hand with https://github.com/desktop/highlighter-tests/pull/6

### CODE REVIEW

**Comment by say25** [comment]
It feels like adding to the Markdown file is going to get long. Maybe it should be its own file as the list will continue to grow?

**Comment by shiftkey** [comment]
@say25 yeah, I'm open to ideas about how to manage these better.

cc @agisilaos

**Comment by say25** [comment]
I feel like the way to do it is make a `highlighter-supported-languages.md` file referenced from the the current markdown file. With a compressive list. I’m more than happy to make the change.

**Comment by say25** [comment]
@shiftkey: I feel like the way to do it is make a `highlighter-supported-languages.md` file referenced from the the current markdown file. With a compressive list. I’m more than happy to make the change.

**Comment by agisilaos** [comment]
I really like this idea @say25! Would love to know what @niik has to say about it.

**Comment by niik** [comment]
> I really like this idea @say25! Would love to know what @niik has to say about it.

I agree that the list is long and detracts from the rest of the document now though I feel like that's just a presentation issue. Since syntax highlighting is already a dedicated document it feels odd to split it out into a separate file containing just a list. What if we instead converted the list to inline text?

screen shot 2017-11-23 at 08 43 10

**Comment by agisilaos** [comment]
That's a better idea! Let's keep the docs to a minimum and go with the inline text! Looks good to me! 👍

**Comment by say25** [comment]
Sounds good @niik any advantage to showing file extensions supported per language?

**Comment by NGsolution** [comment]
Appove @NGsolution

**Pull request merged**
