### PR TITLE
[Stashing] Address button order of stash diff viewer for Windows

### LINKED ISSUE #7273: [Stashing] macOS button order is incorrect
This issue was brought up in review of https://github.com/desktop/desktop/pull/7210#discussion_r274839393. 

https://github.com/desktop/desktop/blob/686fbbc04f9b2c229ad98799dd0c4d63c8df5d01/app/src/ui/stashing/stash-diff-viewer.tsx#L1

> 🎨 can we add some context here about why we've needed to do this?

> I concur, especially since I believe that through subverting this rule we've created the wrong order on Windows. I'll comment about that below.

Let's do a bit of validation here to see if this gives the wrong order on Windows. If so, we need to yank this rule and follow our current conventions.

### PR DESCRIPTION
**Pull request by outofambit**
Fixes #7273

**macOS**
macOS

**Windows (before)**
Windows-Before

**Windows (after)**
Windows-After

☝️ is the same as before...

### CODE REVIEW

**Comment by outofambit** [comment]
hey @niik i took a quick stab at this, is this what you had in mind?

**Comment by iAmWillShepherd** [comment]
@niik there is no difference in the UI made after the reorder. Is this because one of the buttons is a submit button within the `ButtonGroup` component? I think the `ButtonGroup` is responsible for ordering the buttons, so I'm not sure if this PR is needed other than to follow our conventions.

**Comment by outofambit** [comment]
[I fought the law and the law won!](https://tvtropes.org/pmwiki/pmwiki.php/Main/IFoughtTheLawAndTheLawWon)

**Comment by shiftkey** [comment]
> Is this because one of the buttons is a submit button within the `ButtonGroup` component? I think the `ButtonGroup` is responsible for ordering the buttons, so I'm not sure if this PR is needed other than to follow our conventions.

@iAmWillShepherd @outofambit the missing piece to this change is the `destructive` prop on `ButtonGroup`. From the docs:

https://github.com/desktop/desktop/blob/5b774b11af24dbf5b1ed1dafeaf43e5b73750b6b/app/src/ui/lib/button-group.tsx#L4-L11

**Pull request merged**
