### PR TITLE
Reinstate missing illustration and fix blankslate illustration to work in the dark theme

### LINKED ISSUE #6894: Missing blankslate image on compare page
I am seeing a missing blankslate image on the compare tab if the behind/ahead = 0.

image

1.6.3-beta1, mac

### PR DESCRIPTION
**Pull request by niik**
## Overview

**Closes #6894**

## Description

This fixes a mistake I did when implementing the no-changes blankslate where I thought I had removed the last usage of a particular blankslate illustration.

image

This.. was not the case. So I've brought that back and while I was dealing with SVGs I updated the paper-stack illustration we use on the blankslate to work in the dark theme as well.

#### Before

image

#### After

image

## Release notes

Notes: 
`[Fixed] Missing image when comparing branches`
`[Improved] Improved graphic in the suggested changes view to work better in the dark theme`

cc @tierninho

### CODE REVIEW

**Comment by shiftkey** [comment]
Adding the "no commit selected" view in for completeness:

**Comment by tierninho** [comment]
LGTM 🥇tested in 1140b533d9, mac.

**Comment by say25** [comment]
There isnt supposed to be a dark ? mark in the dark mode svg?

**Comment by shiftkey** [comment]
@say25 good spot!

**Comment by niik** [comment]
Given that I’m out and that the question mark issue was pre-existing ever
since we introduced the dark them (as well as when we used it in the
no-changed blankslate) I propose that unless there’s any other comments on
this change we merge it as-is.

**Comment by shiftkey** [comment]
Extracted the `?` problem to https://github.com/desktop/desktop/issues/6915 for someone else to pick up, rather than holding up the PR completely.

**Pull request merged**
