### PR TITLE
remove merge conflict dialog feature flag

### PR DESCRIPTION
**Pull request by outofambit**
## Overview

#6184 (for merge conflict resolution)

## Description

-

## Release notes

(not user facing)

### CODE REVIEW

**Comment by shiftkey** [comment]
Dropping `ready-for-review` because there are outstanding conflicts

**Comment by iAmWillShepherd** [comment]
I was initially going to fix this, but I am no longer sure how we track a files conflict state. We used to use the `AppFileStatusKind` type to delineate between files that had conflicts and used it return an `AbortMergeWarning`. Now that we have removed the `AppFileStatusKind.Resolved` enum value, I'm not sure which value to use instead.

**Comment by billygriffin** [comment]
@iAmWillShepherd let's go ahead and leave this one until @outofambit is back from OOO then if that seems ok.

**Comment by outofambit** [comment]
ready! @iAmWillShepherd 🍏

**Pull request merged**
