### PR TITLE
bail out of rendering a remote action in the NoChanges view after a rebase

### LINKED ISSUE #6990: "pull branch" blank slate action needs to be aware of force push
Found this bit of inconsistent UX while testing #6981:

Two ideas come to mind about addressing this:

 - we hide the blank slate action, because with great power comes great responsibility
 - we update this blank action to be aware a force push is permitted, and explain more about what will happen

### PR DESCRIPTION
**Pull request by shiftkey**
## Overview

**Closes #6990**

## Description

In #6990 we decided to hide the remote action if the branch had been rebased, to avoid encouraging the user to pull in the remote commits again and messing up their rebased branch.

We have plans post `1.7.0` to iterate on this area and see if we can provide more helpful context after the rebase is completed, but for now we want to keep things simple.

## Release notes

Notes: no-notes

### CODE REVIEW

**Comment by outofambit** [comment]
do we also need to disable this action in the system menu?

**Comment by shiftkey** [comment]
@outofambit 

> do we also need to disable this action in the system menu?

This has been an ongoing discussion over the last couple of weeks the latest things on our roadmap are:

 - post-MVP - ensure `Force Push` is shown to users in the menu if the push/pull button will force push - #7138
 - some time later - audit which menu items should be enabled when dealing with conflicts - #7017

The reason why we're not specifically looking at disabling menu items now is that this is still a possible thing that you can do from the command line, and we'd like to take a step back and look at these flows more broadly to decide what things should be enabled/disabled.

**Comment by outofambit** [comment]
> This has been an ongoing discussion over the last couple of weeks the latest things on our roadmap are:

thanks @shiftkey! this is super helpful! sounds good.

**Comment by shiftkey** [comment]
I'll also call out that we're contemplating having a remote action for this "force push after rebase" but we're holding off on diving into that until we get feedback about the current designs to determine how to iterate on things post-ship.

**Comment by shiftkey** [comment]
@outofambit I'm going to merge this in a bit early to keep on top of landing things for the next beta

**Pull request merged**
