### PR TITLE
Linted the files according to the .prettierrc.yml

### PR DESCRIPTION
**Pull request by Harry-Hopkinson**
Closes #N/A

## Description

Notes:
prettier --config ./.prettierrc.yml  --write "./**/*.ts"
prettier --config ./.prettierrc.yml  --write "./**/*.tsx"

### CODE REVIEW

**Review by junioryo — COMMENTED** [review]
BE NICE

**Comment by Harry-Hopkinson** [comment]
What do you mean by this comment?

**Comment by junioryo** [comment]
Just be nice

**Comment by junioryo** [comment]
Hey

**Comment by junioryo** [comment]
What is this app

**Comment by niik** [comment]
Hey @Harry-Hopkinson, thanks for opening this. Given that this also necessitates an upgrade of our bundled prettier (that's why the build is failing here) and that this will introduce a bunch of merge conflicts for our currently open PRs I'm going to close this and open a new one so that we can coordinate internally to minimize merge conflicts. I'll make sure to attribute you as a co-author though!

**Pull request closed without merging**
