### PR TITLE
Move Contributing to .github folder

### PR DESCRIPTION
**Pull request by say25**
I've seen this convention around. Not sure if its the best one. Also haven't seen a full list of the special supported files that can live in `.github` online (maybe one of your can bump the Github team to make a wiki doc in the spirt of https://github.com/blog/2392-introducing-code-owners)

### CODE REVIEW

**Comment by shiftkey** [comment]
@say25 don't forget all the markdown files that link to the `CONTRIBUTING.md` file!

**Comment by say25** [comment]
@shiftkey will address that. Do you know of any other files that could/should live inside the `.github` folder? Im trying to learn from a more experienced Github staffer like yourself with regards to how the magic folder works

**Comment by shiftkey** [comment]
@say25 I'm tracking #3959 which is a new file for support resources, and various [Probot](https://probot.github.io/) extensions use this folder to track their metadata files.

I wouldn't worry about adding more to this PR for now, but as I find more resources that are relevant to Desktop I'll open issues to track them here.

**Comment by shiftkey** [comment]
@say25 there's also a link to the `CONTRIBUTING.md` file in `docs/README.md` that needs to be updated

**Comment by shiftkey** [comment]
@say25 well, aside from the merge conflict that's been introduced - sorry!

**Comment by shiftkey** [comment]
@say25 thanks!

**Comment by say25** [comment]
@shiftkey in the same vein how do you feel about moving README.md to the .github folder?

**Comment by shiftkey** [comment]
@say25 I'm less enthusiastic about doing that move.`README.md` at the root is more discoverable for people who aren't looking at the repository on GitHub.

**Comment by say25** [comment]
@shiftkey sounds great. Will not move it 👍

**Pull request merged**
