### PR TITLE
History Graph in comparison view

### LINKED ISSUE #1634: Feature Request: Graph history view
Just testing the waters on this one but, one thing that I'm missing from all of the more 'advanced' clients is essentially `git log --graph`.

This would just display all branches in one history view, with a nice little DAG graph showing how the repo fits together.

Pretty much like this:
image
(Taken from Stack Overfloew: http://stackoverflow.com/a/9074343)

image
(SourceTree)

### PR DESCRIPTION
**Pull request by hottestchilipepper**
Closes #1634

## Description
I implemented ''History Graph" in comparison view.
You should select comparison branch in history view. Then you can see the 'Graph' button.
This is not a full graph according to #1634, it will show you only 2 branch's graph.

### Screenshots
K-041
K-040
K-037
K-036

## Release notes
History Graph in comparison view.

Notes:

### CODE REVIEW

**Comment by outofambit** [comment]
@hottestchilipepper I recognize this is (also) a lot of work, but I was surprised to see this PR because our team hasn't had a conversation with you to confirm that this is a feature we want to add now. I know the issue you linked (#1634) is locked, so it’s okay to open a new issue and share your perspective in a constructive manner — like explaining what your needs/problems are and even sharing a lightweight example of something that would help you and why. Thanks!

**Comment by gigabyteservice** [comment]
having a graph is a really important thing, why this PR is closed! it's 1 year since we are waiting for this feature

**Comment by jaxor24** [comment]
Need this feature.

**Comment by maddada** [comment]
This is a must have feature, please add it!

**Comment by carljustineoyales** [comment]
any updates to this feature?

**Comment by 201flaviosilva** [comment]
Please don’t let it die, I really need this :)

**Comment by NooP1989** [comment]
Whats your Problem to add this full Feature!? People asked for it since 2017 ([#1634](https://github.com/desktop/desktop/issues/1634)) and no productive solution to date. Do you need more programmers?

**Pull request closed without merging**
