### PR TITLE
fix url of show user guide link

### PR DESCRIPTION
**Pull request by IkerCelorrio**

### CODE REVIEW

**Comment by tierninho** [comment]
thanks for the PR @IkerCelorrio but it looks to have been already fixed here: https://github.com/desktop/desktop/pull/2793

**Comment by shiftkey** [comment]
@IkerCelorrio thanks, but I think #2793 is also the same fix - and that's under review right now.

**Comment by IkerCelorrio** [comment]
@shiftkey  ouch! so sorry /cc @tierninho

**Comment by shiftkey** [comment]
@IkerCelorrio no problem!

**Pull request closed without merging**
