### PR TITLE
Hover states on list items and tabs

### PR DESCRIPTION
**Pull request by ampinsk**
## Overview

Fixes https://github.com/desktop/desktop/issues/5030

This adds a hover state to all list items in both light and dark mode:
- Uncommitted changes
- Commit history
- File list
- Repo list
- Branches list

And to tabs in:
- Changes panel
- Branches panel

Light mode:

hover-state-list

Dark mode:

hover-state-dark

The only problem I've run into and can't figure out how to address is the hover style is also applied to these header items:

screen shot 2018-11-28 at 4 09 19 pm

### CODE REVIEW

**Comment by ampinsk** [comment]
@billygriffin Using the hand pointer felt a little too webby to me, but I don't feel super strongly about it. 😄

**Comment by billygriffin** [comment]
@ampinsk That seems fine. I have a personal preference for the hand pointer, but I just tested 7 different apps on macOS and 4 of 7 used the hand pointer and 3 of 7 used the regular cursor. I think I just like it because it makes it obvious/explicit when you're over something clickable, but I also don't feel strongly so I will defer to your judgment. 😄

**Comment by j-f1** [comment]
For the headers, you could set `pointer-events: none` on them to prevent any interaction.

**Comment by ampinsk** [comment]
@niik and I paired on fixing this! Should be ready to go now 👍

**Comment by tierninho** [comment]
Changes look good. Overkill to add hover here?

screen shot 2018-11-30 at 10 21 11 am

**Comment by ampinsk** [comment]
@tierninho hmm the hover state should be already working there!

**Comment by tierninho** [comment]
@ampinsk Yep, you are right! Not sure why it didn't show for me, but now it works fine.

**Comment by outofambit** [comment]
merging this early so we can have it in for the beta

**Comment by hdsantos89** [comment]
Thanks! So happy to see it on the changes readme!

**Pull request merged**
