### PR TITLE
Solve #14286

### LINKED ISSUE #14286: Min-width problematic on some screens
### Search existing issues

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the problem I am experiencing.

### The problem

The app has a (quite bit) min-width which is problematic on some screens (for instance, if you have a vertical monitor).
I think this large min-width is not really needed.
It is extremely annoying that to close (or minimise) the app you have to drag the window in order to show the button on the top right.

### Release version

Any recent version (for instance, 2.9.12)

### Operating system

Irrelevant (but in Windows is extremely evident)

### Steps to reproduce the behavior

1. Open GitHub Desktop
2. Try to resize the window

### Log files

_No response_

### Screenshots

_No response_

### Additional context

Before you could at least maximise the window and get the right size (#10097). But, unfortunately, this seems to be "fixed" now.

### PR DESCRIPTION
**Pull request by daniporr**
Closes #14286

## Description

- Use a "less problematic" value for `min-width` and `min-height`

### Screenshots

This depends on the size of your screen.

Moreover, this just affects the minimum size that you can get when you resize the window.

## Release notes

Notes:

### CODE REVIEW

**Comment by tidy-dev** [comment]
👋 @daniporr I understand your frustration with the current app minimum dimensions and thank you for wanting to improve GitHub Desktop. However as explained https://github.com/desktop/desktop/issues/1702#issuecomment-312952005, those dimensions were picked intentionally. Since that decision, we have added numerous features that have been made to respect those minimum dimensions and would need revisited in order respond and still properly function with smaller minimum dimensions. This work is not in scope at this time; therefore, I am closing this pull request until it is agreed upon work by the Desktop team.

**Comment by daniporr** [comment]
Thank you for your answer.

I hope this problem will be considered by the Desktop team in the near future (as you mentioned, it is a very old problem).

**Comment by daveycodez** [comment]
Bump. Fix it.

**Comment by DoctorDerek** [comment]
Still a problem

**Pull request closed without merging**
