### PR TITLE
generate HTML bundle of coverage stats by default

### PR DESCRIPTION
**Pull request by shiftkey**
## Overview

Working on #6125 and adding some more tests, I find myself tweaking the jest config so I can look at a the details of the coverage for the test run.

Currently you only see the summary in the console, and a JSON bundle is generated with CI builds.

```
=============================== Coverage summary ===============================
Statements   : 29.62% ( 5024/16960 )
Branches     : 14.44% ( 1165/8068 )
Functions    : 16.48% ( 582/3531 )
Lines        : 29.77% ( 4988/16753 )
================================================================================
```

This is great for seeing the overall details, but I want to dig into the areas I'm working on and track what they're coverage looks like.

## Description

With this change, after running `yarn test:unit:cov` locally you'll see a `coverage` folder on disk:

```
$ ls coverage
base.css		index.html		models			sort-arrow-sprite.png
block-navigation.js	lib			prettify.css		sorter.js
coverage-final.json	main-process		prettify.js		ui
```

If you open `coverage/index.html` you'll see the detailed stats, and can click into the relevant area of the codebase you're interested in:

## Release notes

Notes: no-notes

### CODE REVIEW

**Comment by shiftkey** [comment]
Marking this as `time-sensitive` because I depend on it for #6125 which I'd like feedback on to ensure it's on the right track for 1.5.1.

**Comment by j-f1** [comment]
Why not use [Codecov&rsquo;s view](https://codecov.io/gh/desktop/desktop/compare/4d7bff2ec89a934acfd0636ac48a7f02b0ec1278...08700aba9cda4c440d8e50f3cae4770cb2b88aac) instead?

**Comment by shiftkey** [comment]
@j-f1 because that feedback loop requires me to push changes to a remote, and wait for the builds to then publish stats to CodeCov. I want a faster feedback loop than that.

**Comment by outofambit** [comment]
i’m going to merge this now and unblock #6125

**Pull request merged**
