### PR TITLE
Update Node.js to v12.14.1

### PR DESCRIPTION
**Pull request by rafeca**
This is the same version as used by electron v9

### CODE REVIEW

**Comment by niik** [comment]
@rafeca what happened here, don't we want to update the node version on CI?

**Comment by rafeca** [comment]
> @rafeca what happened here, don't we want to update the node version on CI?

uhm good question! I didn't close this PR! (even if GitHub says so 😅)

I think it got automatically closed once https://github.com/desktop/desktop/pull/9680 got merged and the `spike/actions-win32` branch got deleted (at least the timestamps of the events match: the branch got deleted at [`2020-08-11T16:35:30Z`](https://github.com/desktop/desktop/pull/9680#event-3644047775) and this PR got closed at [`2020-08-11T16:35:33Z`](https://github.com/desktop/desktop/pull/10364#event-3644047974)).

I'm going to change the target branch of the PR and reopen it

**Comment by rafeca** [comment]
> I'm going to change the target branch of the PR and reopen it

LOL it was not possible to change the target branch of the PR while it was closed, so this is what I had to do:

1. Restore the `spike/actions-win32` branch from https://github.com/desktop/desktop/pull/9680 to be able to reopen this PR.
2. Reopen this PR.
3. Change the target branch of this PR.
4. Delete again the `spike/actions-win32` branch from https://github.com/desktop/desktop/pull/9680

**Comment by niik** [comment]
Huh, weird! I wonder if this is something we'll experience more of now that we've turned on branch auto-delete or if it was just a temporary blip.

**Comment by rafeca** [comment]
> Huh, weird! I wonder if this is something we'll experience more of now that we've turned on branch auto-delete or if it was just a temporary blip.

I think it has to do with the fact that this PR was created from a fork

**Pull request merged**
