### PR TITLE
introduce distinct issue templates

### PR DESCRIPTION
**Pull request by shiftkey**
[Improved issue templates](https://blog.github.com/2018-05-02-issue-template-improvements/) was just made available to everyone, and I wanted to take this opportunity to see if we can improve how we get feedback for Desktop by introducing two templates:

 - a bug report template - what we know and have been working with for ages
 - an enhancement template - a simpler, free-form template to gather ideas

I'm going to look around for some examples of good enhancement templates, and I'm open to ideas from others about good ones they've seen elsewhere.

 - [x] introduce a good enhancement template for Desktop
 - [x] remove old `ISSUE_TEMPLATE.md`

I might need to look at a subsequent PR to address the docs usage - it's not clear to me from the GitHub docs how to refer to a specific template in the URL. Let me know if you've spotted this already.

### CODE REVIEW

**Comment by agisilaos** [comment]
@shiftkey I found an interesting one for a good enhancement template. [babel](https://github.com/babel/babel) started to use this one recently. Here's the link to the [template](https://github.com/babel/babel/blob/master/.github/ISSUE_TEMPLATE/Feature_request.md) and how it looks like:

screen shot 2018-05-04 at 02 01 18

**Comment by shiftkey** [comment]
@nerdneha I'm :thumbsup: to introducing an "magnitude of pain" question to the bug report template. We can iterate on that after this lands as I just wanted to see if we can make it easier to distinguish those from enhancement requests.

**Comment by shiftkey** [comment]
I took the Babel template that @agisilaos suggested, tweaked it a bit to suit what I think we're interested in, and added some emoji because ✨✨✨✨✨. If we're happy with that new template, I'm happy to try this out and refresh the docs in a follow-up PR.

**Comment by shiftkey** [comment]
> I'll see if I messed up the formatting somehow.

I think what you're seeing in the rich diff isn't quite "what you'd see on the site" because of all these sections in the diff indicating added/changed/removed text (seems to be focused on paragraphs separated by whitespace).



I copy-pasted the text into a new issue and it looks fine when previewed there:

**Comment by nerdneha** [comment]
@shiftkey 🙇‍♀️ LGTM. 🗞

**Pull request merged**
