### PR TITLE
Beta release of RBB lite and multi-select lists

### PR DESCRIPTION
**Pull request by niik**
After discussing with @nerdneha earlier today we decided that shipping RBB lite and multi-select to beta was the easiest way to get mileage on the changes as well as deliver updates to QA.

There was some concerns earlier about potential stability issues but our (my) take on this is that we'll accept some risk on the beta channel, that's what it's there for. Our need for mileage is high enough that it's important for us to get this to the beta channel as soon as possible.

### CODE REVIEW

**Comment by nerdneha** [comment]
Looks like lines 7 and 8 are the same; I’m not in front of my computer right now but I can push and update if you’re clocked out for the week

**Comment by niik** [comment]
Cheers, that’d be great. I’m not too concerned since I don’t believe
there’s a way to view the beta release notes anyway

**Comment by shiftkey** [comment]
> I’m not too concerned since I don’t believe
there’s a way to view the beta release notes anyway

Yep, this is being tracked in #3385

**Comment by nerdneha** [comment]
I think we didn't merge it just in case we wanted to rollback easily and just release master to beta. Things seems to be good now though, happy to merge

**Comment by shiftkey** [comment]
@nerdneha it's be easy enough to revert #4522 and push a new beta update if we wanted to rollback the RBB changes for whatever reason.

**Pull request merged**
