### PR TITLE
Use macos-13-xl-arm64 M1 runner

### PR DESCRIPTION
**Pull request by tidy-dev**
Known constraint -> Uses Node 16 which we already do.

### CODE REVIEW

**Review by sergiou87 — APPROVED** [review]
Yay!!! 🚀 💖

**Comment by chevette17** [comment]
17137

**Comment by chevette17** [comment]
71f61fe7fcda6c4adefe0f0f7b62024927b43db9

**Comment by niik** [comment]
So previously we had it set such that we [would only run tests when the actual architecture matched the target arch](https://github.com/desktop/desktop/pull/9691#issuecomment-623895754). Now we are running on native arm (on macOS) but we still only run tests in x64. Should we change it so that we only run tests on macOS/arm and Windows/x64?

**Comment by tidy-dev** [comment]
Ah. I wondered why we only did it on the x64 builds.  It seems that in the reference issue indicates the tests failed for arm64 when not running on an arm64 windows machine. This does not seem to be the case for macOS. What is the benefit of switching?

**Pull request merged**
