### PR TITLE
Set node version to 8.5.0

### PR DESCRIPTION
**Pull request by donokuda**
Bumps the local node version to 8.5.0 for those using [nodenv](https://github.com/nodenv/nodenv)

### CODE REVIEW

**Comment by shiftkey** [comment]
@donokuda is there any particular reason why we shouldn't just go up to 8.9.3 (the current LTS version)?

**Comment by shiftkey** [comment]
Also, see my tears over in #3556

**Comment by donokuda** [comment]
> @donokuda is there any particular reason why we shouldn't just go up to 8.9.3 (the current LTS version)?

I didn't even realize 8.9.3 was out (and also LTS.) I'm so behind the times 😭 

> Also, see my tears over in #3556

😭 😭 😭 

Also looks like 8.9.3 hasn't been added to nodenv yet...

```
donokuda$ nodenv install --list
Available versions:
  0.1.14
  0.1.15
  0.1.16
 [...]
  8.0.0-rc.0
  8.0.0
  8.0.0-rc.1
  8.0.0-rc.2
  8.1.0
  8.1.1
  8.1.2
  8.1.3
  8.1.4
  8.2.0-rc.1
  8.2.0
  8.2.1
  8.3.0-rc.0
  8.3.0
  8.4.0
  8.5.0
  8.6.0
  8.7.0-rc.1
  8.7.0-rc.2
  8.7.0
  8.8.0
  8.8.1
  8.9.0
  8.9.1-rc.1
  8.9.1
  8.9.2-rc.1
  8.9.2
  9.0.0-rc.0
  9.0.0
  9.1.0
  9.2.0
[...]
```

**Comment by shiftkey** [comment]
@donokuda `8.9.2` should be fine - this only affects the tooling dependencies - the actual application dependiencies are compiled against our version of Electron, which is pinned in `app/.npmrc`.

**Comment by donokuda** [comment]
> @donokuda 8.9.2 should be fine - this only affects the tooling dependencies - the actual application dependiencies are compiled against our version of Electron, which is pinned in app/.npmrc.

👍 Ah, good to know. I bumped it to 8.9.2.

**Pull request merged**
