### PR TITLE
Try updating electron-winstaller

### PR DESCRIPTION
**Pull request by joshaber**

### CODE REVIEW

**Comment by joshaber** [comment]
Creating the diff didn't fail—it looks like the failure was fixed in https://github.com/Squirrel/Squirrel.Windows/pull/1087—but the delta is ~3x bigger than it has been historically:

screen shot 2017-11-20 at 1 35 21 pm

@desktop/core Maybe that bigger delta is worth it to be up to date? Maybe? Thoughts?

**Comment by shiftkey** [comment]
@joshaber poking at [the previous delta package](https://gist.github.com/shiftkey/990f4ddd0dbb5edaad7c35d29f70b3f7) and this one seem fine.

```
$ unzip -Z -t GitHubDesktop-1.0.10-beta0-delta.nupkg
3155 files, 89136 bytes uncompressed, 74410 bytes compressed:  16.5%

$ unzip -Z -t GitHubDesktop-1.0.10-beta1-delta.nupkg
3261 files, 2833434 bytes uncompressed, 1117161 bytes compressed:  60.6%
```

Rubbing some grep on the non-zero archive contents shows `squirrel.exe` being updated, which fits with what we'd expect (binary diff probably don't compress well compared to text):

```
$ unzip -Z GitHubDesktop-1.0.10-beta1-delta.nupkg | grep -v "0 b" | grep "defN" 
-rw-a--     6.3 fat     7345 bx defN 17-Nov-20 17:52 lib/net45/GitHubDesktop.exe.bsdiff
-rw-a--     6.3 fat   226591 bx defN 17-Nov-20 17:50 lib/net45/resources/app/crash.js
-rw-a--     6.3 fat   932346 bx defN 17-Nov-20 17:50 lib/net45/resources/app/crash.js.map
-rw-a--     6.3 fat   162553 bx defN 17-Nov-20 17:50 lib/net45/resources/app/main.js
-rw-a--     6.3 fat   582614 bx defN 17-Nov-20 17:50 lib/net45/resources/app/main.js.map
-rw-a--     6.3 fat      432 bx defN 17-Nov-20 17:50 lib/net45/resources/app/package.json
-rw-a--     6.3 fat     2162 bx defN 17-Nov-20 17:53 lib/net45/resources/app/renderer.js.bsdiff
-rw-a--     6.3 fat     1705 bx defN 17-Nov-20 17:53 lib/net45/resources/app/renderer.js.map.bsdiff
-rw-a--     6.3 fat   303932 bx defN 17-Nov-20 17:50 lib/net45/resources/app/static/licenses.json
-rw-a--     6.3 fat   458546 bx defN 17-Nov-20 17:53 lib/net45/squirrel.exe.diff
-rw-a--     6.3 fat      672 bx defN 17-Nov-20 17:50 package/services/metadata/core-properties/ea88a020e54e4939b4e6a21ad2be25f9.psmdcp
-rw-a--     6.3 fat    15159 bx defN 17-Nov-20 17:53 [Content_Types].xml
-rw-a--     6.3 fat      498 bx defN 17-Nov-20 17:50 _rels/.rels
```

**Comment by shiftkey** [comment]
I think the only blocker on merging this in is that a Squirrel update (probably https://github.com/Squirrel/Squirrel.Windows/pull/1061) means our splashscreen loading GIF now looks squashed and aliased:

**Comment by niik** [comment]
> I think the only blocker on merging this in is that a Squirrel update (probably Squirrel/Squirrel.Windows#1061) means our splashscreen loading GIF now looks squashed and aliased:

Ouch, that looks really bad. Is there anything I could do on our end to create a GIF which doesn't look terrible? If not I think that's a showstopper

**Comment by shiftkey** [comment]
@niik maybe some upscaling of the GIF to 2x size would help? I'm not quite sure how painful that is for you to put together with the animation, but I can help test it on the various OSes and see if that fixes it

**Comment by iAmWillShepherd** [comment]
What issue does this PR address? Also, is it still an issue?

**Comment by shiftkey** [comment]
@iAmWillShepherd the context for this is https://github.com/desktop/desktop/pull/3349#issuecomment-345070596.

We've been able to workaround the issue on the server-side, and we'll have to do that while clients run versions of Desktop that contain Squirrel.Windows versions that support old versions of TLS. I _think_ this will be fine to merge if we can fix the installer GIF issue.

**Comment by damieng** [comment]
Apart from the squished splash the icon on the task bar is also wrong and alpha is no longer supported...

**Comment by shiftkey** [comment]
Closing this out as it looks like we've got to contribute some things to address upstream before we should upgrade ourselves here.

**Comment by damieng** [comment]
I've actually updated Squirrel and Electron-Winstaller.  It is now using WPF again so the alpha, dragging, task bar and dpi are now correct again.

This does mean it's not as efficient as the WinForms GIF image rendering in terms of memory usage so you might want to use a smaller version rather than the 160 frame one.  (There were some memory improvements in the WpfAnimatedGif upgrade but it's still quite high - it unpacks every frame and then seems to duplicate it a few times through the various Wpf layers)

**Comment by shiftkey** [comment]
@damieng 💖💖💖 I'll put this on my plate for this week to revisit - we were already aware of the GIF issue and had a simpler GIF in place because of the issue with WPF and GIF rendering.

**Pull request closed without merging**
