### PR TITLE
[WIP] LFS File Locking

### PR DESCRIPTION
**Pull request by chasse20**
#8419

## Description

This PR includes base functionality for GIT-LFS file locking. This was a very popular request by people (especially those in the game industry) and hopefully this can satisfy that. Some further development is needed to satisfy MVP functionality. Please refer to the Outstanding Task list below along with the Known Issues section.

### Outstanding Tasks
- [x] Progress feedback for the LFS network action of getting/setting locks
- [x] Better offline handling for file locking (including disablement)
- [x] Option to automatically release owned locks on commit
- [x] Include as part of Github Desktop's feature flagging system
- [x] Disable ability to lock a file that is not added to the repo; should be able to force unlock files that somehow made it past that check
- [ ] Add toggle for `lfs.setlockablereadonly` (defaults to off to support game-friendly pipeline until I get a chance much later on to add an Explorer tab)
- [ ] Address memory leakage

There is a major memory leak issue that happens when calling LFS commands from Node whenever a user is not authenticated. **I would appreciate any help from the core development team from Github Desktop to resolve it.** Steps for replication: create a repository, delete the credentials associated with it, and then cause it to refresh the lock statuses (focus/unfocus the window). Hanging processes will be present even when the application is closed.

## Screenshots

LFS_PR_1
LFS_PR_2
image

## Release notes

- Detects if file locking is supported on a repository
- Runs periodic check of file lock status
- File lock UI feedback in Changes view (the lock icon and context menu)
- File lock UI feedback in Compare view (lock icon)
- Changed file context menu includes option for locking/unlocking/force unlocking file(s)
- Persistent toggle option that is visible during Push to release owned file locks

#### Known Issues
- The username used for file locking is dependent on the server; proper lock ownership feedback won't happen until the user attempts to lock something for the first time
- Because of the technical limitation described above, it will still be possible for users to select/check locked files for commit (but this will return with an error popup from the server)
- There is no way to view or change existing locks for files that aren't part of the changes list
- Serious memory leakage when the user attempts to get or sets lock while not authenticated

### CODE REVIEW

**Comment by chasse20** [comment]
Added a toggle for automatically "Releasing" owned file locks upon commit. You'll see this on the Push screen and this setting will store persistently.

**Comment by outofambit** [comment]
Please see https://github.com/desktop/desktop/issues/8419#issuecomment-577926869. I've learned a lot here about `git-lfs` and the work required to integrate it more fully into GitHub Desktop. Thank you again.

**Comment by iamdeveloperidevelop** [comment]
Is it working? Or was it removed? I've just locked file via console, so locking is working, but github desktop is not detecting that

**Comment by btarg** [comment]
LFS file locking would be an incredible boon for game devs using GH Desktop, especially for Unreal Engine games. Having a simple UI to lock files for collaboration is something that I'm surprised is overlooked!

**Pull request closed without merging**
