### PR TITLE
Can't pull after cloning an empty repository

### PR DESCRIPTION
**Pull request by agisilaos**
Fixes: #4574 

I followed @shiftkey's advice and implemented his rough patch for fixing this issue. One of his comments though was:

> This feels suboptimal because we're repeating the same check in a few places, but that's a side-effect of how the component is currently organized. But that should be a starting point for someone to dig into.

**Note:** Maybe we can change some things about how this component is organized so we don't repeat the same check as much? I'm open to suggestions.

### CODE REVIEW

**Comment by agisilaos** [comment]
🍅

**Comment by agisilaos** [comment]
Hmm, can't access VSTS logs to see why build's failing.. As I can see also the build on master is failing as well. Super weird. 🤔 Any ideas what may be happening? @iAmWillShepherd

**Comment by shiftkey** [comment]
@agisilaos 

> Hmm, can't access VSTS logs to see why build's failing.. 

@agisilaos that build was from before we gained access to public projects, and the actual error was because forks were not building at the time. This should all be fine now.

**Comment by shiftkey** [comment]
@agisilaos I think the submodules changes need to be reverted to whatever is currently on `master`

**Comment by agisilaos** [comment]
Hm, what you mean @shiftkey?

**Comment by shiftkey** [comment]
@agisilaos this reads to me as a merge gone awry:

```
~/src/desktop/ git log -p -n 2 -- app/static/common/gitignore
commit d914f8cdb46bc9e023eda37d1164e9ede7a2f4ab
Author: agisilaos <tsaras96@yahoo.gr>
Date:   Wed May 9 15:59:13 2018 +0300

    🤔

diff --git a/app/static/common/gitignore b/app/static/common/gitignore
index 18e28746b..690a433b6 160000
--- a/app/static/common/gitignore
+++ b/app/static/common/gitignore
@@ -1 +1 @@
-Subproject commit 18e28746b0862059dbee8694fd366a679cb812fb
+Subproject commit 690a433b668348c33087d34fafe2155ebe8bb4cf

commit 07316cfcd11df395445d3ed7c31bc7f47e486277
Author: Brendan Forster <github@brendanforster.com>
Date:   Fri May 4 12:24:25 2018 +1000

    update submodules to get new changes

diff --git a/app/static/common/gitignore b/app/static/common/gitignore
index 690a433b6..18e28746b 160000
--- a/app/static/common/gitignore
+++ b/app/static/common/gitignore
@@ -1 +1 @@
-Subproject commit 690a433b668348c33087d34fafe2155ebe8bb4cf
+Subproject commit 18e28746b0862059dbee8694fd366a679cb812fb
```

**Comment by agisilaos** [comment]
@shiftkey Will create a fresh pr because I'm not sure what's exactly happening here.

**Pull request closed without merging**
