### PR TITLE
fix pointy corners with border-radius

### LINKED ISSUE #6635: Fix pointy corners on the commit description box
See #6234 — that fix broke autocomplete popups, so this has to be done a different way.

### PR DESCRIPTION
**Pull request by lisavogtsf**
## Overview
Addresses pointy corners on commit message issue

**Closes #6635**

## Description
Restores textarea border-radius to inherited value.

I was unable to verify whether this affects `autocompletion-popup user` and `autocompletion-popup issue` problems resulting from an earlier attempted fix, mentioned in #6459, as I couldn't replicate the autocompletion behavior in Github Desktop 1.6.1 or in the dev build.

## Release notes
Notes: no-notes

### CODE REVIEW

**Comment by outofambit** [comment]
I was able to verify the autocomplete looks good! (It's a little particular about which usernames it will trigger on depending on the repo.)

screen shot 2019-02-03 at 8 51 08 pm
screen shot 2019-02-03 at 8 50 14 pm

**Comment by j-f1** [comment]
Looks like the bottom corners aren’t rounded.

**Comment by outofambit** [comment]
good catch @j-f1! @lisavogtsf could you take a look at that? thank you!

**Comment by lisavogtsf** [comment]
Interesting. And thanks for the catch @j-f1 ! (and thanks for moving the issue to 'in progress')

On my machine--where I can't see autocompletion--all corners look rounded.
screen shot 2019-02-03 at 7 13 22 pm
screen shot 2019-02-03 at 7 13 15 pm

I wonder if the autocompletion is the problematic interaction again. I'll see if I can trigger the autocompletion.

**Comment by j-f1** [comment]
Are those screenshots from a repo that’s connected to GitHub? If not, the co-author feature may be disabled.

**Comment by lisavogtsf** [comment]
@j-f1  Thanks! and double face-palm. It looks like I wasn't properly logged in to github on the dev version of the app--as evidenced by the old profile photo. I don't have time to look into this more now, but I will later. And now I have pointy corners on the bottom too. Interesting that it may have to do with login or co-authors or... will see.

**Comment by lisavogtsf** [comment]
With the latest styling changes commit I get rounded bottom corners and emoji autocomplete whether the action bar is visible or not.
image
image

**Comment by j-f1** [comment]
How does it look when you click the co-author button?

**Comment by lisavogtsf** [comment]
@j-f1 I think this is reasonable behavior when you click the co-author button. The very bottom corners remain rounded while the separation between description and co-authors is a right angle.

screen shot 2019-02-04 at 3 08 29 pm
screen shot 2019-02-04 at 3 08 21 pm

**Comment by tierninho** [comment]
LGTM! The changes look ✨

> I was unable to verify whether this affects `autocompletion-popup user` and `autocompletion-popup issue` problems resulting from an earlier attempted fix, mentioned in #6459, as I couldn't replicate the autocompletion behavior in Github Desktop 1.6.1 or in the dev build.

Verified above and we are good to go 💯

**Pull request merged**
