### PR TITLE
Dynamically Stylable SVG: Part Deux

### PR DESCRIPTION
**Pull request by OiYouYeahYou**
Continuing from: https://github.com/desktop/desktop/pull/3135

### CODE REVIEW

**Comment by OiYouYeahYou** [comment]
@niik Am I up to your specifications, or are you waiting on me for anything?

**Comment by iAmWillShepherd** [comment]
@niik is currently on a plane to America. This team's productivity may be down since we are having a team meeting.

**Comment by niik** [comment]
@OiYouYeahYou I went through and fixed up that shadow for the paper stack and added back some wheels on the UFOs that apparently had gone missing. I think the SVGs are in good shape now so the next step would be to discuss how we approach making them dynamically stylable. Did you already have something ready for that?

**Comment by shiftkey** [comment]
Dropping `ready-for-review` while @niik and @OiYouYeahYou are jamming on the changes mentioned in the previous comment.

**Comment by nerdneha** [comment]
Hi @OiYouYeahYou, it looks like you've gotten a little busy lately as there haven't been activity on this in the last month. Is this still something you're interesting in pursuing? Additionally, did we miss any outstanding or blocking questions?

If not, we thought we might close this PR just for the time being until you have the bandwidth to open it up again.

**Pull request closed without merging**
