### PR TITLE
tidy up some unnecessary braces

### PR DESCRIPTION
**Pull request by garritfra**

### CODE REVIEW

**Comment by shiftkey** [comment]
@garritfra we're using Prettier to formatt the code, and I think these changes will clash with that

**Comment by j-f1** [comment]
@shiftkey Some of these changes remove `{}` from arrow functions, which [Prettier explicitly doesn’t modify](https://prettier.io/docs/en/rationale.html#what-prettier-is-not-concerned-about). This PR might be valuable if you prefer to avoid braces on single-line functions.

**Comment by shiftkey** [comment]
@j-f1 fair point - I'll reopen this and see if @garritfra wants to address the CI issues (which are around whitespacing and should be addressable with a `yarn lint:fix`

**Comment by garritfra** [comment]
I'll make sure to do that after work

**Comment by garritfra** [comment]
done, need review👀

**Pull request merged**
