### PR TITLE
Add key property for all dialogs to ensure transitions

### PR DESCRIPTION
**Pull request by outofambit**
## Overview

While investigating a crash related to dialogs, I saw that most of our dialog components are missing a `key` property, which is needed to ensure that the component isn't created/destroyed more than once during transitions.

This PR adds `key`s to all dialog components that lack them.

### CODE REVIEW

**Comment by tierninho** [comment]
Anything to test here? Dialogs seem fine in dev mode. Tried to use React in dev tools to verify `key` but crashes periodically.

**Comment by shiftkey** [comment]
> Tried to use React in dev tools to verify `key` but crashes periodically.

@tierninho what sort of crash? 🤔

**Comment by iAmWillShepherd** [comment]
> Anything to test here? Dialogs seem fine in dev mode. Tried to use React in dev tools to verify `key` but crashes periodically.

Are you referring to React dev tools crashing or the Desktop application?

**Comment by tierninho** [comment]
> Are you referring to React dev tools crashing or the Desktop application?

Yes, when I drill down into some content in the React tab, it crashes every time.

> what sort of crash?

```
TypeError: Cannot convert undefined or null to object
    at Function.getOwnPropertyNames (<anonymous>)
    at Bridge._inspectResponse (chrome-extension://react-developer-tools/build/backend.js:7696:17)
    at Bridge._handleMessage (chrome-extension://react-developer-tools/build/backend.js:7592:15)
    at listener (chrome-extension://react-developer-tools/build/backend.js:92:10)

Version: 2.0.4
OS: Mac OS 10.14.5
```

**Comment by iAmWillShepherd** [comment]
@tierninho 

This change isn't causing that crash. I get those crashed pretty often as well when trying to inspect state. I think it's a bug with dev tools.

**Pull request merged**
