### PR TITLE
[WIP] Syntax Highlighter: Support for Swift language

### PR DESCRIPTION
**Pull request by agisilaos**
Hello everyone, I thought it would be a good idea for the Github Desktop's highlighter app to support Swift. I started working on that and so far I only added swift as an option to the `app/src/highlighter/index.ts`.

 I would really like to continue working on it but not sure how I should proceed. I tried to see how other languages are being implemented for this feature and I didn't see any difference from what I did so far(in general). Any ideas what's the next steps should be? Any help is really appreciated!

@niik Thank you so much for working on that! Looks super rad 💯

### CODE REVIEW

**Comment by niik** [comment]
Hey @agisilaos, that looks great! All I need from you now is to submit a PR to https://github.com/desktop/highlighter-tests with a good sample file written in Swift, you can name it `swift.swift`.

Once that's in we can get this merged and then we can follow up in another PR if there's any language-specific tweaks in css.

**Comment by agisilaos** [comment]
Sounds like a plan @niik 👍

**Comment by agisilaos** [comment]
@niik PR for the swift file in the [Highlighter Tests](https://github.com/desktop/highlighter-tests) can be found here: [Add swift file in the repo #1](https://github.com/desktop/highlighter-tests/pull/1) ✌️

**Comment by koenpunt** [comment]
To complement this; Objective-C would be cool too!

**Comment by niik** [comment]
@koenpunt Objective-C should already work as long as the file extension is ”.objc”. If it’s not working for you please file an issue and we’ll have a look

**Comment by koenpunt** [comment]
I believe the common extension for Objective-C is `.m`, so I've created a PR for that: https://github.com/desktop/desktop/pull/3355

**Comment by Rom2018** [comment]
roml.l@yandex.kz       roml.l@yandex.by       roml.l@ya.ru     roml.l@yandex.ua

**Pull request merged**
