### PR TITLE
Adding Accessibility Linting

### PR DESCRIPTION
**Pull request by tidy-dev**
## Description
Adding [recommended accessibility linting](https://thehub.github.com/epd/engineering/dev-practicals/frontend/accessibility/readiness-routine/linting-recommendations/#linting-in-ci).

Related Issue: https://github.com/github/accessibility/issues/1673

## Release notes
Notes: no-notes

### CODE REVIEW

**Comment by tidy-dev** [comment]
So far I have added [eslint-plugin-primer-react](https://github.com/primer/eslint-plugin-primer-react). Resulting in 112 errors - A quick glance looks like a lot of images without `alt` attribute.

**Comment by tidy-dev** [comment]
Added  [eslint-plugin-github](https://github.com/github/eslint-plugin-github) and 
image

**Comment by tidy-dev** [comment]
For [eslint-plugin-primer-react](https://github.com/primer/eslint-plugin-primer-react), there are 15 rules that I have set to warn for now, but likely we will want to address from an accessibility perspective.

1. jsx-a11y/alt-text
2. jsx-a11y/click-events-have-key-events
3. jsx-a11y/no-noninteractive-element-interactions
4. jsx-a11y/no-static-element-interactions
5. jsx-a11y/no-autofocus
6. jsx-a11y/no-noninteractive-element-to-interactive-role
7. jsx-a11y/aria-role
8. jsx-a11y/aria-activedescendant-has-tabindex
9. jsx-a11y/mouse-events-have-key-events
10. jsx-a11y/label-has-associated-control
11. jsx-a11y/anchor-is-valid
12. jsx-a11y/iframe-has-title
13. jsx-a11y/no-noninteractive-tabindex
14. jsx-a11y/role-supports-aria-props
15. jsx-a11y/interactive-supports-focus

For [eslint-plugin-github](https://github.com/github/eslint-plugin-github), there are 37 rules that have errors. I have turned them all off off as these all appear to be coding style rules and not required to meet accessibility standards. That said, many of them would likely be easy to correct and the our code base would be better for it. 

1. github/array-foreach
2. github/no-then
3. import/no-namespace
4. import/first
5. import/no-duplicates
6. import/no-commonjs
7. import/no-unresolved
8. import/no-dynamic-require
9. import/named'
10. import/extensions
11. eslint-comments/no-use
12. eslint-comments/no-unused-disable
13. eslint-comments/no-duplicate-disable
14. filenames/match-regex
15. i18n-text/no-en
16. no-only-tests/no-only-tests
17. no-console
18. no-undef
19. prefer-promise-reject-errors
20. no-shadow
21. no-case-declarations
22. no-unused-vars
23. no-invalid-this
24. camelcase
25. prefer-template
26. no-useless-escape
27. one-var
28. object-shorthand
29. func-style
30. no-useless-concat
31. no-extra-boolean-cast
32. no-control-regex
33. no-empty
34. no-ex-assign
35. no-fallthrough
36. no-irregular-whitespace
37. no-dupe-class-members

**Comment by tidy-dev** [comment]
After some discussion with accessibility folks, right now we just need [eslint-plugin-github](https://github.com/github/eslint-plugin-github) and we to use the plugin as `github/react` (as opposed the the recommended). 

This results in the same 112 errors as seen from [eslint-plugin-primer-react](https://github.com/primer/eslint-plugin-primer-react). Per https://github.com/github/accessibility/issues/1673, I disabled those errors via inline comments. There were some places where inline comments would not work as not acceptable react/typscript syntax and I disabled the rule for the whole file instead.

**Comment by tidy-dev** [comment]
Added markdown linter as a separate yarn command - thus not yet part of our `yarn lint` command that is used by our actions workflows. The markdown linter currently shows 127 errors.

**Review by sergiou87 — APPROVED** [review]
Looks good! I built and ran the app and worked as expected :shipit: 

Also ran `yarn markdownlint` and got the 127 errors you mentioned!

**Pull request merged**
