### PR TITLE
Bump more dependencies for macOS arm64

### PR DESCRIPTION
**Pull request by sergiou87**
## Description

This PR bumps 3 dependencies:
- desktop-trampoline to [v0.9.7](https://github.com/desktop/desktop-trampoline/releases/tag/v0.9.7) because I found out the prebuilt binaries for arm64 actually had a x86_64 binary 😐  For some reason, it didn't use the arm64 binary until [I bumped the node version](https://github.com/desktop/desktop-trampoline/commit/ab9cabd08f92ee903b192ffef3752ede1d0bbd86) 🤯 
- dugite to [v1.103.0](https://github.com/desktop/dugite/releases/tag/v1.103.0) which uses arm64 binaries for git and git-lfs.
- app-path to [v3.3.0](https://github.com/sindresorhus/app-path/releases/tag/v3.3.0) which contains now [a universal binary I added](https://github.com/sindresorhus/app-path/pull/13).

## Release notes

Notes: no-notes

### CODE REVIEW

**Review by tidy-dev — APPROVED** [review]
✨

**Comment by jensenharris** [comment]
When I install 2.8.1-beta2 on my Apple Silicon Mac without Rosetta installed, it immediately prompts me:

Rosetta Required

Looks like still something to sort out here? I see the app type as Intel.

I installed through the Beta link in `readme.md`: https://central.github.com/deployments/desktop/desktop/latest/darwin?env=beta

**Comment by sergiou87** [comment]
@jensenharris yes, that link downloads the x64 beta. I added a new link to the README.md in https://github.com/desktop/desktop/pull/12098/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R30 but that branch hasn't been merged yet.

The link for arm64 betas for macOS is https://central.github.com/deployments/desktop/desktop/latest/darwin-arm64?env=beta (notice the `-arm64` suffix)

**Comment by jensenharris** [comment]
You are a hero @sergiou87. Thanks for your work bringing this across the last mile! The build at the new link now works fine on my Rosetta-less M1. I really appreciate it!

**Pull request merged**
