### PR TITLE
Adjust diff dark theme colors

### LINKED ISSUE #5027: Dark Theme Beta Diff Colors Are Not Ideal
I'm testing the new beta version of the new dark theme and the only issue I'm having is that the green and red colors used to represent added lines and deleted lines are too dark (the green for sure it seems).  You can still see where the colors start and stop in the lines of code, but they do not jump out at you like they do in the normal theme (which is expected, but not to this degree).  I think having brighter colors here would help out a bit for those with eyes that are not entirely great.

screen shot 2018-06-25 at 2 53 58 pm

### PR DESCRIPTION
**Pull request by ampinsk**
This lightens the dark green diff colors in dark theme! There was discussion in #5027 on how to ideally go about this, and I'd love to continue that here. Do these colors feel like an improvement? Is this more or less accessible for colorblind users?

**Before**
screen shot 2018-06-29 at 4 10 33 pm

**After**
screen shot 2018-06-29 at 4 07 52 pm

Fixes #5027

### CODE REVIEW

**Comment by shiftkey** [comment]
Adding in some screenshots of how this looks when emulating colorblindness - I merged `master` into this PR which now enables #4959:

#### Light theme - red-blind (unchanged)

screen shot 2018-07-03 at 7 57 52 pm

#### Light theme - green-blind (unchanged)

screen shot 2018-07-03 at 7 57 39 pm

#### Dark theme - red-blind

screen shot 2018-07-03 at 7 58 34 pm

#### Dark theme - green-blind

screen shot 2018-07-03 at 7 58 45 pm

**Comment by greg-grondecki-infotrack** [comment]
I would say that the background green is still a tiny bit too dark, but better than previous

**Comment by JosephTLyons** [comment]
I agree with @greg-grondecki-infotrack.  This is an improvement, but it is still a bit dark.

**Comment by ampinsk** [comment]
I lightened the greens a bit more! 

screen shot 2018-07-09 at 9 59 04 am

**Comment by agisilaos** [comment]
Looks so much better than the previous iteration. I just received the new beta and I love it. 😍 Thank you @ampinsk!

**Pull request merged**
