### PR TITLE
Upgrade to React 16

### PR DESCRIPTION
**Pull request by shiftkey**
- [x] test app locally (dev and prod) on macOS
 - [x] test app locally (dev and prod) on Windows
 - [x] test app locally (dev and prod) on Linux
 - [x] summarise performance changes as part of upgrading
 - [x] update `tooling.md` to mention [this post](https://building.calibreapp.com/debugging-react-performance-with-react-16-and-chrome-devtools-c90698a522ad) about debugging React perf

### CODE REVIEW

**Comment by shiftkey** [comment]
Notes about the changes in `yarn build:prod` output:

 - renderer.js: now 1.47 MB (was 1.52 MB)
 - renderer.js.map: now 4.46 MB (was 5.12 MB)
 - crash.js: now 181 kB (was 227 kB)
 - crash.js.map: 314 kB (was 937 kB)

**Comment by shiftkey** [comment]
Benchmarking launch time for a macOS and Windows setup (with `yarn build:prod` && `yarn start:prod` and five launches from a warm start, with different #s of tracked repositories). Looks like it shaves a bit from the full load time, with the renderer ready time being about the same.

### macOS

 Using `master` aka 597ef296ce929bc816021260bfa87187bc967eaa:

 - mean `Renderer ready time`: 249.2ms
 - mean `Load time`: 402.8ms

Using this PR aka 085e70494006165baefc3e3e7e74ef25426d83c6:

 - mean `Renderer ready time`: 242.7ms
 - mean `Load time`: 380.5ms

### Windows

 Using `master` aka 597ef296ce929bc816021260bfa87187bc967eaa:

 - mean `Renderer ready time`: 347.2ms
 - mean `Load time`: 540.03ms

Using this PR aka 085e70494006165baefc3e3e7e74ef25426d83c6:

 - mean `Renderer ready time`: 351ms
 - mean `Load time`: 513ms

**Comment by shiftkey** [comment]
@desktop/core feels on getting this reviewed and merged - do we want to do this before 1.2 is underway?

**Comment by shiftkey** [comment]
I've also updated `react-virtualized` in this process as it looks like there's been [a few hotfixes](https://github.com/bvaughn/react-virtualized/blob/master/CHANGELOG.md) and "More natural scrolling speeds for large lists in Chrome. " stood out as something that might help us out in Desktop. 

I've gotta give this another pass to ensure this is ready for review.

**Comment by niik** [comment]
> @desktop/core feels on getting this reviewed and merged - do we want to do this before 1.2 is underway?

I'm 👍 this is the right time in the cycle to get these changes in so that we can get some mileage on them before release. If we get this, Electron 1.8 and TS 2.7 upgraded all in this on release we'll have a lot of surface area to test so the more time we have for that the better.

**Pull request merged**
