### PR TITLE
Add MacVim as a supported external editor for macOS

### PR DESCRIPTION
**Pull request by johnelliott**
Fixes https://github.com/desktop/desktop/issues/4530

### CODE REVIEW

**Comment by iAmWillShepherd** [comment]
@johnelliott, looks like the tests are passing on our CI server, so not sure why tests are failing for you locally. I think it's safe for you to ignore since your changes have nothing to do with that part of the code base.

**Comment by iAmWillShepherd** [comment]
Could you also update the editor integration doc to reflect the new supported editor? Once that's complete, I can mark this PR as `ready-for-review`.

**Comment by johnelliott** [comment]
@iAmWillShepherd yes

**Comment by agisilaos** [comment]
@johnelliott Can you replace `from:` with `Fixes:`? So the issue can be closed automatically when the PR is merged.

**Comment by johnelliott** [comment]
@shiftkey great, thank you :)

**Comment by iAmWillShepherd** [comment]
Gonna go ahead and give this a merge @shiftkey.

**Comment by HeartQ** [comment]
thanks u

**Pull request merged**
