### PR TITLE
add note about Arch Linux package

### LINKED ISSUE #3377: Arch Linux AUR PKGBUILD
I've created an install script for Arch Linux: https://aur.archlinux.org/packages/github-desktop-git/

### PR DESCRIPTION
**Pull request by shiftkey**
Fixes #3377 

cc @immackay for any additional feedback

### CODE REVIEW

**Comment by immackay** [comment]
Hi @shiftkey, I've also taken over the package https://aur.archlinux.org/packages/github-desktop/ which will be kept updated to the latest release.

**Comment by shiftkey** [comment]
@immackay which one would you prefer to be the canonical `PKGBUILD`?

**Comment by immackay** [comment]
Is the Desktop dev team planning any breaking changes in the master repo? :wink:
If not, then either will be fine I'm sure

**Comment by shiftkey** [comment]
> Is the Desktop dev team planning any breaking changes in the master repo?

`master` will have the latest changes, so let's use `github-desktop` for the README.

**Pull request merged**
