### PR TITLE
Add host key verification to auth issue list

### PR DESCRIPTION
**Pull request by ghost**
## Description

Recently I encountered an issue where I deleted my `.ssh/known_hosts` file and afterward was unable to fetch and push from a repository I was previously able to use with GitHub Desktop. The app showed an "Authentication failure".
Once I verified the host's fingerprint running, e.g. `ssh git@github.com`, everything worked fine.

The dialog tries to be helpful and expansive, but it did not lead me to the resolution.
Adding this helps people save some time; however, handling host key verification in-app in the future may be a helpful idea.

I hope you find this valuable, too.

### Screenshots

Screenshot of updated dialog

## Release notes

Notes: no-notes

### CODE REVIEW

**Comment by liannemarie** [comment]
Please remove unauth access on my account

**Comment by sergiou87** [comment]
Thanks for the PR @thsmdt!! In theory, recent work around SSH support (#12756) should've addressed this so that you wouldn't even see the error dialog.

Could you share your logs so I can dig into this? Thank you!

**Comment by ghost** [comment]
Sure, this excerpt is from a build based on the branch associated with this pull request; thus, the message is already adapted.
It shows you what happens on clones.

Maybe a note to my environment: I am running a macOS 12 beta.

```
info: [ui] [AppStore.getAccountForRemoteURL] no generic credentials found for 'git@github.com:desktop/desktop.git'
info: [ui] Executing clone: git -c credential.helper= -c init.defaultBranch=development clone --recursive --progress -- git@github.com:desktop/desktop.git <LOCALPATH>/GitHub/desktop (took 0.343s)
error: [ui] `git -c credential.helper= -c init.defaultBranch=development clone --recursive --progress -- git@github.com:desktop/desktop.git <LOCALPATH>/GitHub/desktop` exited with an unexpected code: 128.
stderr:
Cloning into '<LOCALPATH>/GitHub/desktop'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 2: Authentication failed. Some common reasons include:

- You are not logged in to your account: see GitHub Desktop > Preferences.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
```

**Comment by sergiou87** [comment]
> macOS 12 beta

That might be it, AFAIK macOS 12 includes a newer version of OpenSSH, which may have changed the specific string we use to detect when git/ssh requires to accept a host's key fingerprint. We're looking for prompts that look like this: https://github.com/desktop/desktop/blob/bb140c08aa7ec8711309b944ccf5fea48564039b/app/src/lib/trampoline/trampoline-askpass-handler.ts#L14-L24

I will investigate next week (or feel free to check what's the specific prompt you get and update the regex linked above to update this PR 😄 )

**Comment by haykam821** [comment]
I get a message like this on the macOS 12 Monterey beta:

```
The authenticity of host '👀 (👀)' can't be established.
RSA key fingerprint is SHA256:👀.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])?
```

```
The authenticity of host '👀 (👀)' can't be established.
ED25519 key fingerprint is SHA256:👀.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])?
```

In particular it looks like the 'This key is not known by any other names' line needs to be accounted for.

**Comment by sergiou87** [comment]
That's perfect, thank you @haykam821 !! ❤️

**Comment by ghost** [comment]
I just added a fix that works on macOS 12 and seems not to break things for other clients. 😄
However, I am unsure if the way I went is too open and should be restricted to the known line @haykam821 already mentioned?

Further, I realized that the popup only showed for RSA; as many repository hosting services seem to use ED25519 or alternatives nowadays, the key type is now be extracted from the prompt and shown in the popup.


This is how it looks:

Add SSH Host Dialog with SSH

Add SSH Host Dialog with ED25519

**Review by sergiou87 — CHANGES_REQUESTED** [review]
This looks great @thsmdt 😍  I tested it on macOS Big Sur and Windows and works fine!

Seems like CI is failing because you need to run the linter, other than that I'd say this is good to go ❤️

**Comment by ghost** [comment]
Sounds great! Thanks for checking, @sergiou87 😄

I missed the linter check; sorry for that. Now it should work just fine 😊

**Review by sergiou87 — APPROVED** [review]
Thanks for your contribution! :shipit:

**Comment by Lino357** [comment]
My device hat same problems wire the new game system

**Pull request merged**
