### PR TITLE
Add suport to IntelliJ Idea on Mac

### LINKED ISSUE #8398: Add support for IntelliJ IDEA as an editor
**The problem**
Now that I'm back at being a Java developer I've been using IntelliJ more and more, it would be great to add it as a supported editor

I have already a working patch that I'll gladly submit for review if there's no problem to add the support 
Screenshot 2019-10-03 at 12 52 38

### PR DESCRIPTION
**Pull request by gssbzn**
## Overview

**Closes #8398**

## Description

- Add support for IntelliJ IDEA on Mac

## Release notes

Notes:

- Add support for IntelliJ IDEA on Mac

### CODE REVIEW

**Comment by Rexogamer** [comment]
Do they have a Windows app?

**Comment by gssbzn** [comment]
@Rexogamer they do but jetbrains installation on windows is kind of a mess and detection of jetbrain products is complicated, I previously added RubyMine and tried to add windows support as well but you can see the conversation here https://github.com/desktop/desktop/pull/3883

**Comment by Rexogamer** [comment]
Ahhh yes, JetBrain.

**Comment by SilveraGit** [comment]
,

**Comment by Rexogamer** [comment]
@SilveraGit hmm?

**Pull request merged**
