### PR TITLE
Dont change message while restoring

### LINKED ISSUE #7652: "unable to restore" prompt appears when restore takes time to complete
## Description

The warning we have setup to originally indicate that a stash cannot be restored also appears as part of the normal restore flow:

## Version
* GitHub Desktop: `1.7.1-beta1`
* Operating system: Windows 10

## Steps to Reproduce
1. Setup a stash to restore (I've been able to see this with as few as 3 files, but 20+ is a good number)
2. Restore the stash

### Expected Behavior

Some indicator of progress while restoring the stash would be nice, but other than that the experience is fine.

### Actual Behavior

Midway through the restore process the alert about "Unable to restore stash..." appears and then disappears:

restore-warning-appears-during-restore

This is confusing in a couple of ways:

 - the ⚠️ indicator suggests something hazardous
 - how it appears and disappears while I'm waiting makes me a bit nervous

### PR DESCRIPTION
**Pull request by iAmWillShepherd**
~~⚠️ Depends on https://github.com/desktop/desktop/pull/7683~~
~~🗒 This branch is based on `stop-clicking-on-me` to keep the diff small.~~

## Overview

Fixes #7652

## Description

Prevent the stash message from changing while restoring a stash.

_Note that I faked the long stash restore using `setTimeout` to show the message doesn't change_

Notes: [Fixed] "Unable to restore" prompt no longer changes while restoring stash.

### CODE REVIEW

**Comment by outofambit** [comment]
@iAmWillShepherd since this merges into another PR of yours, I'd say hit merge whenever you're ready

**Comment by iAmWillShepherd** [comment]
> @iAmWillShepherd since this merges into another PR of yours, I'd say hit merge whenever you're ready

I'd prefer to keep this change separate since it solves a different problem than what this PR is based on. If you're not against me waiting until #7683 is merged, I'll go that route.

**Comment by outofambit** [comment]
> I'd prefer to keep this change separate since it solves a different problem than what this PR is based on.

@iAmWillShepherd oh, i didn't understand from the PR description that you meant that you would merge it into `development` _after_ #7683 was merged. that would be my preference too. thanks for clarifying!

**Comment by shiftkey** [comment]
@iAmWillShepherd #7683 has been merged, please update this PR to target `development` so we can wrap this up too 🏎

**Pull request merged**
