### PR TITLE
Support for webp image

### PR DESCRIPTION
**Pull request by agisilaos**
Fixes: #4160 
This PR adds support for webp image. @shiftkey Let me know if there's anything else I can do to improve the existing PR.

### CODE REVIEW

**Comment by shiftkey** [comment]
@agisilaos did you find an example repository to help with testing this out?

**Comment by j-f1** [comment]
@shiftkey What do you think about renaming the `highlighter-tests` repo to `diff-tests` or something similar? Then, we could commit example files to test the diffs.

**Comment by shiftkey** [comment]
@j-f1 I'm 👎 to repurposing the `highlighter-tests` repo for our needs, but I am interested in potentially introducing a `diff-tests` repository for situations like this where we want to make it easier to verify changes without depending on external repositories.

**Comment by agisilaos** [comment]
@shiftkey Yes! It works like a charm. 🌮 

screen shot 2018-03-04 at 01 58 12

**Comment by niik** [comment]
> but I am interested in potentially introducing a `diff-tests`

@shiftkey I'm 👍 on that but I don't believe it should block this PR from landing so I'm gonna go ahead and bring this in.

**Comment by shiftkey** [comment]
@niik agreed - putting it on my backlog to start off and document Later™

**Comment by mannerAvTV** [comment]
_pullfile_

**Pull request merged**
