### PR TITLE
1.6.4 hotfix release

### PR DESCRIPTION
**Pull request by shiftkey**
## Overview

This PR is intended to close out some outstanding issues that arose from the `1.6.3` release last week:

 - [Electron Security Fix](https://electronjs.org/blog/filereader-fix) - not directly affecting Desktop, but good to pull in as soon as possible
 - #7028 - we've not been able to reproduce this issue on our end, but given Git for Windows was updated as part of this release we're fairly sure it's a regression that has been fixed in a later release. As we're not tied to any features as part of this release, we can revert back to the version of Git which we were using in `1.6.2`
 - #7038 - we feel this was also an artifact of the Git upgrade, but the experience can be improved on top of reverting to the previous version of Git - see #7062 for more details

There are other related issues like #7040 and #7028 but we believe they're relating back to the same root cause.

## Description

TODO:

 - [x] bump version for beta
 - [x] draft release notes for beta
 - [x] get approval on changes and release notes
 - [x] ship to beta
 - [x] get feedback that #7028 is resolved 
 - [x] get feedback that #7038 is resolved
 - [x] bump version and update release notes for production
 - [x] ship to production
 - [x] merge in `development` so this PR is mergeable

## Release notes

Notes: no-notes

### CODE REVIEW

**Comment by jaybirdfish** [comment]
Can't wait for this to be available. 1.6.3 has stopped us cold

**Comment by shiftkey** [comment]
@jaybirdfish which issue are you affected by?

**Comment by jaybirdfish** [comment]
Hi, Brendan.

1.6.3 of Github Desktop no longer works because it says something about “error launching git: Filename or extension is too long”. I tried all the workarounds I could find, but they didn’t work for me.

Thanks,
Jay

**Comment by jaybirdfish** [comment]
Excellent work. I just downloaded v1.6.4 and it is working fine. Thanks for fixing it.

**Pull request merged**
