### PR TITLE
Dismissable merge conflict dialog and associated banner

### LINKED ISSUE #6379: Make Merge Conflicts Dialog Dismissable
from designs in https://github.com/desktop/desktop/issues/6213#issuecomment-440048836

cc @desktop/design

### LINKED ISSUE #6380: Make Merge Conflicts Dialog Reopenable from Banner
from designs in https://github.com/desktop/desktop/issues/6213#issuecomment-440048836

cc @desktop/design

### PR DESCRIPTION
**Pull request by outofambit**
## Overview

Closes #6379 
Closes #6380 

## Description

dismissable merge conflicts modal

## Release notes

Notes: "Merge Conflicts" dialog flow can be exited to support more workflows

### CODE REVIEW

**Comment by tierninho** [comment]
Two questions arose while testing this:

- Was the `Open in Merge Tool` button in the upper right of your gif supposed to do anything? Nothing happens when i click it. 

- Is the user allowed to switch branches, or compare against another branch? I currently get an error telling me to resolve the conflict first.

Suggestion:
Allow the modal to be closed only by clicking the `X` or the `esc` key, not by clicking off the screen into another part of the app. Use case: When i make the edit in Atom, and click back into Desktop, the modal disappears.

**Comment by ampinsk** [comment]
Woop looks great! Only thing I noticed is the alert icon in the banner should be orange instead of gray. 😄

**Comment by outofambit** [comment]
@ampinsk thoughts on this?

> Allow the modal to be closed only by clicking the X or the esc key, not by clicking off the screen into another part of the app.

**Comment by ampinsk** [comment]
@outofambit re: 

> Allow the modal to be closed only by clicking the X or the esc key, not by clicking off the screen into another part of the app.

I agree with this 👍

**Comment by outofambit** [comment]
🍏

**Comment by outofambit** [comment]
@iAmWillShepherd 🍕

**Pull request merged**
