### PR TITLE
Power up PowerShell Highlights

### PR DESCRIPTION
**Pull request by say25**
Adding PowerShell Highlight Support

### CODE REVIEW

**Comment by shiftkey** [comment]
@say25 are you able to add a corresponding test to https://github.com/desktop/highlighter-tests to go with this change?

**Comment by say25** [comment]
Yea I can. Just haven’t had the time yet :(

**Comment by shiftkey** [comment]
@say25 no problem - having that file ready helps with the review process on our end too!

**Comment by say25** [comment]
Corresponding Highlighter-Test PR: https://github.com/desktop/highlighter-tests/pull/26

**Comment by shiftkey** [comment]
Thanks again @say25!

**Comment by say25** [comment]
@shiftkey now if only you could cut me another beta so I could use it ..... 😛

**Pull request merged**
