### PR TITLE
started on a guide to integrating Desktop with VSTS

### PR DESCRIPTION
**Pull request by shiftkey**
@mrahhal added a lovely comment in https://github.com/desktop/desktop/issues/852#issuecomment-322983925 about a server-side configuration to work nicely with Desktop, so I'm pulling this in so others might find it later.

@mrahhal - are there screenshots of this experience that you can share with us to this to round this out?

### CODE REVIEW

**Comment by mrahhal** [comment]
Sure. I'll prepare some screenshots.

**Comment by mrahhal** [comment]
1. Click on "Security" in the user profile's dropdown:



2. Click on "Alternate authentication credentials":



3. Check the "Enable alternate authentication credentials" checkbox, and then choose a suitable username/password:



4. Enter your chosen credentials. You can either use your email or the chosen username to authenticate:

**Comment by shiftkey** [comment]
@mrahhal that's amazing - I've folded that in and tweaked the words a bit. Thanks for the work!

**Comment by mrahhal** [comment]
Thanks for all the hard work! 🎉

**Comment by shiftkey** [comment]
#jolo

**Comment by AbhishekMitra08** [comment]
Tried that. added an alternate account. Still getting authentication failed? Anything else that I am missing

**Comment by steveward** [comment]
@AbhishekMitra08 the steps for authenticating to Azure DevOps have changed. I've got a branch I'm working on to update the steps -- I just need to add screenshots. You can find it here:

https://github.com/desktop/desktop/blob/vsts-to-devops/docs/integrations/azure-devops.md

The short of it is you will now need to create a personal access token. Let me know if you have any issues.

**Pull request merged**
