### PR TITLE
Decreased the max line length limit

### LINKED ISSUE #3740: Decrease the max line length limit
As per https://github.com/desktop/desktop/pull/3032#issuecomment-354265785, we can probably cut our max line length limit down quite a bit. It's currently at 500,000. We could try 100,000 or even 50k.

See https://github.com/desktop/desktop/blob/b0d5afb37c36116006bb44855c9e3e81d3f554d7/app/src/lib/git/diff.ts#L41-L45

### PR DESCRIPTION
**Pull request by sagaragarwal94**
Fixes #3740

### CODE REVIEW

**Comment by iAmWillShepherd** [comment]
@sagaragarwal94, would you mind posting screenshots or GIFs of the test cases detailed in [this comment](https://github.com/desktop/desktop/issues/3740#issuecomment-370610592)? 

Also, for your issue body, can you replace _References_ with _Fixes_? We do this so that issues can be automatically closed once the PR is merged.

**Comment by shiftkey** [comment]
Given this was a minor change a bit tricky to demonstrate, I ran through these test scenarios to verify the limit is being enforced:

A long line in a diff, but below this limit, is rendered fine:

screen shot 2018-05-26 at 3 39 41 pm

A long line in a diff over this limit does trip the warning:



But then you can click **Show Diff** and see the contents of the diff:

**Comment by shiftkey** [comment]
Thanks for the contribution @sagaragarwal94!

**Comment by bdvis** [comment]
Amazing 🎉 thank you @sagaragarwal94! This has been driving me _crazy!_

**Pull request merged**
