### PR TITLE
Truncate long repo names in panes and modals

### PR DESCRIPTION
**Pull request by http-request**
Issue: <https://github.com/desktop/desktop/issues/2998>

**Before:**

screen shot 2017-12-14 at 00 26 20
screen shot 2017-12-14 at 00 25 59

**After:**

screen shot 2017-12-14 at 00 22 08
screen shot 2017-12-14 at 00 21 43

### CODE REVIEW

**Comment by shiftkey** [comment]
I think this needs to be addressed in the same way we address #3396, which is assigned to @niik.

**Comment by joshaber** [comment]
>I think this needs to be addressed in the same way we address #3396, which is assigned to @niik.

Hmm, I think the complexity with #3396 is that it has to use resize observers because the surrounding elements can change how much sizing we have. I don't _think_ we have that problem here. Or I might be misunderstanding what you're saying?

**Comment by shiftkey** [comment]
> Or I might be misunderstanding what you're saying?

I definitely left out some context here.

The branch names are important, and in many cases it's just the ending of the text that can differ. In other places where we deal with this (the branch list is a classic) we trim from the middle, not the end. If we intend to doing _trimming_ here, rather than _wrapping_, we should be consistent with other places in the app.

But :thumbsup: for digging up @donokuda's comment - I think that's what we should be doing here too...

**Comment by joshaber** [comment]
Ah, I see. You're saying we should be using `PathText` in the `Remove Repository` dialog in order to get middle truncation?

**Comment by shiftkey** [comment]
@joshaber I _think_ so. I don't have very strong feelings on this, but it might look better than wrapping on these very very very long branch names?

**Comment by niik** [comment]
> @joshaber I think so. I don't have very strong feelings on this, but it might look better than wrapping on these very very very long branch names?

We should only be truncating in lists, not in flow text. There are no realistic space constraints here and these types of dialogs (confirmation) are the last line of defense against getting rid of the wrong branch/repo. No reason not to show exactly what'll be removed.

Also, we should be using the ellipsis scss mixin here instead of duplicating

**Comment by http-request** [comment]
Now truncation uses for clone repository list. For remove confirmation modal it looks like it was before.

**Comment by joshaber** [comment]
Thank you @http-request 🤘

**Pull request merged**
