### PR TITLE
Prevent CodeMirror search plugin from stealing registered global keyboard shortcuts

### LINKED ISSUE #8068: Diff search keyboard shortcut conflicts with GitHub web site integration
## Description

There is a keyboard shortcut to open the repository on GitHub's website, which on Windows is CTRL+SHIFT+G.  There is also a keyboard shortcut to open the repo in the Finder or File explorer CTRL+SHIFT+F.  These used to work when viewing the history when the diff view was active.  Since (I'm assuming) https://github.com/desktop/desktop/pull/7866, CTRL+SHIFT+G and CTRL+SHIFT+F do not work in this scenario - CTRL+SHIFT+G instead opens the regex search in the diff view, and CTRL+SHIFT+F appears to do nothing.  It would be great if the SHIFT modifier would take precedence and instead open the repo/finder/file explorer when these combinations are pressed.

## Version

* GitHub Desktop: 2.1.0

* Operating system: Microsoft Windows [Version 10.0.17763.615]

## Steps to Reproduce

1. Commit some code in a repo that references an upstream on GitHub.
2. Edit some code and save.  On the "changes" screen, put your focus in the diff view (click into it).  Hit CTRL+SHIFT+G.  This used to open GitHub in your browser pointed to the repo.  It now opens the Regex diff search.  Hit CTRL+SHIFT+F.  This used to open your file explorer or finder pointed at the repo: it now appears to do nothing.
3. Click into the changes window so that the changed file's name is highlighted.  CTRL+SHIFT+G and CTRL+SHIFT+F now work as expected.
4. Click the History tab.
5. Click into the diff view.  Same issue - CTRL+SHIFT+F does nothing, CTRL+SHIFT+G opens the regex search.  These shortcuts work as expected if the changed files list or the commits list is focused.

### Expected Behavior
CTRL+SHIFT+F and CTRL+SHIFT+G should take precedence over CTRL+F and CTRL+G when SHIFT is pressed.

### Actual Behavior
CTRL+F and CTRL+G take precedence when the diff view is selected.

## Additional Information

Likely related to https://github.com/desktop/desktop/pull/7866

### PR DESCRIPTION
**Pull request by niik**
## Overview

**Closes #8068**

## Description

When I added the search plugin back in https://github.com/desktop/desktop/pull/7866 I forgot to look for new keyboard bindings that would come into effect through the default key maps. Looking through [the default key maps](https://github.com/codemirror/CodeMirror/blob/5.44.0/src/input/keymap.js#L8-L47) and [the commands registered by the search plugin](https://github.com/codemirror/CodeMirror/blob/6454f583167a44016ee452b1787466f442bd9122/addon/search/search.js#L249-L257) I arrived at this list of keyboard shortcuts to disable.

As part of this I also found that the co-author input control (which is also based on CodeMirror) also reacted to these shortcuts and showed a (unstyled and very unusable) search bar so I took care of that as well.

## Release notes

Notes: [Fixed] Some menu keyboard shortcuts didn't work while focused on a text diff.

### CODE REVIEW

**Comment by nycdotnet** [comment]
Thanks!  I approved but admit I don't know how this is supposed to work, but seems plausible. :-)

**Comment by tierninho** [comment]
Results of testing:

In diff:
`Cmd-F` = find text
`Cmd-G` = regex search
`Shift-Cmd-G` = regex search on first attempt, then opens repo on Github on second attempt 
`Shift-Cmd-Alt-F` = nothing
`Cmd-Alt-F` = selects small chunk of text

Global app:
`Cmd-F` = a find attempted, does nothing
`Cmd-G` = goes to summary field
`Shift-Cmd-G` = opens repo on Github
`Shift-Cmd-Alt-F` = nothing
`Cmd-Alt-F` = nothing

Co-author area:
`Cmd-F` = regex search
`Cmd-G` = regex search
`Shift-Cmd-G` = regex search
`Shift-Cmd-Alt-F` = regex replace all
`Cmd-Alt-F` = regex replace all

Do these look correct, especially `Shift-Cmd-G` in the diff area?

Edge case: if you do `Cmd-F` three times in a row in the diff area, then regex search appears overlapping it and won't go away.

4630190f60, mac

**Comment by kuychaco** [comment]
Hmmm I expected more nothing's for the co-author input 🤔 

> Co-author area:
> Cmd-F = regex search
> Cmd-G = regex search
> Shift-Cmd-G = regex search
> Shift-Cmd-Alt-F = regex replace all
> Cmd-Alt-F = regex replace all

And yeah this diff one seems odd:

> Shift-Cmd-G = regex search on first attempt, then opens repo on Github on second attempt

**Comment by niik** [comment]
@tierninho Are you sure you were testing on this branch? The commit sha that you included in your comment seems to indicate you were on development.

image

That might have ben just a copy paste error but I'm asking because I'm unable to reproduce your results on this branch.

**Pull request merged**
