### PR TITLE
Upgrade dugite to v1.91.3

### PR DESCRIPTION
**Pull request by rafeca**
Closes https://github.com/desktop/desktop/issues/10022
Closes https://github.com/desktop/desktop/issues/9904

## Description

This PR upgrades the current `dugite` version to [`v1.91.3`](https://github.com/desktop/dugite/releases/tag/v1.91.3) which includes a new version of `git` (`v2.26.2`).

These are the changes from to the currently used version `v1.88.6` ([full list of commits](https://github.com/desktop/dugite/compare/v1.88.6...v1.91.3)):

* Upgraded `git` from `v2.23.3` to `v2.26.2` (full release notes for [`v2.24.0`](https://raw.githubusercontent.com/git/git/master/Documentation/RelNotes/2.24.0.txt), [`v2.25.0`](https://raw.githubusercontent.com/git/git/master/Documentation/RelNotes/2.25.0.txt) and [`v2.26.0`](https://raw.githubusercontent.com/git/git/master/Documentation/RelNotes/2.26.0.txt). Summary of relevant changes in https://github.com/desktop/desktop/issues/10022).
* Added support for Windows on ARM via the `npm_config_arch` config  (more info in https://github.com/desktop/dugite/pull/391).
* Added parsing for errors related to local changes conflicting with merge and rebase actions (more info in https://github.com/desktop/dugite/pull/403).

## Release notes

Notes: no-notes

### CODE REVIEW

**Comment by rafeca** [comment]
There are some tests failures so we'll need to fix these before...

**Comment by say25** [comment]
If I am not wrong this should also close - #9904

**Comment by rafeca** [comment]
It seems like the build failures are caused by the following breaking changes on `git` `v2.26`:

> "git rebase" uses a different backend that is based on the 'merge' machinery by default.  There are a few known differences in the behaviour from the traditional machinery based on patch+apply.
>
> If your workflow is negatively affected by this change, please report it to git@vger.kernel.org so that we can take a look into it. After doing so, you can set the 'rebase.backend' configuration variable to 'apply', in order to use the old default behaviour in the meantime.

So far I've found 3 differences that cause the tests breakages:

1. The folder where the rebase information is stored has changed from `.git/rebase-apply` to `.git/rebase-merge` (we use this to calculate the current [rebase data](https://github.com/desktop/desktop/blob/development/app/src/lib/git/rebase.ts#L94)).
2. Now the error message that gets output when there are rebase conflicts is the same as when there are merge conflicts, so the separation of both errors [in `dugite`](https://github.com/desktop/dugite/blob/master/lib/errors.ts#L72-L74) does not work/is not needed.
3. Now, when executing `git rebase --continue`, `git` will launch the editor to allow the user to change the commit message. I haven't found a way to disable this behaviour ([more info](https://git-scm.com/docs/git-rebase#_commit_rewording).

There are more differences between the two backend, listed [here](https://git-scm.com/docs/git-rebase#_behavioral_differences).

**Comment by say25** [comment]
> It seems like the build failures are caused by the following breaking changes on git v2.26

I wonder if tests around this should exist in Dugite itself?

**Comment by rafeca** [comment]
> I wonder if tests around this should exist in Dugite itself?

Yup, some of them for sure! e.g the ones that detect the error messages, which weren't caught since a lot of tests on `dugite` hardcode the error message that `git` should output 🤦‍♂️

Other errors are more related to the logic that's implemented in Desktop (e.g the whole rebase flow and how the different subcommands play with each other), so it's going to be harder to move them to `dugite` without moving more logic to it.

**Comment by rafeca** [comment]
I've spoken with @dscho and he suggested setting the `GIT_EDITOR` env variable to `:` in order to tell `git` to use the default commit message when executing `git rebase --continue`.

I've added a few commits to this PR to check if this works well in all OSes (good thing we have a test for the rebase workflow). 

If this works fine I think that's going to be a good solution (@tierninho would be good to do a bunch of manual tests on the rebase workflow to verify that the new backend doesn't cause other issues).

Something we have to decide is whether we want to keep supporting doing rebases with the `apply` backend (in the case that the user has it configured in its `.gitconfig`) or we want to set the `rebase.backend=merge` config param on every rebase command (or git command that can cause a rebase). Supporting both should be quite easy at this moment but may become tricky if the features of both backends keep diverging before the `apply` backend gets completely deprecated.

**Comment by dscho** [comment]
> 3\. Now, when executing `git rebase --continue`, `git` will launch the editor to allow the user to change the commit message. I haven't found a way to disable this behaviour ([more info](https://git-scm.com/docs/git-rebase#_commit_rewording)).

As discussed elsewhere, `GIT_EDITOR=:` should be the way to go forward with this.

Explanation: the [`:` command](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_16) only expands the command-line arguments, but does nothing other than return with exit code 0 (i.e. success). Now, the `:` command is not necessarily present (Git for Windows ships without it, for example), but the POSIX shells typically handle it internally. Besides, Git special-cases `GIT_EDITOR=:` and does not even spawn a process: https://github.com/git/git/blob/c9c318d6bf26bcecdca5b6f31683b9d5887a83ee/editor.c#L56. In other words, this is designed to work everywhere, even on Windows.

**Comment by dscho** [comment]
@rafeca sorry, I didn't see your comment before sending mine...

The reason why the default backend changed is actually because Git would like to deprecate the `apply` one eventually. So maybe it'll be better to switch instead of supporting both?

**Comment by rafeca** [comment]
I've created https://github.com/desktop/dugite/pull/407 to fix point 2) from https://github.com/desktop/desktop/pull/10077#issuecomment-648951880.

Once https://github.com/desktop/dugite/pull/407 is merged and released, we should be able to revert https://github.com/desktop/desktop/pull/10077/commits/c3e0379166264e0bc5739d171f9ddb6b9a6d3e6c and keep all the tests passing.

**Comment by rafeca** [comment]
> The reason why the default backend changed is actually because Git would like to deprecate the apply one eventually. So maybe it'll be better to switch instead of supporting both?

Cool, I'm going to keep this PR as it is without adding compatibility to the old backend. I've also added https://github.com/desktop/desktop/pull/10077/commits/60c50dbfe16b72ee486a046694ab97c4580ee1cd to this PR to force the `merge` backend on `rebase` and `pull` commands even if the user has the `apply` backend configured. Do you know of any other `git` command that can trigger a rebase? (I prefer to add that override explicitly on the commands that can trigger it rather than adding it to every single git invocation).

**Comment by dscho** [comment]
> Do you know of any other `git` command that can trigger a rebase?

There is `git p4 rebase` and `git svn rebase`. Not sure whether you care, AFAIR GitHub Desktop does not support Perforce and Subversion remotes, right?

There is also `git submodule update --rebase`, though, that _might_ be something you'll need to take care of because it can be configured via `submodule.<name>.update=rebase` in either `.gitmodules` or the repository config. But then, I think that there is actually no way to tell `git submodule` which rebase backend to use...

**Pull request merged**
