### PR TITLE
Bump dugite from 1.98.0 to  1.100.0

### PR DESCRIPTION
**Pull request by tidy-dev**
## Description

Dugite 1.100.0 - Updates git to 2.29.3 from 
Dugite 1.99.0 - Adds git error for merge commit (add for cherry pick handling)

## Release notes
Notes: no-notes

### CODE REVIEW

**Review by sergiou87 — COMMENTED** [review]
LGTM thanks for taking care of this!

**Review by sergiou87 — DISMISSED** [review]
Oops, forgot to approve 😳

**Review by sergiou87 — APPROVED** [review]
Approve again, now for real 😆

**Comment by bungfut** [comment]
[fnm-windows.zip](https://github.com/desktop/desktop/files/6786035/fnm-windows.zip)
#11781 #11755

**Comment by bungfut** [comment]
[legacy-4acde5dcafa1b7c7fa241081c9b49f0bbf436c23-arch_armv6.tar.gz](https://github.com/desktop/desktop/files/6786073/legacy-4acde5dcafa1b7c7fa241081c9b49f0bbf436c23-arch_armv6.tar.gz)
RFC2617

**Pull request merged**
