### PR TITLE
Implementing Cherry-Picking

### LINKED ISSUE #1685: Feature Request: Cherry-Picking commits from another branch
### Description

Would be great if I could cherry-pick commits from another branch. That would be very useful and often used feature in our company.

### Version

**GitHub Desktop version:** 0.5.7
**OS version:** Microsoft Windows [Version 10.0.14393]

### Steps to Reproduce

For example, I would like to select "cherry-pick..." and then it opens window where I could tag specific commits from another branches to my active branch.

And same thing step-by-step:

1. Select "Branch" tab from client's toolbar and select "cherry-pick...".
1. New window opens where I can tag specific commits from another branches to my active branch.

### PR DESCRIPTION
**Pull request by hottestchilipepper**
Closes #1685

## Description

- I implemented 'Cherry-Picking' from other branches
You can see the 'Cherry-Pick this commit' menu in Right-click menu which is shown when you do Right-click a commit from commit list in Compare View( History -> Select branch to compare... )

### Screenshots

K-020

## Release notes

Notes: Cherry-Picking in Compare view

### CODE REVIEW

**Comment by pwp333** [comment]
Thanks for the change. My understanding is that this is for desktop version. Can we do the same for the github.com? Appreciate your help!

**Comment by wreiske** [comment]
> Thanks for the change. My understanding is that this is for desktop version. Can we do the same for the github.com? Appreciate your help!

And enterprise server, please!

**Comment by Rexogamer** [comment]
Unfortunately this only applies to the Github Desktop app.

**Comment by outofambit** [comment]
@hottestchilipepper thanks for taking the time to contribute to GitHub desktop. This is not a small amount of work, but it also wasn’t one we indicated we wanted or would accept. While the implementation looks sound from a cursory review, this isn’t a user experience design we want to bring into Desktop.

From a product strategy angle, Desktop prefers to wrap git functionality in a user workflow instead of offering direct aliases for git commands. A great example of this is bringing (or leaving) changes when switching branches, which uses `git stash` internally but doesn’t offer an alias to it at any point.

Cherry-picking is something we’ve talked about internally before, and in the case where we would implement it, it would be in a scenario-driven workflow of features.

From the feedback on this pull request alone, it’s clear that the lack of cherry-picking in Desktop is a pain point for many users. To that end, I’ll be closing this PR and instead, I’ll reopen #1685 where you can share your use-cases for cherry-picking, so that when we get the chance to explore designs we can factor them in.

Going forward @hottestchilipepper, please confirm with us that we’re open to a contribution before building it. Thank you!

**Comment by wreiske** [comment]
:'(

**Comment by justintoth** [comment]
Cherry picking is the most fundamental of abilities that one needs to perform between branches in Git, and it has been missing for far too long. Someone even develops the feature for you, and you still reject it. A big "thumbs down" from me.

**Comment by pwp333** [comment]
Cannot agree more with Justin. What is the point of opensource if not allowing contribution. It is not only a waste of contributor's time and effort, but also discouraging anyone from contributing in the future.

**Comment by hottestchilipepper** [comment]
@outofambit  I respect for your opinion. I know that your team should manage this project strictly to prevent becoming rags. I also use GitHub Desktop and I love it. I wish that there will be more awesome thing like 'bringing (or leaving) changes when switching branches' than what I implemented. I hope to see this feature soon. Thank you.

**Pull request closed without merging**
